### ISSUE TITLE
Suggestion: Save images to FOLDERID_ProgramData and config file to FOLDERID_RoamingAppData

### ISSUE THREAD

**Issue by lx-s** [t1m0thyj/WinDynamicDesktop#1]
Hi there,

a suggestion for your tool: You could save the images.zip file user independent location [`%ProgramData%\WinDynamicDesktop`](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457.aspx) and your settings.conf to [`%AppData%\Roaming\WinDynamicDesktop`](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457.aspx).
This would make it easier to run your program from its own `%ProgramFiles%`-Folder without tinkering with folder permissions.

A downside to this is, that it would make removing your program a bit more involved, since the user would have to delete these folders manually. This would have to be mentioned in the README I guess.

**Comment by Martin5001** [comment]
If you decide to implement this suggestion it would be good to keep the portable version too.

**Comment by Martin5001** [comment]
Also it would probably need an (un)installer so the user would not have to delete these folders manually.

**Comment by CSharpFan** [comment]
When you uninstall you can't delete things from %APPDATA%, as that is tied to the current user.

Imagine an application installed in Program Files, and there are 2 users on the computer.

User one opens, settings saved in User1AppData
User two opens, settings saved in User2AppData

User 2 uninstalls app, application uninstaller can only clean up User2AppData (you don't have access to User1AppData)

**Comment by t1m0thyj** [comment]
I've added an installer, which has the default destination folder `%LOCALAPPDATA%\Programs\WinDynamicDesktop`. The portable version is still available for download too, I don't plan to stop making it available.

It might be better to use the ProgramData and Roaming AppData folders, but currently I prefer the simplicity of keeping the entire file structure used by the app in a single folder. If anyone strongly disagrees with this, feel free to reopen this issue.
