### ISSUE TITLE
Night Light - Feature Request

### ISSUE THREAD

**Issue by StormCoder7** [t1m0thyj/WinDynamicDesktop#102]
Is it possible to turn Night Light on and off whenever the sunrise and sunset image goes up? As well as this can you tweak the images so they don't become hard to see when Night Light is on, or at least have a feature to toggle that?

**Comment by t1m0thyj** [comment]
> Is it possible to turn Night Light on and off whenever the sunrise and sunset image goes up?
Windows 10 has built-in the feature to turn Night Light on and off based on sunrise/sunset so I don't see the need to add this in the app. (Also the format for the registry key that controls the Night Light feature seems complex and not necessarily consistent between versions of Windows [see [here](https://superuser.com/a/1209192/517562)] which would make me hesitant about doing this in the app.)

> As well as this can you tweak the images so they don't become hard to see when Night Light is on, or at least have a feature to toggle that?
If I understand correctly you mean to disable the effects of Night Light for the wallpaper image when the desktop is shown, but have it enabled everywhere else. This isn't really possible as far as I know, if Night Light is on Windows is going to tint the whole screen and I can't control that in my app.

**Comment by StormCoder7** [comment]
Ok sure, thanks, what I meant by disabling the affects was changing the colour temperature of the wallpaper according to what your desired night light affect is. I don't know if this is possible (or easy).

**Comment by t1m0thyj** [comment]
@StormCoder7 Just to be clear, do you mean a feature that would be separate from night mode and would change the wallpaper color temperature to mimic night mode? Or a feature that would somehow work in conjunction with night mode while it is turned on?

**Comment by StormCoder7** [comment]
I mean while Night Light is turned on, you give users the option to adjust the colour temperature of the wallpaper so it's easier to see.
