### ISSUE TITLE
Problems in Scandinavian countries

### ISSUE THREAD

**Issue by t1m0thyj** [t1m0thyj/WinDynamicDesktop#104]
The app currently does not handle regions of the world that have polar day/night during parts of the year, and the SunCalc.Net library throws an exception when one of these regions is used for a location.

**Comment by FantasiaChan** [comment]
Use DateTime.Now instead.

**Comment by t1m0thyj** [comment]
`DateTime.Now` is used some places in the code, but I also need a way to calculate when sunrise and sunset occur for the user's location. I submitted a [PR](https://github.com/kostebudinoski/SunCalc-Net/pull/1) to the SunCalc library that should fix the problem in the next version of the app.

**Comment by kostebudinoski** [comment]
New SunCalc.Net version 1.0.3 is available in Nuget that fixes the problem with the polar day/night during these parts of the year:

https://www.nuget.org/packages/SunCalcNet/1.0.3

**Comment by FantasiaChan** [comment]
if issue is solved why issue is still opened? (bad english)

**Comment by t1m0thyj** [comment]
Because it isn't solved yet in the app. The Suncalc.Net library now has the fix needed, but I need to consume it in WDD and make some changes to how I use it. This should be done in the next version.

**Comment by t1m0thyj** [comment]
Fixed in version 3.2.1

**Comment by MuggeGHQ** [comment]
mmm, The app store version says there is a update but when i press update. There is no new version in app store so nothing happen ?

**Comment by t1m0thyj** [comment]
@MuggeGHQ New versions don't show up immediately on Windows Store, they have to be approved by Microsoft first. Usually the approval process takes 1-3 days, if you want the bleeding edge then GitHub version is better.

**Comment by t1m0thyj** [comment]
@MuggeGHQ Just got published, 3.2.1 which contains the fix should be available on the Store now.
