### ISSUE TITLE
Simplified Chinese translation added

### ISSUE THREAD

**Issue by zhangyuesai** [t1m0thyj/WinDynamicDesktop#105]
I made a Simplified Chinese translation and uploaded it here:
[zh_CN.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/2935695/zh_CN.txt)
It works on 3.1.0 (installer version) on Windows 10 version 1809.
`.po` files are not supported in Issue attachments so I changed the filename extention to `.txt`.

**Comment by t1m0thyj** [comment]
Thanks for the translation, I'm working on adding it to the next version of the app and have moved it to a separate repository where you can upload updated files in the future: https://github.com/t1m0thyj/WDD-locale/issues/5
