### ISSUE TITLE
App is not launching

### ISSUE THREAD

**Issue by sotiriszampras** [t1m0thyj/WinDynamicDesktop#108]
Everytime I open the app it says to see the log file:
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/2979349/WinDynamicDesktop.exe.log)

 - Windows version: 10 build 18855
 - Installation source: Microsoft Store

**Comment by FantasiaChan** [comment]
I can't help there ._.

**Comment by FantasiaChan** [comment]
try the GitHub version

**Comment by sotiriszampras** [comment]
> try the GitHub version

Thanks it worked

**Comment by FantasiaChan** [comment]
For t1m0thyj: I noticed that the version with GitHub works more stable than with Windows Store.

**Comment by t1m0thyj** [comment]
@sotiriszampras Thanks for reporting, this should be fixed in the next version of the app.

@FantasiaChan You are correct, not totally sure why but I hope to improve the stability of the Windows Store version over the new few releases.

**Comment by t1m0thyj** [comment]
This should now be fixed in version 3.2.0 which was released on the Microsoft Store today.
