### ISSUE TITLE
Small log update

### ISSUE THREAD

**Issue by FantasiaChan** [t1m0thyj/WinDynamicDesktop#109]
app.manifest updated
Program.cs updated
After each mistake (Google translate??) they stuck together and nothing was clear. Now a line will be created between errors and it will be possible to divide them among themselves. I've improved the exception handling too.
If "log file couldn't be opened" errors will be better decorated and read them will also be easier

**Comment by FantasiaChan** [comment]
[WDD.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/2993491/WDD.txt)
WDD.txt make WDD.rar!!!

**Comment by FantasiaChan** [comment]
I forget attach the file ._.
[src.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/2999181/src.txt)
Make src.txt -> src.rar

**Comment by FantasiaChan** [comment]
Working?

**Comment by t1m0thyj** [comment]
In the future if you could create a branch of the repo in your fork and push changes to it, that would be an easier way to compare changes than uploading a RAR file.

Regarding the suggested changes, I believe the log files already contained all the information about errors but agree that it was rather jumbled. I think adding a new line between exception data should be a simple way to fix this, and have made this change in my code.

Regarding the `app.manifest`, I see that you uncommented out two sections but am not sure why. Could you explain the purpose of having those lines in the manifest? Did adding them fix the problem you were having with running the app on Windows 7?

**Comment by ceprickett** [comment]
Thanks 😊😘

**Comment by t1m0thyj** [comment]
Just released a new version (3.2.0) with improved error logging.
