### ISSUE TITLE
[BUG] Display menu automatically when switch tablet mode to desktop mode

### ISSUE THREAD

**Issue by sorcererxw** [t1m0thyj/WinDynamicDesktop#111]
When reporting a bug please provide:
- Steps to reproduce it
  1. [Settings] Auto hide taskbar on desktop mode + Always show taskbar on tablet mode
  1. Launch WinDynamicDesktop
  2. Switch to tablet mode
  3. Switch to desktop mode
  4. The WinDynamicDesktop menu will display without any click. And i cant click outside to dismiss it.
- Screenshots: ![](https://i.imgur.com/em7jMdF.png)
- Windows version: Win10 Home 1809
- WinDynamicDesktop version: 3.1.0 (UWP) from Microsoft Store

**Comment by t1m0thyj** [comment]
Can no longer reproduce this behavior with Windows 11 and WDD 5.
