### ISSUE TITLE
Problem with wrong screen fit

### ISSUE THREAD

**Issue by TFJ1802** [t1m0thyj/WinDynamicDesktop#112]
<img width="1078" alt="Annotation 2019-03-29 110154" src="https://user-images.githubusercontent.com/49064004/55228494-21b66000-5212-11e9-89d8-f970e7b4e47a.png">
Problems with the default screen fit on the wallpaper is it possible to change the fit.
thanks,

**Comment by t1m0thyj** [comment]
Are you using the Windows Store version of the app? If so, there is a [known issue](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Known-issues#wallpaper-fit-not-saved-with-multiple-monitors) where wallpaper fit doesn't get saved if you change it after installing WinDynamicDesktop. If you reset the Store app (or uninstall and reinstall it) it should remember the fit that you selected, or if you use the desktop version from GitHub you shouldn't encounter this problem.

**Comment by TFJ1802** [comment]
ok thanks



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/01/19,
8:58:53 AM

**Comment by TFJ1802** [comment]
Tried it but its still got the problems



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/01/19,
10:26:10 AM

**Comment by TFJ1802** [comment]
I mean did the github install



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/01/19,
10:35:10 AM

**Comment by t1m0thyj** [comment]
It looks like your screenshot is larger than the resolution of the Firewatch theme which is 1920x1080. Because of this the Center fit won't fill the whole screen, you'd need to stretch the image. Feel free to reopen the issue if this isn't the case.

The default themes shouldn't have this issue but the resolution of community themes is beyond my control. I'll add resolution info to each one on the GitHub page.
