### ISSUE TITLE
Extracted wallpapers from OSX are low quality

### ISSUE THREAD

**Issue by Stealer0** [t1m0thyj/WinDynamicDesktop#116]
Original Mojave.heic file 140mb, while extracted jpegs 40mb only.
There's significant compression.

There's a long discussion about that on reddit with no knowledge on how to extract it accordingly.
The only user came with workaround is to use PNG with P3 > sRGB loss.

Finally here's the answer.
Url to download 279.5mb tiff lossless wallpapers:
https://www.reddit.com/r/apple/comments/99t4za/all_16_macos_mojave_dynamic_wallpapers_5k_tiff/

I've converted them to jpegs to use with WinDynamicDesktop:
https://1drv.ms/f/s!AqMSFEWkJ4T3oWUEyedoJtQx7-TV

Enjoy!

**Comment by Stealer0** [comment]
* reddit discussion
https://www.reddit.com/r/apple/comments/8oz25c/all_16_full_resolution_macos_mojave_dynamic/e07eisu/

**Comment by t1m0thyj** [comment]
Thanks for uploading the higher quality version, I've replaced the low quality downloads with it. It's still the same download link, so if you delete the `themes/Mojave_Desert` folder in WDD and restart the app it should automatically download the higher quality version.

**Comment by TheGoldmasterCorporation** [comment]
how do you convert them?
