### ISSUE TITLE
Automatic translation improvement

### ISSUE THREAD

**Issue by FantasiaChan** [t1m0thyj/WinDynamicDesktop#119]
I suggest: on first start the program , take ~~from the Envoirment~~ the OS language ~~(OSVersion)~~, and substitute the value in the .conf file using the File.WriteAllText method (e.g.
if (OSLanguage == "RU_ru")
  File.WriteAllText(*conf settings*)

(Very bad translate from google. )

**Comment by FantasiaChan** [comment]
UPD:
Get OS language:
var culture = System.Globalization.CultureInfo.CurrentCulture;
    if (culture.ToString() == "ru-RU")
       File.WriteAllText("PATH TO CONF FILE","TEXT TO BE INSIDE THE FILE WITH lang: ")

**Comment by t1m0thyj** [comment]
It should automatically determine the best translation based on your system locale as can be seen in this line here: https://github.com/t1m0thyj/WinDynamicDesktop/blob/master/src/Localization.cs#L47

Did the app fail to automatically translate into Russian for you after upgrading to 3.2.0?

**Comment by FantasiaChan** [comment]
Nope. All correct

**Comment by t1m0thyj** [comment]
To be clear you mean that it did *not* work?

**Comment by FantasiaChan** [comment]
I'm confused.

**Comment by t1m0thyj** [comment]
When you upgraded from version 3.1.0 to 3.2.0, did it automatically detect that Russian was your system language? It should but I'm assuming that didn't work, hence the reason why you created this issue.

**Comment by FantasiaChan** [comment]
I thought it wasn't implemented yet.

**Comment by t1m0thyj** [comment]
Did you need to manually open the language dialog to select Russian?

**Comment by FantasiaChan** [comment]
No. It translated automatically

**Comment by FantasiaChan** [comment]
I opened this issue, thinking that this is not yet implemented, but I was mistaken
