### ISSUE TITLE
Wallpaper doesn't always update on wake from sleep

### ISSUE THREAD

**Issue by t1m0thyj** [t1m0thyj/WinDynamicDesktop#12]
When I originally tested the app this was working, but recently it stopped working on my PC. This seems more serious than what I reported as #7. Currently it's difficult to debug the program when not running it from Visual Studio, so probably should implement #8 first.

**Comment by ivocass** [comment]
Great app! Although in my case it never updates on wake from sleep (Windows 10 Pro x64 v1709). Using "Refresh Wallpaper" for now.

**Comment by t1m0thyj** [comment]
Just released version 1.3, with rewritten code for the wallpaper change scheduler. Can you please try the new version and let me know if this problem still exists?

**Comment by ivocass** [comment]
> Can you please try the new version and let me know if this problem still exists?

So far so good! I'll report again this weekend, so I can test it some more.

**Comment by MnemonicWME** [comment]
1.3 fixed the problem for me, thank you,
