### ISSUE TITLE
Trying to add a translation

### ISSUE THREAD

**Issue by Sebosz** [t1m0thyj/WinDynamicDesktop#120]
Hi there! I'm trying to make a translation to polish, but after I pasted the file and changed .conf file, language didn't change.
I've attached translation files.

[pl_PL.mo.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/3135404/pl_PL.mo.txt)
[pl_PL.po.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/3135405/pl_PL.po.txt)

**Comment by FantasiaChan** [comment]
Can you attach the .conf file?

**Comment by Sebosz** [comment]
[settings.conf.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/3137630/settings.conf.txt)

**Comment by FantasiaChan** [comment]
delete ".mo"
![image](https://user-images.githubusercontent.com/39629381/57190731-9e7ddd80-6f26-11e9-841a-98737a8205e5.png)

**Comment by FantasiaChan** [comment]
it should be
"language":"pl_PL" without .mo

**Comment by FantasiaChan** [comment]
UPD: I looked at the source code and concluded that it would not accept your language anyway.
I make a separate version for the Polish language, wait a bit.

**Comment by Sebosz** [comment]
Hey, I removed .mo from the file and everything works :) Also I updated the file, because I used % once instead of &.
I'd like to notice that not everything could be translated - just like shown on pic.
![1](https://user-images.githubusercontent.com/50180018/57192848-616d1780-6f35-11e9-818b-3652c18915e8.png)

**Comment by FantasiaChan** [comment]
I have the same problem.

**Comment by Sebosz** [comment]
Anyway besides that, the translation I attached yesterday seems ready & works for me.

**Comment by FantasiaChan** [comment]
In version 3.2.1 you forgot to add Polish ._.

**Comment by t1m0thyj** [comment]
Yeah there's also Czech and Spanish in the wdd-locale repo but I was in a rush to fix the crash because it was a serious bug. I appreciate the new translations and plan to add them soon after I finish finals this week.

**Comment by t1m0thyj** [comment]
@Sebosz Thanks for the translation, it will be added in the next version. The translation strings that were missing should be added in the new POT file I uploaded [here](https://github.com/t1m0thyj/WDD-locale/blob/master/messages.pot). Instructions for updating a translation can be found [here](https://github.com/t1m0thyj/WDD-locale#updating-existing-translation) on the wdd-locale repo. Future updates to the Polish translation can be uploaded [there](https://github.com/t1m0thyj/WDD-locale/issues/8) as well.
