### ISSUE TITLE
Suddenly WinDynamicDesktop stopped working on a computer and laptop.

### ISSUE THREAD

**Issue by FantasiaChan** [t1m0thyj/WinDynamicDesktop#121]
I didn’t do anything, just displays "see the logfile" every time I start it.

Computer | Laptop
------------ | -------------
Windows 7 | Windows 10
WDD 3.2.0 | WDD 3.2.0 (?)
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/3146787/WinDynamicDesktop.exe.log) | [WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/3145275/WinDynamicDesktop.exe.log)

Both stopped working on the same day.

**Comment by FantasiaChan** [comment]
One day, different problems XD

**Comment by ddasutein** [comment]
That's interesting. If I set the location to Russia, I would also get an out of range exception. Can you try and type in another location and see if the error still occurs?

**Comment by FantasiaChan** [comment]
![image](https://user-images.githubusercontent.com/39629381/57210400-33dfa700-6fe5-11e9-8b23-1f7f8bb3f28d.png)

**Comment by FantasiaChan** [comment]
In the field of the city, I entered the "New York" and put a non-existent language. And it still does not want to work.
(Google translate)

**Comment by FantasiaChan** [comment]
I attached the log to first comment

**Comment by t1m0thyj** [comment]
If your config file has a valid language, then the Out of Range exception is caused by some parts of Russia being near the North Pole. Because of this the Suncalc library sometimes fails to retrieve all of the sun phases for your location. See #104.

**Comment by t1m0thyj** [comment]
@FantasiaChan @ddasutein Could you give an example of a location string that was failing for you? Both "Russia" and "New York" work fine for me.

Both of the logs show the same problem, the invalid language errors at the top of the first log are old and the newest errors are at the bottom of the file.

**Comment by MuggeGHQ** [comment]
Same here. Latest version and my country have been working until today.
Copenhagen is not working anymore. Not even the "use windows location service" is working now :(
New York works for me but that's docent work for me. Totally wrong time.
Now what ?

**Comment by MuggeGHQ** [comment]
now i can´t even open the app without getting that error :( So i cant even get into the app and change any settings.

**Comment by t1m0thyj** [comment]
Could you test this EXE and let me know if it works for your location? https://drive.google.com/open?id=1nHb5_SP7vnMLcmVN2x4QNsPbKYZ1xlJi

**Comment by ddasutein** [comment]
@t1m0thyj Here is the log from a fresh build (updated my fork yesterday). This is the result when setting "Russia" as the location. 

[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/3150531/WinDynamicDesktop.exe.log)

**Comment by t1m0thyj** [comment]
@ddasutein Could you try the updated build I posted [here](https://github.com/t1m0thyj/WinDynamicDesktop/issues/121#issuecomment-489730480)? I think it should fix the issue

**Comment by ddasutein** [comment]
Can confirm that build solves the problem. Locations tested; Alaska, Iceland, Norway, Russia, and simply "North Pole" and "South Pole".

**Comment by t1m0thyj** [comment]
Released the fix as version 3.2.1

**Comment by FantasiaChan** [comment]
Yes, this version works fine.
