### ISSUE TITLE
WDD 3.2.1 cannot be installed

### ISSUE THREAD

**Issue by FantasiaChan** [t1m0thyj/WinDynamicDesktop#123]
Submit your bug report or feature request here. If you have questions please ask them on [Gitter](https://gitter.im/t1m0thyj/WinDynamicDesktop) instead.

When reporting a bug please provide:
 - Screenshots (if applicable)
 - Windows version 10
 - WinDynamicDesktop version 3.2.1
 - Installation source - GitHub Setup
![image](https://user-images.githubusercontent.com/39629381/57271822-baee5700-7099-11e9-8dc0-baaab6d36d48.png)

Bonus: I can't delete 3.2.0 version
(Отказано в доступе=access denied)

**Comment by FantasiaChan** [comment]
I'm stupid. I should have opened the installer as an administrator.

**Comment by t1m0thyj** [comment]
Thanks, this wasn't stupid to report. Admin privileges shouldn't be required by the installer, this was caused by upgrading to a new version of Inno Setup (installer tool) and should be fixed now.
