### ISSUE TITLE
How to change "secret" setings on UWP

### ISSUE THREAD

**Issue by MrZyr0** [t1m0thyj/WinDynamicDesktop#125]
Hello,

I've installed the UWP version of WinDynamicDesktop and I want to change some parameters in the settings.conf
It's writte that I can find the file in regular Program Files folder. But there is nothing of the program.

Can I create a folder WinDynamicDesktop in Program File ? 
There is a way to access to the settings of the UWP app ? Because it's impossible to open Windows App folder due to permission restrictions and it's risky to change permission to open it.

Thanks

**Comment by MrZyr0** [comment]
I've found the place of `settings.conf` !
C:\Users\Julien\AppData\Local\Packages\38719TimothyJohnson.WinDynamicDesktop_rfarkse4rn21a\LocalState

I'll edit the readme to specify it because it's not evident

**Comment by FantasiaChan** [comment]
C:\Users\*username*\AppData\Local\WinDynamicDesktop\settings.conf
(?)

**Comment by MrZyr0** [comment]
It was a failed, sorry

**Comment by t1m0thyj** [comment]
@FantasiaChan That's for the desktop version, original question was about the Microsoft Store version.
