### ISSUE TITLE
[Suggestion] With the wallpaper also change the brightness of the monitor

### ISSUE THREAD

**Issue by FantasiaChan** [t1m0thyj/WinDynamicDesktop#128]
For example, at 13:00, set the brightness to full, and set the minimum brightness at midnight.

**Comment by ddasutein** [comment]
Hi there. I'm actually working on this specific feature on my own fork. My proposal for this feature is:

- Brightness will dynamically change at the same time as the wallpaper (Sunrise, Day, Sunset, Night, AllDay, AllNight). 

- Two options. `Auto` and `Custom`. Auto will only change brightness with fixed values. Custom will give you options to customize the brightness level on a specific time of day. 

- Brightness control will be done through the Windows Management Instrumentation (WMI). For this feature to work, your display must have DDC/CI support. I have a test app on my repo where you can experiment with. [Here](https://github.com/ddasutein/BrightnessControl). The code in this project will be implemented in WinDynamicDesktop. I can't guarantee that this may work for all monitors. Unfortunately, my monitor does not support DDC/CI, but my laptop display does. Though most modern laptops should have this functionality out of the box with all the proper drivers installed. I'd appreciate feedback on this if anyone comes across this comment.

- Some work-in-progress screenshots. [Brightness Settings Dialog](https://i.imgur.com/GP92gKv.png), [Brightness Settings Dialog (DDC/CI not supported)](https://i.imgur.com/srqjWoQ.png) [Test notification of WinDynamicDesktop updating the wallpaper and brightness](https://i.imgur.com/5ejhNiH.png)

**Comment by t1m0thyj** [comment]
Feature added in #157 thanks to @ddasutein
