### ISSUE TITLE
Default themes not installed as zips are invalid

### ISSUE THREAD

**Issue by Dj3DX** [t1m0thyj/WinDynamicDesktop#129]
When choosing your location after installing, an error pops up saying that the zip file for Mojave and the Solar gradients is broken. When navigating to WinDynamic folder and trying to manually extract the zips, windows says the zips are invalid and cannot be extracted. A way to fix this would be being able to download the two default themes as .ddw or just providing the zip with all the images thanks.

When reporting a bug please provide:
 - Steps to reproduce it:
Not sure, I uninstalled the MS Store edition as I wanted the wallpaper to span my monitors and installed the Github installer. 

 - Windows 10
 - WinDynamicDesktop version: 3.2.1
 - Installation source: Installer and Windows edition

**Comment by t1m0thyj** [comment]
This should be fixed in version 3.3.0 which was just released.
