### ISSUE TITLE
[BUG] Unable to set windows 10 location

### ISSUE THREAD

**Issue by m310012** [t1m0thyj/WinDynamicDesktop#130]
Submit your bug report or feature request here. If you have questions please ask them on [Gitter](https://gitter.im/t1m0thyj/WinDynamicDesktop) instead.

When reporting a bug please provide:
 - Steps to reproduce it
 - Screenshots (if applicable)
 - Log file (if it exists, see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) for how to find it)
 - Windows version (e.g. 7, 10)
 - WinDynamicDesktop version (e.g. 2.0.0)
 - Installation source (e.g. installer, Microsoft Store, portable EXE)

**Comment by m310012** [comment]
After I update WinDynamicDesktop to version 3, I can't click (using) the automatic location windows 10 services (version win 10 pro build 1903). Of course I grant access for WinDynamicsDesktop to using my location on windows settings.

**Comment by t1m0thyj** [comment]
Is this issue still happening? Are you using the Microsoft Store version of the app, or have you downloaded it from GitHub?

**Comment by t1m0thyj** [comment]
This should be fixed in version 4.0, if not feel free to re-open this issue.
