### ISSUE TITLE
How can I contribute and add a language (Macedonian)

### ISSUE THREAD

**Issue by snajdovski** [t1m0thyj/WinDynamicDesktop#131]
I would love to contribute on this project and add my language (Macedonian)

**Comment by FantasiaChan** [comment]
https://github.com/t1m0thyj/WinDynamicDesktop/issues/91#issuecomment-469958567

**Comment by t1m0thyj** [comment]
@snajdovski To create a translation, follow the instructions [here](https://github.com/t1m0thyj/WDD-locale#creating-new-translation) and create an issue in the [wdd-locale](https://github.com/t1m0thyj/WDD-locale/issues/new) repo to upload it. Thanks :)

**Comment by snajdovski** [comment]
Added .txt and .zip file (successfully tested)
