### ISSUE TITLE
New Theme - iOS 13 Black

### ISSUE THREAD

**Issue by sepehrsohrabi** [t1m0thyj/WinDynamicDesktop#133]
iOS 13 Black
[iOS 13 Black.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3271527/iOS.13.Black.zip)

**Comment by t1m0thyj** [comment]
Thanks, added to new WDD themes site: https://windd.info/themes/

(more info about the new site in [this comment](https://github.com/t1m0thyj/WinDynamicDesktop/issues/150#issuecomment-539809111))
