### ISSUE TITLE
New Theme - iOS 13 Blue

### ISSUE THREAD

**Issue by sepehrsohrabi** [t1m0thyj/WinDynamicDesktop#134]
iOS 13 Blue
[iOS 13 Blue.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3271540/iOS.13.Blue.zip)

**Comment by t1m0thyj** [comment]
Thanks, added to new WDD themes site: https://windd.info/themes/

(more info about the new site in [this comment](https://github.com/t1m0thyj/WinDynamicDesktop/issues/150#issuecomment-539809111))
