### ISSUE TITLE
New Theme - iOS 13 Green

### ISSUE THREAD

**Issue by sepehrsohrabi** [t1m0thyj/WinDynamicDesktop#135]
iOS 13 Green
[iOS 13 Green.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3271579/iOS.13.Green.zip)

**Comment by t1m0thyj** [comment]
Thanks, added to new WDD themes site: https://windd.info/themes/

(more info about the new site in [this comment](https://github.com/t1m0thyj/WinDynamicDesktop/issues/150#issuecomment-539809111))
