### ISSUE TITLE
New Theme - iOS 13 Orange

### ISSUE THREAD

**Issue by sepehrsohrabi** [t1m0thyj/WinDynamicDesktop#136]
iOS 13 Orange
[iOS 13 Orange.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3271606/iOS.13.Orange.zip)

**Comment by FantasiaChan** [comment]
3 images?

**Comment by sepehrsohrabi** [comment]
It's actually 2
I don't know why it shows 3

**Comment by FantasiaChan** [comment]
I deleted "Thumbnail.png" and it's show 4 images :/

**Comment by t1m0thyj** [comment]
Thanks, added to new WDD themes site: https://windd.info/themes/

(more info about the new site in [this comment](https://github.com/t1m0thyj/WinDynamicDesktop/issues/150#issuecomment-539809111))
