### ISSUE TITLE
Transition Effect Disappeared After Last Windows 10 Update

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WinDynamicDesktop#137]
Hello,

Transition effect between images disappeared in Windows 10 Home, Version 1903. There is a sudden change of the background images now.

I'm using WinDynamicDesktop 3.3.0 (UWP).

Thanks.

**Comment by ddasutein** [comment]
It seems to be an isolated issue on Windows 10 version 1903. Both my desktop and laptop are having that issue even if switching wallpapers in the Settings app. Might be a good opportunity to file a bug report on the Feedback Hub.

**Comment by alpyn** [comment]
Ok, I'm going to report this bug on the Feedback Hub.

**Comment by 18434351819** [comment]
Thank you for your reply and look forward to his update.

发送自 Windows 10 版邮件应用

发件人: Dasutein
发送时间: 2019年6月20日 16:12
收件人: t1m0thyj/WinDynamicDesktop
抄送: Subscribed
主题: Re: [t1m0thyj/WinDynamicDesktop] Transition Effect Disappeared AfterLast Windows 10 Update (#137)

It seems to be an isolated issue on Windows 10 version 1903. Both my desktop and laptop are having that issue even if switching wallpapers in the Settings app. Might be a good opportunity to file a bug report on the Feedback Hub.

**Comment by MegaMarian12350** [comment]
This bug applies only on the Microsoft store (UWP) version of the app. The standard version (available on GitHub) works flawlessly.

**Comment by t1m0thyj** [comment]
This should be fixed in version 3.4.1 of the Microsoft Store app which was released this week.
