### ISSUE TITLE
Support for Heic photos

### ISSUE THREAD

**Issue by TheGoldmasterCorporation** [t1m0thyj/WinDynamicDesktop#140]
Hi there when you support importing heic photos?

there are quite a good number at dynamicwallpaper.club that i would love to use

**Comment by 18434351819** [comment]
sorry ,i don't have iPhone ,so no HEIC.In fact, if it is a static drawing, wallpaper can be set directly




------------------ 原始邮件 ------------------
发件人:  "TeamGoldmaster"<notifications@github.com>;
发送时间:  2019年7月3日(星期三)上午7:52
收件人:  "t1m0thyj/WinDynamicDesktop"<WinDynamicDesktop@noreply.github.com>;
抄送:  "Subscribed"<subscribed@noreply.github.com>;
主题:  [t1m0thyj/WinDynamicDesktop] Support for Heic photos (#140)




Hi there when you support importing heic photos?
 
there are quite a good number at dynamicwallpaper.club that i would love to use

**Comment by t1m0thyj** [comment]
There are no plans to directly support importing HEIC photos, it would be convenient but the image format is not natively supported on Windows. However, you can convert them to an image format that is compatible with WinDynamicDesktop and create a custom theme using the images as mentioned [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes#image-files):
> If you want to use a set of HEIC images (the format used by macOS for dynamic wallpapers), they need to be converted to a different format because HEIC is not natively supported by Windows. You can easily convert them to JPEG format with [this online image converter](https://strukturag.github.io/libheif/).
