### ISSUE TITLE
Proxy Server not supported

### ISSUE THREAD

**Issue by vailatis** [t1m0thyj/WinDynamicDesktop#145]
- Install program on a computer behind a network internet proxy.
 - Windows 10
 - WinDynamicDesktop 3.3.0
 - Installation source: Installer

It seem that your current version does not support internet access through a network proxy, since there is no way or places to configure the Proxy Server, Port and optional proxy credentials in order to let the program to reach internet other than in direct routed way. This prevent the program to get configured and used for all those people that doesn't have a direct internet connection, but that need to use a proxy server with or without authentication.

**Comment by FantasiaChan** [comment]
[Google Translate]
Since the application is written in C# , it uses proxy settings with Internet Explorer or Microsoft Edge. The proxy configuration inside them and WDD should connect

**Comment by F3neden** [comment]
I have the same issue. Currently programming a proxy extension that provides authentication via username and password.

**Comment by t1m0thyj** [comment]
Proxy support added in https://github.com/t1m0thyj/WinDynamicDesktop/commit/3e49426700dbaedc9c42ee3ea551336396600ce9 and will be in the next version of WDD.

**Comment by t1m0thyj** [comment]
Support for web proxies defined in HTTP_PROXY and HTTPS_PROXY environment variables was added in version 4.1.0 which was just released. The update may take 24 hours to show up on Microsoft Store.
