### ISSUE TITLE
Missing for translations uwp/use beter platform for translation

### ISSUE THREAD

**Issue by 07pepa** [t1m0thyj/WinDynamicDesktop#146]
There are some missing translations (if you think of it as hashmap even keys are missing in *.mo file (at least at czech))  of some sentences in win dynamic desktop.

 list of them with languages  (1st level is  untntranslated word 2. is languages where was not translated.

- About (in context menu)
   - deusch
   - czech
   - french
   - greek
- Select Language (in context  submenu) /modal window when you click on this option
   - czech
   - deusch
   - french
   - greek

As you can see this is suboptimal way how to translate see and manage what is missing were...
even for this small project

there are more advance tools  sugested on stack owerflow for c# is [transifex](https://pypi.org/project/transifex/) but you need your own hosting
but in my experiences it is best when **new translation** can be applyed ad hoc (you can see what you wrote)

**Comment by t1m0thyj** [comment]
Thanks for bringing this up, I agree the current process for managing translations is not ideal. I'm experimenting with using [Zanata](https://translate.zanata.org/project/view/windynamicdesktop) to host the translations online, and will investigate ways to make it easier to apply new translations in the app to test.

**Comment by t1m0thyj** [comment]
Translations are now hosted on [Zanata](https://translate.zanata.org/project/view/windynamicdesktop).

It is also more convenient now to test updates to a translation. More details can be found [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Translating-the-app#testing-new-translations).
