### ISSUE TITLE
New Theme: Your Name

### ISSUE THREAD

**Issue by jerrylususu** [t1m0thyj/WinDynamicDesktop#150]
Screencaps from anime movie **Your Name 君の名は。 ** (2016).

Adapted from [Dynamic Wallpaper Club](https://dynamicwallpaper.club/wallpaper/6la1i2jp3vj), originally created by user `wallpapyrus`.

[yourname-wallpaper.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3463899/yourname-wallpaper.zip)

**Comment by grand-lotus-iroh** [comment]
This one is cool, how did you convert it though? May you please tell me so I can convert [Licancabur ](https://dynamicwallpaper.club/wallpaper/rzeg18a2re) to .ddw too? Thanks again for share, great job!

**Comment by grand-lotus-iroh** [comment]
UPDATE: I think I found out how to do this, doesn't look too hardcore.

https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes#image-files

**Comment by jerrylususu** [comment]
> 
> 
> UPDATE: I think I found out how to do this, doesn't look too hardcore.
> 
> https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes#image-files

Yeah... I did the conversion manually, since I couldn't find a tool to do the conversion automatically.

I'm wondering how can I add this theme into the wiki page "Community created themes"... Do I need to edit it myself, or is there some maintainer of wiki?

**Comment by t1m0thyj** [comment]
Sorry for taking so long to add this, have been planning a new site for WDD themes for a while. Added your theme to the new site now that it is live: https://windd.info/themes/

The new site will be connected to the "Get more themes" link in the next release of WDD, and the wiki page will be deprecated. Building the new site is also completely automated, so it should be easy to add more new themes in the future.

**Comment by BeLeap** [comment]
![image](https://user-images.githubusercontent.com/46488521/81456987-6d865780-91cf-11ea-951a-741558010f11.png)
Down here looks strange.
Can you fix it?

**Comment by jerrylususu** [comment]
Sorry, but there isn't much I can do... The images are directly extracted from the original HEIC files, which seems to come from the image screenshot.
