### ISSUE TITLE
[Feature Request] "Import from file" should accept .heic file format.

### ISSUE THREAD

**Issue by CarnageMarkus** [t1m0thyj/WinDynamicDesktop#151]
Hi, first of all thanks for great app.

It would be very nice to support `.heic` file format directly (import), so that people don't need to adjust wallpapers from [dynamic wallpaper club](https://dynamicwallpaper.club/)

There are libraries to work with heic:
https://github.com/mczachurski/wallpapper

**Comment by FantasiaChan** [comment]
Why not .ddw

**Comment by CarnageMarkus** [comment]
Because there is far more themes in `.heic` file format, and everyone would be happy, if app would automatically convert them. Not everyone wants to spend hour creating `.ddw` file from `.heic`. This step can be automated. Which means more themes for this app.  👍

**Comment by grand-lotus-iroh** [comment]
Makes sense... how does one convert .heic to DDW anyway from Windows 10 PC? So I visited this site to find a wallpaper, https://dynamicwallpaper.club/gallery, and than I downloaded part of earth (https://dynamicwallpaper.club/wallpaper/rvh95t6f5jj) and i'm stuck with a 15 meg Licancabur.heic file. 

Did I read too fast over the README and miss the tutorial to convert? Beautiful app and thanks for making software, I <3 WinDynamicDesktop alot.

**Comment by grand-lotus-iroh** [comment]
UPDATE: I think I found out how to do this, doesn't look too hardcore.

https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes#image-files

**Comment by Gabgab2003** [comment]
@grand-lotus-iroh That's for multiple files, when you download an heic file from dynamicdesktop.clubr whatever it's called it's a single file. You would need to split it into jpg or png (preferably jpeg) and then compile it to ddw

**Comment by Gabgab2003** [comment]
I haven't found a good way to convert heic to multiple files. I always get a single file. (I only had success with a single app and that was a trial with watermarks)

**Comment by hyad94** [comment]
> 
> 
> Hi, first of all thanks for great app.
> 
> It would be very nice to support `.heic` file format directly (import), so that people don't need to adjust wallpapers from [dynamic wallpaper club](https://dynamicwallpaper.club/)
> 
> There are libraries to work with heic:
> https://github.com/mczachurski/wallpapper

Your right bro, do you find a way to convert .heic to .ddw ? I need Mr sillywalker from dynamicwallpaper club so much

**Comment by hyad94** [comment]
> 
> 
> Makes sense... how does one convert .heic to DDW anyway from Windows 10 PC? So I visited this site to find a wallpaper, https://dynamicwallpaper.club/gallery, and than I downloaded part of earth (https://dynamicwallpaper.club/wallpaper/rvh95t6f5jj) and i'm stuck with a 15 meg Licancabur.heic file.
> 
> Did I read too fast over the README and miss the tutorial to convert? Beautiful app and thanks for making software, I <3 WinDynamicDesktop alot.

Add HEIC format to internet download manager (idm) and download, its work for me.

**Comment by Gabgab2003** [comment]
> 
> 
> > Makes sense... how does one convert .heic to DDW anyway from Windows 10 PC? So I visited this site to find a wallpaper, https://dynamicwallpaper.club/gallery, and than I downloaded part of earth (https://dynamicwallpaper.club/wallpaper/rvh95t6f5jj) and i'm stuck with a 15 meg Licancabur.heic file.
> > Did I read too fast over the README and miss the tutorial to convert? Beautiful app and thanks for making software, I <3 WinDynamicDesktop alot.
> 
> Add HEIC format to internet download manager (idm) and download, its work for me.

what does that download it as? I think he meant he gets a 15 megabytes file and doesnt know what to do with it

**Comment by semool** [comment]
Here you can upload the HEIC file: https://strukturag.github.io/libheif/
After that you can select every single Image in it and save it localy.
Now you can make your Theme with this Images.

**Comment by CarnageMarkus** [comment]
You guys are taking discussion off topic. 

### This is feature request for : Support `.heic` file format, naively in app. 

- There are multiple libraries which can decode `.heic`.
- `.ddw` and `.heic` have basically the same contents.

Therefore, application should support using `.ddw` AND `.heic`  files **directly**. Without need to create custom themes and ask for their acceptance.

**Comment by t1m0thyj** [comment]
I've investigated adding support for `.heic` files in WDD. It would be possible to extract images from a `.heic` file, using the [Magick.NET](https://github.com/dlemstra/Magick.NET) library. However, WDD also needs metadata when importing a theme so it knows the time of day during which each image should be shown. It is also possible to extract this data from `.heic` files, and there are 2 formats:
* `apple_desktop:solar` with solar info data - This metadata format is only used in Apple's wallpapers, and can easily be mapped to the info WDD needs. Apple's wallpapers have already been converted to `.ddw` for use in the app, so not much point in supporting this format.
* `apple_desktop:h24` with time info data - This is the format used by 3rd party wallpapers like the ones on DynamicWallpaper.club. There is no consistent way I could find to map this format to what WDD needs, without knowing the internals of how Apple's wallpaper engine is written. It requires a human to look at the data for each wallpaper and figure out the best way to handle it.

I plan to upload a Python script to the [WDD-themes repository](https://bitbucket.org/t1m0thyj/wdd-themes/src/master/scripts/) soon, that can extract the frames from an `.heic` image as well as the XML metadata. (Will comment here when I upload it.) If someone can figure out a consistent way to convert the `apple_desktop:h24` metadata to the format `[sunriseImageList, dayImageList, sunsetImageList, nightImageList]` that WDD needs, I'll reconsider adding this to the app.

**Comment by t1m0thyj** [comment]
Uploaded the Python script [here](https://bitbucket.org/t1m0thyj/wdd-themes/src/master/extract_heic.py).

**Comment by Gabgab2003** [comment]
Important note: You need to compile/install imagemagick with heic support to use the script, there are a few articles on how to do this

**Comment by PLA2019** [comment]
I have extracted .jpeg from the .heic file, how do I make the theme now?

**Comment by Henboy10** [comment]
> Uploaded the Python script [here](https://bitbucket.org/t1m0thyj/wdd-themes/src/master/extract_heic.py).

Could you make this with a GUI?

**Comment by Gabgab2003** [comment]
@Henboy10 I'll make a gui when I'm home, it will be basic, but functional

**Comment by Henboy10** [comment]
That would be awesome

> @Henboy10 I'll make a gui when I'm home, it will be basic, but functional

**Comment by pilot76103** [comment]
> Uploaded the Python script [here](https://bitbucket.org/t1m0thyj/wdd-themes/src/master/extract_heic.py).

I just tried this script, and for some reason, it's only creating the same JPG file. It appears to extract the correct number from the HEIC file (e.g., 16 images from Mojave.heic and 8 images from Catalina.heic).

![extract_heic Glitch](https://user-images.githubusercontent.com/15096812/72198664-f696a900-33fe-11ea-8586-1202c0497e3e.jpg)

**Comment by kolaqsq** [comment]
> I've investigated adding support for `.heic` files in WDD. It would be possible to extract images from a `.heic` file, using the [Magick.NET](https://github.com/dlemstra/Magick.NET) library. However, WDD also needs metadata when importing a theme so it knows the time of day during which each image should be shown. It is also possible to extract this data from `.heic` files, and there are 2 formats:
> 
> * `apple_desktop:solar` with solar info data - This metadata format is only used in Apple's wallpapers, and can easily be mapped to the info WDD needs. Apple's wallpapers have already been converted to `.ddw` for use in the app, so not much point in supporting this format.
> * `apple_desktop:h24` with time info data - This is the format used by 3rd party wallpapers like the ones on DynamicWallpaper.club. There is no consistent way I could find to map this format to what WDD needs, without knowing the internals of how Apple's wallpaper engine is written. It requires a human to look at the data for each wallpaper and figure out the best way to handle it.
> 
> I plan to upload a Python script to the [WDD-themes repository](https://bitbucket.org/t1m0thyj/wdd-themes/src/master/scripts/) soon, that can extract the frames from an `.heic` image as well as the XML metadata. (Will comment here when I upload it.) If someone can figure out a consistent way to convert the `apple_desktop:h24` metadata to the format `[sunriseImageList, dayImageList, sunsetImageList, nightImageList]` that WDD needs, I'll reconsider adding this feature to the app.

I made a script. Works both for :solar and :h24 types of metadata. uploaded script [here](https://github.com/kolaqsq/WDD-theme-converter) and examples [here](https://drive.google.com/open?id=1IL29EhOAV0jDQwgwcI7P-g1wR37i_Gi3)

**Comment by joezhouchenye** [comment]
Finally, I managed to add a custom .heic file. 
- First, you need to extract jpegs from .heic using Joyoshare HEIC Converter for Mac. 
- Second, rename all files in the format "{filename}_{number}.jpg". 
- Third, manually create and edit the theme.json with the official theme folder content as a reference. 
- Forth, download an official .ddw theme and make a copy. 
- Fifth, open the copy with your compressing software and delete all files within the software.
- Sixth, add all your custom files into the copy.
- Seventh, add the theme like a normal .ddw theme.

Notice:
- The {filename} should replace any space with _.
- The software may be not responding after the last step. I encountered this issue when I made a .ddw file with 96 jpegs. I forced the application to quit and after the restart, everything works fine.

**Comment by Dacron101** [comment]
> Finally, I managed to add a custom .heic file.
> 
> * First, you need to extract jpegs from .heic using Joyoshare HEIC Converter for Mac.
> * Second, rename all files in the format "{filename}_{number}.jpg".
> * Third, manually create and edit the theme.json with the official theme folder content as a reference.
> * Forth, download an official .ddw theme and make a copy.
> * Fifth, open the copy with your compressing software and delete all files within the software.
> * Sixth, add all your custom files into the copy.
> * Seventh, add the theme like a normal .ddw theme.
> 
> Notice:
> 
> * The {filename} should replace any space with _.
> * The software may be not responding after the last step. I encountered this issue when I made a .ddw file with 96 jpegs. I forced the application to quit and after the restart, everything works fine.

Hey, so first i wanted to thank you with your description, it helped me to creat my own ddw, but something went wrong, if i want to load it into the programm, it just keep loading. It would be very nice if you could take a look into the files and say what i did wrong.
Thanks
Jakob

**Comment by Dacron101** [comment]
it doesnt support it, so a make a few screenshots
![fehler1](https://user-images.githubusercontent.com/62934056/78009906-03fa6a00-7342-11ea-84db-5146cc96d7a1.PNG)
![fehler2](https://user-images.githubusercontent.com/62934056/78009918-08268780-7342-11ea-8f1e-d25448b62fe5.PNG)

**Comment by joezhouchenye** [comment]
Two obvious mistake I can tell:

• The json file name should be theme.json not London-24h.json
• The “imageFilename” json key should be “London-24h_*.jpg” (You need to match your actual file name. “*” is a replacement to the number.)

Also, Loading theme from the application will automatically create a thumbnail for your custom theme. However, I am wondering if the custom theme will work by directly editing the settings.conf file.
在 2020年3月31日 +0800 PM5:21，Dacron101 <notifications@github.com>，写道：

**Comment by Dacron101** [comment]
Thanks so much, now it works great, thx

**Comment by TheGoldmasterCorporation** [comment]
well, I am working on converting a bunch from heic to win dynamic. once extracted, just make a note that tells how to change photos.

**Comment by t1m0thyj** [comment]
Since the Python script wasn't necessarily convenient to use, I've created a webpage that can extract images and metadata from multi-image HEICs: https://windd.info/heic/

Note: The extraction process can take several minutes for large images.

**Comment by Dustmix** [comment]
This isn't a perfect solution but i made this [batch file](https://github.com/Dustmix/heic2ddw) that can help convert heic files.

**Comment by Weebo0** [comment]
I see this is a old post but, I've no knowledge on how to code or whatsoever and I wonder if someone can make a very detailed explanation. I have fixed the pics seperated but I dont get what "app" you use to open a script and what json mean?

**Comment by t1m0thyj** [comment]
@Weebo0 If you have separate images, you can now use DDW Theme Creator (thanks to @gdstewart): https://ddw-theme-creator.vercel.app/

**Comment by castiboy** [comment]
A bit late to the conversation, but just thought it was worth noting that there's official HEIC support on Windows 10 through this codec:
https://www.microsoft.com/en-us/p/heif-image-extensions/9pmmsr1cgpwg
By installing it, I can use HEIC images as wallpapers natively, though obviously the image is static on whatever frame it decided to use.

I don't know if this can help the import process in any way (versus the many third party solutions), but I look forward to the day I can simply download these HEIC files and use them, just like it can be done on a mac.

Thanks either way for the work on this cool tool !

**Comment by iamtitere** [comment]
Hey, i've just founded this page, to create and convert from heic https://ddw-theme-creator.vercel.app/

**Comment by TheAlienDrew** [comment]
Kinda wish there was a reverse of this... export from wdd to heic

**Comment by gonace** [comment]
I'm not sure if this is any help, but I found this service (website) https://ddw-theme-creator.vercel.app/ that you can use to create a .ddw from a .heic.

**Comment by PLA2019** [comment]
Any file is wrong
**Error: There was a problem with the .heic file. Try again or select another file.**

https://ddw-theme-creator.vercel.app/

**Comment by gdstewart** [comment]
Hey @PLA2019, I'm not sure why but for whatever reason some .heic files do not allow the photos to be extracted. That's why it was returning the error.

**Comment by PLA2019** [comment]
> Hey @PLA2019, I'm not sure why but for whatever reason some .heic files do not allow the photos to be extracted. That's why it was returning the error.

alright，thank you for you answer

**Comment by bl4k3r** [comment]
So is it possible that "Import from file" will accept the .heic file format in the future?

**Comment by t1m0thyj** [comment]
Probably not - I've tried to get HEIC import working in the [feature-heic](https://github.com/t1m0thyj/WinDynamicDesktop/tree/feature-heic) branch. The blocker for me currently is that without knowing the location in the world and time of year when the picture was taken, it seems impossible to convert the HEIC metadata to the dayImageList/nightImageList that WDD needs. I've gotten close by calculating hour angles for each image in the HEIC metadata, but these aren't reliable since the sun doesn't always rise at exactly 90 deg and set at exactly 270 deg.

**Comment by t1m0thyj** [comment]
This issue has been open for nearly 2 years, during which I've made multiple attempts at implementing support for HEIC import in WDD. I've decided against adding official HEIC support to WDD, since it seems impossible to automate the creation of a theme.json with correct dayImageList/nightImageList (see my previous comment). If you want to convert an HEIC to DDW format, please use this site instead: https://ddw-theme-creator.vercel.app/

**Comment by PL7963** [comment]
apple_desktop:h24 is map by time right? 
Is it possible just changing the wallpaper only by time in the WinDynamicDesktop client? In this way, you may don't have to map h24 to solar.

**Comment by aria-dev** [comment]
Shameless plug for anyone wanting to convert heic to ddw quick: https://github.com/aria-dev/heic-to-ddw/tree/main
