### ISSUE TITLE
New Theme Dragoon

### ISSUE THREAD

**Issue by vladbox79** [t1m0thyj/WinDynamicDesktop#152]
[Dragoon.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3490245/Dragoon.zip)
Submit your bug report or feature request here. If you have questions please ask them on [Gitter](https://gitter.im/t1m0thyj/WinDynamicDesktop) instead.

When reporting a bug please provide:
 - Steps to reproduce it
 - Screenshots (if applicable)
 - Log file (if it exists, see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) for how to find it)
 - Windows version (e.g. 7, 10)
 - WinDynamicDesktop version (e.g. 2.0.0)
 - Installation source (e.g. installer, Microsoft Store, portable EXE)

**Comment by t1m0thyj** [comment]
Thanks for submitting a new theme. [One of the requirements](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes#managing-custom-themes) for theme submissions is:
> Also be sure to include a link for image credits so that proper attribution can be given.

Accordingly, please provide the link that these images were sourced from.

**Comment by t1m0thyj** [comment]
Closing since no link for image attribution has been provided in 90 days. Once the link is provided, I can consider uploading the theme.
