### ISSUE TITLE
New Theme: Part of Earth

### ISSUE THREAD

**Issue by grand-lotus-iroh** [t1m0thyj/WinDynamicDesktop#153]
After you extract, click Import from file... and pick the .json file inside the extracted folder.

[Part-of-earth-wallpaper.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3499297/Part-of-earth-wallpaper.zip)

**Comment by t1m0thyj** [comment]
In order for images to be added to the WDD Themes site, they must be at least HD resolution. These images are 1250x702, which is less than the requirement of 1920x1080.
