### ISSUE TITLE
The download ended.

### ISSUE THREAD

**Issue by pacejiang-awesome** [t1m0thyj/WinDynamicDesktop#154]
Windynamicdesktop 3.3.0 (uwp)
When I downloaded Mojave and Catalina, the program reported an error generating the following log files.
[the 2019-08-19 03:23:20. 639] System. ArgumentOutOfRangeException: index of scope.Must be non-negative and less than the set size.
Parameter name: index
In the System. ThrowHelper. ThrowArgumentOutOfRangeException (ExceptionArgument argument, ExceptionResource resource)
In WinDynamicDesktop. DownloadDialog. DownloadNext (ThemeConfig theme)
In WinDynamicDesktop. DownloadDialog. D__12. MoveNext ()
--- the end of the stack trace in the previous position where the exception was thrown
The System.Runtime.Com pilerServices. AsyncMethodBuilderCore. < > mount __6_0 (Object state)
The download ended.

**Comment by t1m0thyj** [comment]
This should be fixed in the latest version of the Microsoft Store app (3.4).
