### ISSUE TITLE
Dim default wallpaper at night

### ISSUE THREAD

**Issue by disablesilence** [t1m0thyj/WinDynamicDesktop#158]
Feature request: When user select your own custom wallpaper, make this wallpaper darker at night. Switch wallpaper to dimmed when dark mode is activated.

Thank you for great product!

**Comment by t1m0thyj** [comment]
I don't plan to add this feature directly in the app, but it's now possible to create a theme from a single image using DDW Theme Creator (thanks to @gdstewart): https://ddw-theme-creator.vercel.app/

The "Create theme from single image" option can take a single wallpaper image and convert it to multiple images, including dimmer versions for night time or dark mode.
