### ISSUE TITLE
Seperate app and system theme toggles?

### ISSUE THREAD

**Issue by Senexis** [t1m0thyj/WinDynamicDesktop#159]
Heya! Big fan of the utility!

I've recently found out that the system theme changing option works when you don't download the app from the Microsoft Store, and it seems to work just fine for me. One issue I currently have with it, though, is that I can't seem to change whether I want my apps' themes when the system theme changes. I am not a big fan of the apps changing colors drastically at night and would like to have only the taskbar and other elements of the system change instead of both the system and apps.

I would love for there to be two toolstrip menu items; one for system dark mode, and another one for app dark mode. This would still allow everyone who's into that app darkness to still opt into both, but would also allow grumpy sun praisers like me to customize the feature a bit more to our liking.

Suggestion:
In `src/SystemThemeChanger.cs`, at around line 57, introduce an aditional `if` statement for `darkAppTheme` and refactor the current `darkTheme` to `darkSystemTheme`. Of course, some UI and config changes are also needed.

Thank you for considering this feature request!

**Comment by t1m0thyj** [comment]
Feature added by OP in #160
