### ISSUE TITLE
Error when program starts at boot

### ISSUE THREAD

**Issue by t1m0thyj** [t1m0thyj/WinDynamicDesktop#16]
A user on Reddit reported that he gets this error every time the program runs at boot:

> System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
> at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
> at System.Drawing.Image.Save(String filename, ImageFormat format)
> at WinDynamicDesktop.Wallpaper.Set(Uri uri)
> at WinDynamicDesktop.WallpaperChangeScheduler.SetWallpaper(Int32 imageId)
> at WinDynamicDesktop.WallpaperChangeScheduler.StartDaySchedule()
> at WinDynamicDesktop.WallpaperChangeScheduler.StartScheduler(Boolean forceRefresh)
> at WinDynamicDesktop.FormWrapper..ctor()
> at WinDynamicDesktop.Program.Main()

**Comment by V10R37** [comment]
I'm getting the same error.
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/2113963/WinDynamicDesktop.exe.log)

**Comment by Skyr3n** [comment]
I have the same problem

System.Runtime.InteropServices.ExternalException (0x80004005): В GDI+ возникла ошибка общего вида.
   в System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   в System.Drawing.Image.Save(String filename, ImageFormat format)
   в WinDynamicDesktop.Wallpaper.Set(Uri uri)
   в WinDynamicDesktop.WallpaperChangeScheduler.SetWallpaper(Int32 imageId)
   в WinDynamicDesktop.WallpaperChangeScheduler.StartDaySchedule()
   в WinDynamicDesktop.WallpaperChangeScheduler.StartScheduler(Boolean forceRefresh)
   в WinDynamicDesktop.FormWrapper..ctor()
   в WinDynamicDesktop.Program.Main()

**Comment by t1m0thyj** [comment]
The cause of this error is difficult to track down, I think it may be fixed in version 1.2 which was released tonight.

**Comment by t1m0thyj** [comment]
The user who originally reported this bug has said the issue is now fixed. Feel free to reopen the issue if anyone still has this problem in the new version.
