### ISSUE TITLE
[Feature Request] fade when changing wallpaper (day to night)

### ISSUE THREAD

**Issue by jerryshaw12** [t1m0thyj/WinDynamicDesktop#166]
fade when changing the wallpaper to make it more aesthetic

**Comment by Jnss98b** [comment]
Windows should already do that when changing to any static wallpaper

**Comment by dnnkeeper** [comment]
Fade not working for me not for static wallpaper neither for dynamic. I checked 'Animate controls and elements inside windows' option under Visual Effects options in windows Performance menu but still not fade effect working.

**Comment by t1m0thyj** [comment]
This should be fixed in version 3.4.1 of the Microsoft Store app which was released this week.
