### ISSUE TITLE
Unable to import a custom theme

### ISSUE THREAD

**Issue by ondrej-mahdalik** [t1m0thyj/WinDynamicDesktop#167]
Hello,
a friend of mine asked me to make a wallpaper for him.
I got images, made the json file and packed them into a .zip file.
Problem is that every time I try to import them, I get stuck on an import dialog.
![obrazek](https://user-images.githubusercontent.com/49830945/66214311-c209a780-e6c1-11e9-900b-fdca9a1d4d6a.png)

I also noticed that a the zip gets extracted successfully and the thumbnail gets generated as well.
![obrazek](https://user-images.githubusercontent.com/49830945/66214518-23317b00-e6c2-11e9-974d-1d88df1c6236.png)

The only way for me to close the import dialog is to force close the whole app using Task manager. The wallpaper still won't appear after reopening the app.
I tried other 3rd party wallpapers and they work just fine.

Here's the ZIP I made: 
[truck.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3690918/truck.zip)

I don't know whether I created the json incorrectly, or if the problem is something different.

Some information about system & app:
Windows 10 64-bit
App version 3.3.0 (GitHub release)

PS: I also tried the same with .png images and with using the .ddw instead of ZIP, no success either.
PPS: I did not upload the log, because the app did not register any errors, so the log is basically empty.

Thank you for any help.

**Comment by user00101010** [comment]
I tried importing your theme with the original json file, it worked and loaded just fine on my side. I would try deleting the folder with the theme, restarting the app and trying again.

Alternatively here is another sample json file.

`{
  "imagesZipUri": "https://bitbucket.org/t1m0thyj/wdd-themes/downloads/Earth_View.zip",
  "imageFilename": "truck_*.jpg",
  "imageCredits": "AlmightyOndrej",
  "sunriseImageList": [
    1,
    2,
    3,
    4
  ],
  "dayImageList": [
    5,
    6,
    7,
    8,
    9
  ],
  "sunsetImageList": [
    10,
    11,
    12,
    13
  ],
  "nightImageList": [
    14,
    15
  ]
}`

**Comment by ondrej-mahdalik** [comment]
@user00101010 Thank you for the advide. I actually tried deleting the folder and restarting the app multiple times.
What I didn't try, until now, was reinstalling the app. Surprisingly, reinstalling fixed the issue.
Thank you for your help.
