### ISSUE TITLE
New Catalina Wallpapers?

### ISSUE THREAD

**Issue by SkyYkb** [t1m0thyj/WinDynamicDesktop#169]
- Windows version: 10
 - WinDynamicDesktop version: 3.3.0
 - Installation source: Microsoft Store

There is a theme includes 2 images of Catalina previously, but there is whole dynamic images in macOS now.
Is WinDynamicDesktop already has this whole theme now?
If there is, how should I get that?

**Comment by t1m0thyj** [comment]
There is a version with 8 wallpapers available here:
https://bitbucket.org/t1m0thyj/wdd-themes/downloads/Catalina.ddw

There will be a new release of WDD soon that makes it easier to install, in the meantime you'll need to rename the DDW file before importing it so the name doesn't conflict with the 2 image Catalina theme. Sorry for the temporary inconvenience.

**Comment by t1m0thyj** [comment]
Version 3.4.0 is now out on GitHub and should be available soon on the Windows Store. It provides an easier way to reinstall the Catalina theme as described [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Reinstalling-a-bundled-theme).
