### ISSUE TITLE
Can't open app

### ISSUE THREAD

**Issue by iwaly** [t1m0thyj/WinDynamicDesktop#170]
After installing **3.4.0** version I can't open app
_Windows 10, 1903_

Log:
> System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
>    в WinDynamicDesktop.CustomAppConfig.GetDefaultThemes()
>    в WinDynamicDesktop.ThemeManager.Initialize()
>    в WinDynamicDesktop.AppContext..ctor(String[] args)
>    в WinDynamicDesktop.Program.Main(String[] args)

**Comment by t1m0thyj** [comment]
Sorry about this, a change was made to the app that requires it have a "WinDynamicDesktop.exe.config" file in the same folder as the EXE. This was not the intended behavior, I will release a patch to fix this tomorrow. In the meantime, here is how to work around the issue:
* Installer - Redownload from GitHub, I updated the installer to contain the required config file so it should work now
* Portable - Download the config file from GitHub and place it in the same folder as the app EXE
* Windows Store - Doesn't have the problem

**Comment by iwaly** [comment]
**Thanks**, now it works fine  <3
