### ISSUE TITLE
Generate theme from single image on the fly

### ISSUE THREAD

**Issue by pchalamet** [t1m0thyj/WinDynamicDesktop#171]
This is not a bug report.

I've quickly hacked a little tool to generate a ddw file from a single image. It's available here: https://github.com/pchalamet/DynDesktopBuilder
It just modifies brightness of the image from 0 to -50% (using Sine) and package everything.
![image](https://user-images.githubusercontent.com/1562400/66937717-42c09000-f040-11e9-84f2-6f6769347f9b.png)

But this would be nice to have this baked into WDD instead - it's really basic and could be generated on the fly probably (and save megabytes).

Anyway, thanks for the tool. It's lovely.

**Comment by t1m0thyj** [comment]
This is a neat idea. Not sure it belongs baked into WDD as I'd like to keep the core feature set minimal, but this would be an awesome feature to have in a Dynamic Wallpaper Creator app. Added it to potential feature list for such an app: https://github.com/t1m0thyj/WinDynamicDesktop/issues/193#issuecomment-608185041

**Comment by t1m0thyj** [comment]
This now exists [here](https://ddw-theme-creator.vercel.app/), thanks to @gdstewart for creating it!
