### ISSUE TITLE
1st TRY -Catalina

### ISSUE THREAD

**Issue by koubafire** [t1m0thyj/WinDynamicDesktop#173]
Can someone check my Solution for Catalina? If is it bad can you repair it?

https://uloz.to/file/QG69fJYyliN6/24hr-catalina-ddw

**Comment by t1m0thyj** [comment]
An 8-image version of the Catalina theme has already been made available [here](https://bitbucket.org/t1m0thyj/wdd-themes/downloads/Catalina.ddw) and instructions for upgrading to it are [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Reinstalling-a-bundled-theme).

**Comment by t1m0thyj** [comment]
Closing as I believe this has been resolved by the Catalina theme now available inside the app. If that is not the case, feel free to provide more details and reopen.
