### ISSUE TITLE
How do I access the Settings window after I hid the system tray icon, on the MS app?

### ISSUE THREAD

**Issue by VincentJoshuaET** [t1m0thyj/WinDynamicDesktop#174]
Where is the settings.conf located on the MS Store version/UWP?

**Comment by t1m0thyj** [comment]
See the wiki to find where the app is installed: https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed. The `settings.conf` file should also be located there.

**Comment by t1m0thyj** [comment]
Closing because question was answered, feel free to reopen if you have further questions.
