### ISSUE TITLE
Pause wallpaper change while in a 3D application

### ISSUE THREAD

**Issue by user00101010** [t1m0thyj/WinDynamicDesktop#176]
**Issue**
Changing the wallpaper "blocks" a large portion of the GPU performance. You can see core clocks dropping, and as a result if you are currently in a 3D application (e.g. game -- confirmed, movie - supposedly) you get a stutter.
**Other details**
This is not something which seems to be a fault of the application itself, as I confirmed that the same stutter and drop occurs when changing the wallpaper manually without the app running.
**Solution**
As such (since I suppose there is nothing you can do about that) the workaround seems to be to pause the function of wallpaper change when there is a 3D application running and resume upon exit of the game/movie. Since the wallpaper shouldn't be visible during the 3D application, this seems like an acceptable workaround.
**Versions**
 - Windows 10 1809
 - WinDynamicDesktop version 2.4.0
 - Tested and confirmed with both Microsoft Store install and the portable EXE

**Comment by t1m0thyj** [comment]
I planned to add an option to the app almost a year ago that would pause changing the wallpaper while a fullscreen window is open (see [this commit](https://github.com/t1m0thyj/WinDynamicDesktop/commit/4380801629350362e375060e076aa6a8ed7b4768)).

Don't remember exactly why I dropped the idea and reverted the commit, I think at the time I didn't have any evidence of performance impact that made it seem necessary. Now that I have such evidence, I'll plan to reimplement the feature.

**Comment by user00101010** [comment]
Hi Timothy and thank you for the quick reply! Sounds awesome that you are planning to resume work of this, it seems to be the solution for the problem! 

I was definitely able to replicate the issue both with changing the wallpaper from Windows and from the app. The underlying problem seems to be with the Windows wallpaper change. It seems weird, probably something legacy and personally I wouldn't hold my breath of them fixing this even if we reported it to them.

![image](https://user-images.githubusercontent.com/43914198/67964599-35db9900-fc09-11e9-9747-4ba725b7d439.png)
Here is the graph which shows this. The flat line is when the test is running. The ripples happen when there is a wallpaper change. When there is a ripple lie that, the game stutters. Unfortunately I couldn't log an FPS test in this, as when the test is out of focus it's displaying as "0 FPS". Sometimes the stutter is better, sometimes worse. I don't remember the original offender in which I noticed this unfortunately, it was really exhuberated and well shown there.

**Comment by t1m0thyj** [comment]
This feature will be available in the next version of the app, which I hope to release before the end of the year.

**Comment by user00101010** [comment]
This is great news! Thank you very much for your work and happy holidays!

**Comment by t1m0thyj** [comment]
Sorry for the delay, version 4.0 was released yesterday which includes this feature.
