### ISSUE TITLE
Random theme each day

### ISSUE THREAD

**Issue by Rand-o** [t1m0thyj/WinDynamicDesktop#179]
Is it possible to add the ability to have a random theme chosen every day? I use a similar app on Mac OS (24 Hour Wallpaper) it would be great to have this functionality!

**Comment by t1m0thyj** [comment]
This feature will be available in the next version of the app, which I hope to release before the end of the year.

**Comment by user00101010** [comment]
Great idea! Love it, the new version is shaping up to be amazing!

**Comment by t1m0thyj** [comment]
Sorry for the delay, version 4.0 was released yesterday which includes this feature.
