### ISSUE TITLE
New version doesn't remember settings from old version

### ISSUE THREAD

**Issue by lutzke** [t1m0thyj/WinDynamicDesktop#182]
Upgraded from version 3.4.0.0 to version 3.4.1, running Windows 10, and none of the settings from the previous version were remembered. I had to re-enter my location, and re-download 100MB worth of wallpapers. I think it would be nice if upgrading to a newer version were a little more seamless.

**Comment by t1m0thyj** [comment]
Sorry that this happened, settings should be remembered between versions. Are you using the Microsoft Store version of the app, or have you downloaded it from GitHub?
