### ISSUE TITLE
[Feature request] Choosing a fit

### ISSUE THREAD

**Issue by villed3** [t1m0thyj/WinDynamicDesktop#183]
I use a multiple monitor setup. In Windows 10 settings I set the background to be spanned across all monitors, but WinDD resets this every time the background updates. Some of the different fitting options would be neat to have within the app.

**Comment by t1m0thyj** [comment]
Are you using the Microsoft Store version of the app, or have you downloaded it from GitHub? There is a known issue with the Microsoft Store version, that the wallpaper fit resets every time the image is updated. The GitHub version should not have this limitation, it should keep your fit setting the same across multiple monitors.

**Comment by villed3** [comment]
I am indeed using the Microsoft Store version, so that explains it. Thanks for the tip!
