### ISSUE TITLE
New Theme

### ISSUE THREAD

**Issue by elharoldsteven** [t1m0thyj/WinDynamicDesktop#184]
[Mojave XP.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3963341/Mojave.XP.zip)

**Comment by elharoldsteven** [comment]
Update: Better image organisation in sunset and sunrise.

[Mojave XP.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3963380/Mojave.XP.zip)

**Comment by t1m0thyj** [comment]
Thanks for the theme, uploaded to https://windd.info/themes :)
