### ISSUE TITLE
[Feature request] Multiple monitor features

### ISSUE THREAD

**Issue by zhangyuesai** [t1m0thyj/WinDynamicDesktop#185]
Could you please consider adding the following features for multiple monitors?

1. Different locations for different monitors. This is similar to the idea of world clocks, only that different clocks are represented by different images on different monitors. This would be helpful for those who have someone they care about living in a different location.
2. Different themes for different monitors.
3. Combine features 1 & 2 and allow users to appoint a location and a theme for each monitor.

**Comment by t1m0thyj** [comment]
As a fellow user of multiple monitors, I agree these features would be awesome to have. But they are not possible to implement, because the APIs provided by Windows for changing wallpaper do not allow setting separate images for each monitor.
