### ISSUE TITLE
System.FormatException: 该字符串未被识别为有效的 DateTime

### ISSUE THREAD

**Issue by ihtao127** [t1m0thyj/WinDynamicDesktop#186]
When reporting a bug please provide:
 - After I installed the software and launch it, it works well, but if I close it and run it again, there is an error.

 - Screenshots
![图片](https://user-images.githubusercontent.com/12413287/72544903-6fc34f80-3888-11ea-878f-103c36bb5ee4.png)

 - Log file 
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/4072507/WinDynamicDesktop.exe.log)

 - Windows version: 10 (1909)
 - WinDynamicDesktop version: 3.4.1
 - Installation source: installer (WinDynamicDesktop_3.4.1_Setup.exe)

**Comment by ihtao127** [comment]
I try to install the same version(3.4.1) on Microsoft Store, it works well with no errors.

**Comment by t1m0thyj** [comment]
Do you still experience the problem in version 4.0 (released yesterday)?

**Comment by ihtao127** [comment]
> 
> 
> Do you still experience the problem in version 4.0 (released yesterday)?

Yes, I tried with the version 4.0 (Desktop Version) and the problem still happen.

**Comment by galaxygh** [comment]
same problem. maybe it's because that I've changed my system time format? Hoping for you to repair this. thanks

![image](https://user-images.githubusercontent.com/52542986/76014169-1d331500-5f54-11ea-8e13-b6b7e94acdd1.png)

**Comment by t1m0thyj** [comment]
Could you downloading [this test build](https://ci.appveyor.com/api/buildjobs/0v8bo42f02pytgrr/artifacts/src%2Fbin%2FRelease%2FWinDynamicDesktop.exe) and test if the problem still exists? You may need to delete the config file (`settings.conf`) if it still contains dates in the wrong format, but after doing that once the problem should hopefully go away.

**Comment by galaxygh** [comment]
Ok. I tried this version and the datetime problem doesn’t appear anymore. And it works well  when I restart it or reboot the system, which won't before. Thanks.

发件人: Timothy Johnson<mailto:notifications@github.com>
发送时间: 2020年3月6日 12 : 31
收件人: t1m0thyj/WinDynamicDesktop<mailto:WinDynamicDesktop@noreply.github.com>
抄送: galaxygh<mailto:abcdpi@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [t1m0thyj/WinDynamicDesktop] System.FormatException: 该字符串未被识别为有效的 DateTime (#186)


Could you downloading this test build<https://ci.appveyor.com/api/buildjobs/0v8bo42f02pytgrr/artifacts/src%2Fbin%2FRelease%2FWinDynamicDesktop.exe> and test if the problem still exists? You may need to delete the config file (settings.conf) if it still contains dates in the wrong format, but after doing that once the problem should hopefully go away.

―

**Comment by galaxygh** [comment]
@t1m0thyj 
Ok. I tried this version and the datetime problem doesn’t appear anymore. And it works well  when I restart it or reboot the system, which won't before. Thanks.

**Comment by t1m0thyj** [comment]
This should be fixed in version 4.1.0 which was just released. The update may take 24 hours to show up on Microsoft Store.
