### ISSUE TITLE
[Feature Request] Make Chocolatey package

### ISSUE THREAD

**Issue by username123231** [t1m0thyj/WinDynamicDesktop#188]
Thanks for the app!

It'd be cool if it was installable as a package via https://chocolatey.org/packages. Similar to the app store install, except that all the features are enabled (IIRC some weren't in app store install versus .exe).

Here's an app that uses Chocolatey https://github.com/microsoft/PowerToys#chocolatey-unofficial.

**Comment by t1m0thyj** [comment]
Created and submitted a Chocolatey package, should be available once approved.

**Comment by username123231** [comment]
Awesome
