### ISSUE TITLE
Sunrise/sunset times may be in wrong time zone

### ISSUE THREAD

**Issue by t1m0thyj** [t1m0thyj/WinDynamicDesktop#19]
If a user of the app travels around the world, the sunrise/sunset times for their home location will be in whatever time zone their computer is set to. This causes negative time spans if there is too large a difference between the time zones.

**Comment by Biswa96** [comment]
How about using system time not the LocationIQ time?

**Comment by t1m0thyj** [comment]
This should be fixed in 6cc68cf. Since the app no longer calls out to the Internet to get sunrise and sunset times, it is no longer impractical to update these values every time before the wallpaper is changed. This means that the code does not rely on any past times, so if the user's timezone changes that should no longer be a problem.
