### ISSUE TITLE
Auto brightness adjusts the brightness a little dark

### ISSUE THREAD

**Issue by Binning42** [t1m0thyj/WinDynamicDesktop#190]
Clearly, when background is very dark, screen is hard to see.

**Comment by t1m0thyj** [comment]
There isn't a one-size-fits-all approach to screen brightness. 20% may look fine on one screen but be too dark on another. You can use the custom brightness setting to pick values that look good for your device.

FYI, the auto brightness feature has been moved to a script in version 4.0: https://windd.info/scripts/#ChangeDisplayBrightness
