### ISSUE TITLE
Chinese & Chinese Simplified new translations are not good

### ISSUE THREAD

**Issue by zhangyuesai** [t1m0thyj/WinDynamicDesktop#191]
I have been providing ZH-HANS translation since version 3.1.0. I put a lot of thought into it for a precise and accurate translation. However, when I tried adding new translations for new terms in 4.0.0, I found that a "Tony blue" was added as a translator for ZH-CN and ZH-HANS. He used a lot of machine translations which make no sense to Chinese users. What's worse, the machine translations overrode my human translations. Please do not adopt Tony's translations.

**NB.** Curiously, there are two language codes for Chinese (Simplified):
* ZH-HANS for "Chinese (Simplified)"
* ZH-CN for "Chinese"

The one I have been working on is ZH-HANS.

**Comment by t1m0thyj** [comment]
Thanks for your attention to the quality of the Chinese translation. Revoked PoEditor access from "Tony Blue" for now and sent an email regarding the situation.

I haven't compared the two translations zh-Hans and zh-CN, do you think one of them should be removed?

**Comment by t1m0thyj** [comment]
Restored PoEditor access to "Tony Blue" after understanding the situation. Initially, they used the Automatic Translation feature of PoEditor, but on Feb 27 they corrected the machine translations to improve them.
