### ISSUE TITLE
DynamicWallpaper Theme Creator!

### ISSUE THREAD

**Issue by Blackrucat** [t1m0thyj/WinDynamicDesktop#193]
l,m new here so i don't know if l,m doing right.

But i have a idea, create a "DDW THEME CREATOR" will be even more easy to make themes
and the comunity will grow up.
(english? not my native language)

**Comment by t1m0thyj** [comment]
It would be cool to have a Dynamic Wallpaper Creator app. I don't have time to build such an app myself, but if anyone is interested in developing one I'd be glad to help where possible 😄 

Some features I would like to see in such an app:
* Assistant to create DDW from a set of images
* Convert HEIC file to DDW (#151)
* Convert single image to DDW (#171)

**Comment by gdstewart** [comment]
This feels like a fun project, I'm gonna give it a try

**Comment by gdstewart** [comment]
Theme creator: https://ddw-theme-creator.vercel.app/
Repo: https://github.com/gdstewart/ddw-theme-creator

I haven't gotten around to figuring out the .heic to .ddw file conversion yet. If anyone wants to contribute feel free! The functionality is pretty minimal at the moment. Some quality of life features could include draggable functionality for the images so that they can be re-ordered after they are uploaded.

**Comment by t1m0thyj** [comment]
@gdstewart Looks awesome 👍 I can link to your site in the readme file if you'd like.

To extract images out of an HEIC file in JavaScript, this project may be of interest: https://github.com/t1m0thyj/heic-extractor
It converts frames of an HEIC image to individual JPEG or PNG images, and also extracts solar metadata.

I haven't yet found a reliable way to map the solar metadata directly to image lists for sunrise/day/sunrise/night. (I've attempted it [here](https://github.com/t1m0thyj/WinDynamicDesktop/blob/feature-heic/src/HeicMetadata.cs) but been unsuccessful so far. HEIC files from different sources seem to have wildly inconsistent formats of metadata.)

Perhaps for the initial implementation, thumbnails extracted from the HEIC could be shown to the user, for them to drag into sunrise/day/sunrise/night categories.

**Comment by gdstewart** [comment]
Yeah go for it with the readme! The drag option seems like a decent compromise, I'll look into it.

**Comment by leostudiooo** [comment]
I'm working on a windows-based _(theoretically usable on Linux, macOS or any operating systems with **Python**)_ CLI program for ddw files.

**Comment by Cyberdroid1** [comment]
Is DDW format necessary? I have made some custom Themes for WDD myself. I chose the pics, created the theme.json and packed it up into a ZIP. So, I think we create a GUI in which you put the name, then dropdown option to choose image for Sunrise, Day, Sunset, Night. We choose as many images required, selected in order. This would compile the theme.json file, and pack up the images and theme.json file into a zip.

**Comment by leostudiooo** [comment]
> Is DDW format necessary? I have made some custom Themes for WDD myself. I chose the pics, created the theme.json and packed it up into a ZIP. So, I think we create a GUI in which you put the name, then dropdown option to choose image for Sunrise, Day, Sunset, Night. We choose as many images required, selected in order. This would compile the theme.json file, and pack up the images and theme.json file into a zip.

Actually, *.zip is also supported.

Guess what? The DDW file is just a zip file. You can just try to change its extend name into zip and unzip it.

**Comment by Cyberdroid1** [comment]
Oh, I didn't know that. Thanks for telling!

**Comment by Blackrucat** [comment]
Thank you, nice job!
I was waiting for a long time.

**Comment by GreenAndBlueGaming** [comment]
I created a simple electron-based desktop standalone app

Here is the repo: https://github.com/GreenAndBlueGaming/wdd-desktop-theme-creator

**Comment by TheAlienDrew** [comment]
My suggestion is the ability to convert WDD to HEIC.

**Comment by t1m0thyj** [comment]
> Theme creator: https://ddw-theme-creator.vercel.app/
> Repo: https://github.com/gdstewart/ddw-theme-creator

Thanks to @gdstewart for creating this awesome tool 🙂

**Comment by Blackrucat** [comment]
If you guys created some DynamicWallpaper Theme, put it on Deviantart, And use tags like WDD, and then people will notice the project more and more.

**Comment by GreenAndBlueGaming** [comment]
> 
> 
> If you guys created some DynamicWallpaper Theme, put it on Deviantart, And use tags like WDD, and then people will notice the project more and more.

https://windd.info/themes/
