### ISSUE TITLE
[Feature Request] Add dynamic lock screen support?

### ISSUE THREAD

**Issue by MacularDegenerate** [t1m0thyj/WinDynamicDesktop#200]
First of all, love this program! Would you ever consider adding dynamic lock screen support though? It would be great if I could set the lock screen wallpaper to match my desktop. Thanks! Keep up the great work!

**Comment by t1m0thyj** [comment]
Changing lock screen wallpaper is an experimental feature. You can download a script for it [here](https://windd.info/scripts/), but it doesn't work well currently (see https://github.com/t1m0thyj/WDD-scripts/issues/1).

**Comment by MacularDegenerate** [comment]
Thanks for the heads up. Glad to hear this is in progress. Great work!

Andrew Polk
________________________________
