### ISSUE TITLE
High Useage of CPU when enable powershell scripts

### ISSUE THREAD

**Issue by greenhand520** [t1m0thyj/WinDynamicDesktop#201]
High Useage of CPU when enable powershell scripts,
like these two image show.
![image](https://user-images.githubusercontent.com/32732204/79458355-43a0a180-8024-11ea-932c-65027e5b9aa3.png)
![image](https://user-images.githubusercontent.com/32732204/79458505-7a76b780-8024-11ea-9182-4cc535511548.png)

**Comment by PorridgePi** [comment]
Same problem here, WinDynamicDesktop constantly uses at least 20% of the CPU, while sometimes peaking to 35% or above. I have also enabled PowerShell scripts.
P.S. 你的拼写拼错了。Usage 是这样拼的，不是 Useage。

**Comment by PorridgePi** [comment]
![image](https://user-images.githubusercontent.com/34623167/83516327-6e2db780-a509-11ea-9b30-f0057c0dc1c6.png)

**Comment by t1m0thyj** [comment]
The way that PowerShell scripts run has changed in WDD v5 so this issue should be fixed.
