### ISSUE TITLE
Feature request : please add a feature to change both lockscreen wallpaper  and desktop wallpaper as well instead of script

### ISSUE THREAD

**Issue by pratham280** [t1m0thyj/WinDynamicDesktop#203]
Submit your bug report or feature request here. If you have questions please ask them on [Gitter](https://gitter.im/t1m0thyj/WinDynamicDesktop) instead.

When reporting a bug please provide:
 - Steps to reproduce it
 - Screenshots (if applicable)
 - Log file (if it exists, see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) for how to find it)
 - Windows version (e.g. 7, 10)
 - WinDynamicDesktop version (e.g. 2.0.0)
 - Installation source (e.g. installer, Microsoft Store, portable EXE)

**Comment by t1m0thyj** [comment]
The feature to change the lockscreen image is currently too unreliable. Until [this issue](https://github.com/t1m0thyj/WDD-scripts/issues/1) is fixed, I don't plan to include it directly in the app.
