### ISSUE TITLE
Cannot Load Large-Sized Wallpaper Files

### ISSUE THREAD

**Issue by leostudiooo** [t1m0thyj/WinDynamicDesktop#204]
- Windows version = 10
- Software version = Windows Store
- Files attached(zip):
[island_bn.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/4640291/island_bn.zip)
[island.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/4640297/island.zip)
  - island.ddw(usable)
  - island_bn.ddw(unusable)

**Comment by t1m0thyj** [comment]
The problem with the unusable DDW is the image filenames. They have padded `0`'s in front (e.g., `island_000.jpg`) which are unexpected by WDD. In the DDW which is usable, the filenames don't have padded `0`'s (e.g., `island_1.jpg`).
