### ISSUE TITLE
Error on Windows 10 startup

### ISSUE THREAD

**Issue by elenmerbau** [t1m0thyj/WinDynamicDesktop#206]
Started to happen after the Windows 10 May update. Windows version is 10.0.19041.

![image](https://user-images.githubusercontent.com/23418072/82444437-de97fb80-9a68-11ea-95c2-df10a69cc7dc.png)

**Comment by Cyberdroid1** [comment]
There may be 2 entries of WDD in Startup tab of Task Manager. Try checking that. If there is, disable one of them and restart your PC.

**Comment by t1m0thyj** [comment]
Is anyone still experiencing this issue with the latest version of WDD (4.4.0)?

**Comment by Cyberdroid1** [comment]
I don't think this issue depends on the app version, but rather on the user config. 
Those who face this issue, try checking the startup tab in task manager or taskschedule page.

**Comment by t1m0thyj** [comment]
> There may be 2 entries of WDD in Startup tab of Task Manager. Try checking that. If there is, disable one of them and restart your PC.

Agreed this seems to likely be a user config issue. If the above suggestion from @Cyberdroid1 does not work, feel free to reopen this issue.
