### ISSUE TITLE
problem loading custom themes

### ISSUE THREAD

**Issue by juicypop** [t1m0thyj/WinDynamicDesktop#208]
When loading a custom theme WinDynamicDesktop freezes with the message "Generating thumbnails, please wait..."
I made sure to name my jpegs properly and the json is valid.

Steps to reproduce it:
- try to import my zipped theme
[village.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/4658022/village.zip)

Screenshots:
![2020-05-20](https://user-images.githubusercontent.com/25671698/82469079-dae59280-9ac3-11ea-8e2f-5f4ee918c782.png)

Log file:
I have no WinDynamicDesktop.exe.log in my Appfolders

Windows version: 10 Pro

WinDynamicDesktop version: 4.1.0 (UWP)

Installation source: Microsoft Store

**Comment by carpac** [comment]
The json may be valid, but it contains an error:

Change
`"imageFilename": "village_*.jepg",`
to
`"imageFilename": "village_*.jpeg",`
and it works.

**Comment by juicypop** [comment]
OMG never work on code snippets in the middle of the night :rofl:
I'm sure this'll fix my problem, thanks for your finding

**Comment by juicypop** [comment]
I can confirm that this fixed the issue, thanks again @carpac  👍
