### ISSUE TITLE
Request: update Catalina wallpapers to newest 6016×6016 versions

### ISSUE THREAD

**Issue by Pivilio** [t1m0thyj/WinDynamicDesktop#211]
Hi this is more of an image update request: the included Catalina wallpapers aren't the fullest resolution versions available, which I found at:

https://www.reddit.com/r/MacOS/comments/d2qb1g/download_macos_catalina_19a558d_stock_wallpapers/

(https://drive.google.com/drive/folders/1S0EhuYPXK63pHk8MQ_Ac8H3NrMSsei4u if the above post gets deleted)

These are also **square** which means better support for portrait and other non-16:9 (16:10, 3:2, 4:3) monitors.

**Comment by t1m0thyj** [comment]
There is now a square Catalina DDW available here: https://github.com/t1m0thyj/WDD-mac-themes/releases/tag/catalina

Also uploaded square wallpapers for Mojave and Big Sur.

The default wallpapers bundled with the app will remain 16x9, since that is the most common display ratio.
