### ISSUE TITLE
[Feature Request] Slider for the showoffs

### ISSUE THREAD

**Issue by MatiasLGonzalez** [t1m0thyj/WinDynamicDesktop#212]
It would be cool to have a slider to change the current image between day and night to a specific one with the transition (mostly to showoff), and also have a button like "Reset to current time" to go back to the current wallpaper.

![SliderControl](https://user-images.githubusercontent.com/48534497/84287383-d84beb00-ab0d-11ea-8c5f-e633616541cf.jpg)
(Sorry for the pixel art)

Also it would be cool to see in the "Choose theme" preview the transition effect (not just a static image swap).

**Comment by t1m0thyj** [comment]
Check out v4.3.0 (currently only available on GitHub, update is pending approval on Microsoft Store). It was just released and improves the appearance of the theme preview.

**Comment by MatiasLGonzalez** [comment]
Exactly what I was thinking, thanks! : )
