### ISSUE TITLE
Choosing a theme not possible

### ISSUE THREAD

**Issue by LeQuadratico** [t1m0thyj/WinDynamicDesktop#214]
Submit your bug report or feature request here. If you have questions please ask them on [Gitter](https://gitter.im/t1m0thyj/WinDynamicDesktop) instead.

When reporting a bug please provide:
 - Steps to reproduce it
Download the last release (4.1.1) and start it, select a location and press OK (Theme chooser should be shown now) OR try to change the theme.

 - Screenshots (if applicable)
![Anmerkung 2020-06-21 220712](https://user-images.githubusercontent.com/45048954/85234137-9f641e00-b40b-11ea-80bf-fe606cd534d5.jpg)

 - Log file (if it exists, see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) for how to find it)

> [2020-06-21 19:59:13.214] System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\WINDOWS\Web\Wallpaper\Windows" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileSystemEnumerableIterator`1.CommonInit()
   bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   bei System.IO.Directory.GetFiles(String path)
   bei WinDynamicDesktop.ThemeDialog..ctor()
   bei WinDynamicDesktop.ThemeManager.SelectTheme()
   bei WinDynamicDesktop.LaunchSequence.NextStep(Boolean themeReadyOverride)
   bei WinDynamicDesktop.LocationManager.OnLocationDialogClosed(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   bei System.Windows.Forms.Form.WmClose(Message& m)
   bei System.Windows.Forms.Form.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

 - Windows version (e.g. 7, 10)
Windows 10 (1909, 18363.900)

 - WinDynamicDesktop version (e.g. 2.0.0)
4.1.1

 - Installation source (e.g. installer, Microsoft Store, portable EXE)
Installer from GitHub, same Errorlog on WinStore-Version

**Comment by LeQuadratico** [comment]
Btw, when I create the folder "Windows" in "C:\Windows\Web\Wallpaper\", I get another error:

> [2020-06-23 10:10:58.748] System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei WinDynamicDesktop.ThemeDialog..ctor()
   bei WinDynamicDesktop.ThemeManager.SelectTheme()
   bei WinDynamicDesktop.MainMenu.OnThemeItemClick(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by LeQuadratico** [comment]
Workaround:
-Create the folder which does not exist (For me it was the "Windows" Folder in "C:\WINDOWS\Web\Wallpaper\Windows").
-Just copy ANY image into that folder.
After that, it worked for me.

**Comment by t1m0thyj** [comment]
The default wallpaper in a fresh Windows 10 installation is located at `%SystemRoot%\Web\Wallpaper\Windows\img0.jpg`. If this file is missing on your system, the Windows folder of your Windows 10 install is corrupted/missing some files.

**Comment by LeQuadratico** [comment]
Okay, strange. Then I can close this issue?

**Comment by t1m0thyj** [comment]
@LeQuadratico Going ahead and closing this. Added workaround to use solid black background if Windows 10 wallpaper is missing, which should fix this error in the next release.
