### ISSUE TITLE
Big Sur wallpaper

### ISSUE THREAD

**Issue by koubafire** [t1m0thyj/WinDynamicDesktop#215]
Can you add new Big Sur wallpaper?

**Comment by elizkovalenko** [comment]
Hi, I have dynamic Big Sur on my google drive. You can download it here: https://drive.google.com/file/d/1ZtobJnqn3HS2I3bYXFJGpq2jtr99-KeZ/view?usp=sharing
Enjoy :)

**Comment by koubafire** [comment]
Its not working - says no pictures was found

**Comment by koubafire** [comment]
Thanks - its working only if i choose json not zip :-)

**Comment by drfuze** [comment]
Hi, check out the new abstract version of macos wallpaper. You can download from the link below.
[https://drive.google.com/file/d/1_i8azXvkyYKzntFB_ybTPlsTC3Q9G3fG/view?usp=sharing](url)
Cheers!

**Comment by t1m0thyj** [comment]
DDWs here: https://drive.google.com/drive/folders/1-b6gTTZpY7g7in1YnfHtnamr51ExKaBO?usp=sharing

**Comment by njr01** [comment]
> Olá, tenho Big Sur dinâmico no meu Google Drive. Você pode baixá-lo aqui: https://drive.google.com/file/d/1ZtobJnqn3HS2I3bYXFJGpq2jtr99-KeZ/view?usp=sharing
> Aproveite :)

Tank you so much!!!!!!!!!!!!!!

**Comment by t1m0thyj** [comment]
Big Sur themes have been added in v4.2.0. New release is available on GitHub, awaiting approval to show up on Microsoft Store.

**Comment by njr01** [comment]
Tank you so much!!!

Enviado do meu iPhone

**Comment by satreddyg** [comment]
v4.2.0 is giving errors when select dark mode and wallpapers not changing all errors i gone back to 4.1.1 much stable and windows defender detect as a virus too am on win10 1909version

**Comment by t1m0thyj** [comment]
> v4.2.0 is giving errors when select dark mode and wallpapers not changing all errors i gone back to 4.1.1 much stable and windows defender detect as a virus too am on win10 1909version

@satreddyg I'm not able to reproduce these issues in 4.2.0. If you continue to experience them, please create a new issue with screenshots.

Regarding Windows Defender, it's normal for it to detect a new release as a virus when it is very fresh and not many people have downloaded it yet. This should fix itself over time.
