### ISSUE TITLE
Black wallpaper on Big Sur theme with certain time zones

### ISSUE THREAD

**Issue by gabrielfsd** [t1m0thyj/WinDynamicDesktop#216]
Hi everyone. First thank you developer for making the app, it's great.

I'm having a problem with latest version 4.2.0 when applying the Big Sur theme. The wallpaper goes dark when I select my city, or even the capital city nearby.

I live in Brazil and my city is "Pedro Leopoldo", when I select Big Sur theme the wallpaper goes black. It only happen on Big Sur theme (Mojave, Catalina and the other two colorful ones work fine). I even tried to select the capital city "Belo Horizonte" only 25 miles away but also it doesn't work. I tried then selecting New York, London, etc and it worked just fine.

I'm using Windows 10 2004 build 19041.331 and the desktop version of the app, not the Windows Store one. Already tried to update from preview version (same result) and completely uninstalling and then installing the new version (same result too).

Any idea why only Big Sur doesn't work on my city time? Thanks.

**Comment by t1m0thyj** [comment]
> when I select Big Sur theme the wallpaper goes black

Do you mean the desktop background goes totally black? Is the correct image for Big Sur shown in the Preview panel of the "Select Theme" dialog?

I tried changing my city in the app to "Belo Horizonte", and my time to around 11AM, but wasn't able to reproduce the issue.

If the issue continues, could you send a log file? ([See here for how to obtain it](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#obtaining-detailed-logs))

**Comment by gabrielfsd** [comment]
Yes, the desktop background goes totally black. The Big Sur preview image is correct on the app itself.

I noticed that the correct Big Sur image appears on desktop around 3PM, so it's a time related bug, maybe? Then the correct image stays until the night, changing as they're supposed to.

I think that manually changing the time doesn't reproduce the issue. I will observe if tomorrow morning my wallpaper will be black and I update this issue page with that info.

**Comment by gabrielfsd** [comment]
When I turned on the computer this morning the Big Sur wallpaper worked fine until 10:20AM when the desktop wallpaper became black. Same time as my laptop, the wallpaper became black too. It was also with Big Sur theme applied.

Around 3PM the wallpaper should be back to the normal images as I noticed yesterday. In theory, if you set your location on app to "Belo Horizonte" and applied Big Sur theme (in that order) before 3PM on my local time you should be able to notice it too.

I recorded a video showing that only Big Sur doesn't work. Around 50 seconds on the video, Catalina also doesn't work when applied after Big Sur, but that only happens some times.
[](https://drive.google.com/file/d/1zXxGnMd_9YYk13PIVoEeEIAdcVkdc8eG/view?usp=sharing)

**Comment by schaafjs** [comment]
I have exactly the same issue and believe that it has something to do with the third/fourth image in the series. If I manually apply the third/fourth one (not from within WinDynamicDesktop), exactly the same black wallpaper occurs. All preceeding and following images do not seem to cause any problems whatsoever.
I'm on Windows 10 2004 and can also share my log if that helps.

**Comment by gabrielfsd** [comment]
I can confirm now that the issue is only with the fourth image. The desktop goes dark even if I go to the picture itself (...WinDynamicDesktop\themes\Big_Sur\Big_Sur_5.jpg) right click on it and select "Set as desktop wallpaper". So is a Windows related bug? Somehow it is not able to set this image as a wallpaper.

**Comment by mrtajniak** [comment]
I have the same issue, only with Big_Sur_5
I am using Windows 20H2

**Comment by t1m0thyj** [comment]
> I can confirm now that the issue is only with the fourth image. The desktop goes dark even if I go to the picture itself (...WinDynamicDesktop\themes\Big_Sur\Big_Sur_5.jpg) right click on it and select "Set as desktop wallpaper". So is a Windows related bug? Somehow it is not able to set this image as a wallpaper.

Thanks for the info, agree it seems to point to this being a problem with Windows rather than with WDD.

Seems like everyone experiencing the issue has the May update (Windows 10 2004). I can't reproduce the issue, likely because I'm still on Win10 1909. I can't update yet because the May update is currently blocked for my device due to driver issues.

Will update this issue once I get my hands on Win10 2004. In the meantime, if there is sufficient reason to think this is a Windows bug, feel free to report it in Windows 10 Feedback app.

**Comment by zhangyuesai** [comment]
I am on 1909 and I have the same issue.

**Comment by Hanscito** [comment]
Same "11:00 am" issue for me with Windows 10 Version 1909 (18363.900)

**Comment by Coding-Bob** [comment]
More info:
Same problem on windows 1909. And after the black background appears, the WDD program seems not working. Changing into Catalina theme by WDD is not responded. 
I have to first choose another wallpaper by default method in settings and restart the PC and WDD.

**Comment by DjCrqss** [comment]
Same Issue for me at 11:00AM. I assumed that somehow I have turned off wallpaper compression with an option but I looked through WinDynamic and can't find a toggle to turn it on so I might've been mistaken.
If you go into the personalise on windows settings you can see the 'picture' has been replaced with 'solid color' for background and the app is laggy so I had an idea that it possibly is that the image is too high resolution to handle with compression off and causes the background to crash.

**Comment by Hanscito** [comment]
I have compressed the image Big_Sur_5.jpg but this doesn't help. Issue remains.

**Comment by Hanscito** [comment]
New approach:
I did download Big-Sur_5.jpg from another source (6016x6016) with 72dpi and resized it to 6016x3384 (5 MB)
and this version works now. Original version which comes with WDD has 96dpi and 19MB.

**Comment by Hanscito** [comment]
Image source:  https://www.idownloadblog.com/2020/06/22/macos-big-sur-wallpapers/

**Comment by dragoncode** [comment]
I have the same problem, using Windows location or setting it manually to London at around 12:45 pm results in a black background. If set to LA manually the correct image is shown. 

I have had similar problems before, and suspect it might have to do with the file size limit for background images in Windows? I remember it was 25mb for a png or something. 

Was not able to find a good solution back then. 

I'm also on 1909.

**Comment by Coding-Bob** [comment]
Problem solved by compressing the specific image. Without using the image with another dpi like @Hanscito , I directly compressed the image to 14MB and it worked.

(Windows 10 version 1909)

**Comment by dragoncode** [comment]
> Problem solved by compressing the specific image. Without using the image with another dpi like @Hanscito , I directly compressed the image to 14MB and it worked.
> 
> (Windows 10 version 1909)

Dumb question but how exactly did you compress the specific image? I only have the ddw file and do not know how to edit it / extract the images.

**Comment by Dolyfin** [comment]
I use 7zip > Open archive option when right clicking the .dww file.

**Comment by chemharuka** [comment]
Recompress the Big_Sur_5.jpg file with 95% quality should work.

**Comment by gabrielfsd** [comment]
It appears that Microsoft corrected this problem in build 2004 19041.508. I opened a bug report for them two months ago. The wallpaper is no longer black for me.

**Comment by username123231** [comment]
@gabrielfsd Not fixed for me with that build unfortunately.

**Comment by gabrielfsd** [comment]
@username123231 Microsoft updated my bug report as "aware". Maybe they're doing some A/B testing with the fix, I'm not sure.

**Comment by t1m0thyj** [comment]
This seems to have been a Microsoft bug that was fixed, feel free to reopen if you still have the issue

**Comment by yazan1107** [comment]
still have the same issue!!

**Comment by yazan1107** [comment]
> Recompress the Big_Sur_5.jpg file with 95% quality should work. (convert -strip -interlace Plane -sampling-factor 4:4:4 -quality 95% Big_Sur_5-Copy.jpg Big_Sur_5.jpg)

i tried to type the same command line in windows terminal, it did not work!!
i get Invalid Parameter - -interlace

**Comment by t1m0thyj** [comment]
> > Recompress the Big_Sur_5.jpg file with 95% quality should work. (convert -strip -interlace Plane -sampling-factor 4:4:4 -quality 95% Big_Sur_5-Copy.jpg Big_Sur_5.jpg)
> 
> i tried to type the same command line in windows terminal, it did not work!! i get Invalid Parameter - -interlace

Are you using the ImageMagick `convert` tool? It has an "interlace" option documented:

**Comment by yazan1107** [comment]
Oh thanks i didn’t have it
