### ISSUE TITLE
Not avaliable new update to 4.1.2 from Microsoft Store.

### ISSUE THREAD

**Issue by livevasiliy** [t1m0thyj/WinDynamicDesktop#217]
Submit your bug report or feature request here. If you have questions please ask them on [Gitter](https://gitter.im/t1m0thyj/WinDynamicDesktop) instead.

When reporting a bug please provide:
 - Steps to reproduce it
 - Screenshots (if applicable)
 - Log file (if it exists, see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) for how to find it)
 - Windows version (e.g. 7, 10)
 - WinDynamicDesktop version (e.g. 2.0.0)
 - Installation source (e.g. installer, Microsoft Store, portable EXE)

**Comment by t1m0thyj** [comment]
I don't have control over this. I published v4.2.0 to Microsoft Store at the same time as the GitHub release. The release must be approved by Microsoft before it appears on the Store, which is taking longer than normal this time.

Can leave this issue open until the update gets approved.

**Comment by t1m0thyj** [comment]
v4.2.0 is now published on the Microsoft Store
