### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by rtao258** [t1m0thyj/WinDynamicDesktop#218]
Thanks for the great app - I think it's the only one of it's kind to provide this functionality for Windows. 
Unfortunately, the program is crashing on launch.

**Steps to reproduce it**

Sorry, not sure. I'd just added two new themes from a third-party source. However, I suspect the issue is with a larger theme I created myself earlier in the day. It is quite large (2000+ images). Admittedly, this is probably an unfair stress test of the program, but I don't know why it wouldn't work.

**Screenshots**

Not applicable. When I try opening the app, I get an error dialog telling me to see the log file for details.

**Log file**
>[2020-06-29 04:24:12.202] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WinDynamicDesktop.WallpaperChangeScheduler.GetImageData(SolarData data, ThemeConfig theme)
   at WinDynamicDesktop.WallpaperChangeScheduler.RunScheduler(Boolean forceImageUpdate)
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

This message is repeated every time I attempt to launch the program.

**Versions**
- Windows: 10
- WDD: 4.2.0

**Installation source**

installer (non-portable)

**Comment by t1m0thyj** [comment]
> I suspect the issue is with a larger theme I created myself earlier in the day. It is quite large (2000+ images). Admittedly, this is probably an unfair stress test of the program, but I don't know why it wouldn't work.

Haven't tested with this many images but agree it should work. Please attach the `theme.json` file you created, and I'll see if I can reproduce the problem with it.

**Comment by rtao258** [comment]
So it looks like there was a problem with the `theme.json`, specifically that there was a trailing comma after the last list I made. I think the program is working correctly now, so I'll close the issue. If it turns out that that was not the problem, I can re-open. Lesson learned to use a JSON validator before trying to run the theme. Sorry for taking up your time.
