### ISSUE TITLE
New Version Crashed on Start

### ISSUE THREAD

**Issue by sudarakas** [t1m0thyj/WinDynamicDesktop#221]
used version : WinDynamicDesktop 4.2.0 (Windows 10 May)

error
(https://github.com/t1m0thyj/WinDynamicDesktop/files/4873961/WinDynamicDesktop.exe.log)
![Screenshot_61](https://user-images.githubusercontent.com/40355098/86521371-86c52080-be6d-11ea-92d9-aa3314866f44.png)

logfile
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/4873964/WinDynamicDesktop.exe.log)

**Comment by t1m0thyj** [comment]
Which theme, if any, did you most recently select in the app?

Please obtain a detailed log file (instructions [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#obtaining-detailed-logs)) and attach it to aid in diagnosing the issue.

**Comment by sudarakas** [comment]
I have already added the log file, the problem was solved after uninstalling and reinstalling the application 🙄🙌
