### ISSUE TITLE
ARM version running in x86 mode.

### ISSUE THREAD

**Issue by matze19999** [t1m0thyj/WinDynamicDesktop#225]
I've downloaded WinDynamicDesktop through Microsoft Store, but task manager shows that its running in x86 mode instead of arm/arm64. I've attached a screenshot.

![image_2020-07-13_11-12-04](https://user-images.githubusercontent.com/13684520/87287290-351a3700-c4fa-11ea-85bd-d8caad0309f1.png)

My device is a Microsoft Surface Pro X.

Windows 10 build is 20161.
WinDynamicDesktop version is 4.2.0 (UWP)

**Comment by t1m0thyj** [comment]
.NET Framework 4 doesn't yet support ARM architecture for Windows Forms apps. .NET 5.0 Preview 6 is the first version to do so. When .NET 5 releases in November, I plan to update WDD to use it which should then achieve ARM support.

**Comment by t1m0thyj** [comment]
.NET 5 was released this week, but without native ARM support for GUI apps which has been delayed.

**Comment by FalenDemon** [comment]
> .NET 5 was released this week, but without native ARM support for GUI apps which has been delayed.

Hi there! Are there any news about native capability with ARM64? Asking for all Microsoft Surface Pro X community :D

**Comment by t1m0thyj** [comment]
WDD v5 now has separate downloads available for ARM64. I don't have an ARM64 device to test this on, so please let me know if you encounter any issues.
