### ISSUE TITLE
Can't run on Win!)

### ISSUE THREAD

**Issue by NA-Siddiky** [t1m0thyj/WinDynamicDesktop#227]
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/4940393/WinDynamicDesktop.exe.log)

Submit your bug report or feature request here. If you have questions please ask them on [Gitter](https://gitter.im/t1m0thyj/WinDynamicDesktop) instead.

When reporting a bug please provide:
 - Steps to reproduce it
 - Screenshots (if applicable)
 - Log file (if it exists, see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) for how to find it)
 - Windows version (e.g. 7, 10)
 - WinDynamicDesktop version (e.g. 2.0.0)
 - Installation source (e.g. installer, Microsoft Store, portable EXE)

**Comment by t1m0thyj** [comment]
Which theme, if any, did you most recently select in the app?

Please obtain a detailed log file (instructions [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#obtaining-detailed-logs)) and attach it to aid in diagnosing the issue.

**Comment by steven2004le** [comment]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WinDynamicDesktop.WallpaperChangeScheduler.GetImageData(SolarData data, ThemeConfig theme)
   at WinDynamicDesktop.WallpaperChangeScheduler.RunScheduler(Boolean forceImageUpdate)
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

When I ran my computer this morning and yesterday morning it says that something went wrong and I couldn't run it. It told me to go check my logs and these are the logs it keeps giving me up above. Please help me out and thank you so much.

**Comment by t1m0thyj** [comment]
Is this error still happening in the latest version of WDD (4.4.0)?

**Comment by t1m0thyj** [comment]
@NA-Siddiky @steven2004le Could you please try this build of WDD and let me know if it fixes your issue? The out of range exception should hopefully be fixed now: https://ci.appveyor.com/project/t1m0thyj/windynamicdesktop/builds/37066592/artifacts
