### ISSUE TITLE
System.IndexOutOfRangeException: 索引超出了数组界限。

### ISSUE THREAD

**Issue by xiaoe-tech** [t1m0thyj/WinDynamicDesktop#228]
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 WinDynamicDesktop.ThemeDialog..ctor()
   在 WinDynamicDesktop.ThemeManager.SelectTheme()
   在 WinDynamicDesktop.LaunchSequence.NextStep(Boolean themeReadyOverride)
   在 WinDynamicDesktop.LocationManager.OnLocationDialogClosed(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   在 System.Windows.Forms.Form.WmClose(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by reporter-law** [comment]
I have the same error
[2020-08-12 01:34:40.005] System.IndexOutOfRangeException: 索引超出了数组界限。
   在 WinDynamicDesktop.ThemeDialog..ctor()
   在 WinDynamicDesktop.ThemeManager.SelectTheme()
   在 WinDynamicDesktop.LaunchSequence.NextStep(Boolean themeReadyOverride)
   在 WinDynamicDesktop.LocationManager.OnLocationDialogClosed(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   在 System.Windows.Forms.Form.WmClose(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by YapuWang** [comment]
[2020-09-09 11:27:04.112] System.IndexOutOfRangeException: 索引超出了数组界限。
   在 WinDynamicDesktop.ThemeDialog..ctor()
   在 WinDynamicDesktop.ThemeManager.SelectTheme()
   在 WinDynamicDesktop.MainMenu.OnThemeItemClick(Object sender, EventArgs e)
   在 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   在 System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   在 System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   在 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.ToolStrip.WndProc(Message& m)
   在 System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by GitLuckyDog** [comment]
[2020-09-11 08:39:29.956] System.IndexOutOfRangeException: 索引超出了数组界限。
   在 WinDynamicDesktop.ThemeDialog..ctor()
   在 WinDynamicDesktop.ThemeManager.SelectTheme()
   在 WinDynamicDesktop.LaunchSequence.NextStep(Boolean themeReadyOverride)
   在 WinDynamicDesktop.LocationManager.OnLocationDialogClosed(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   在 System.Windows.Forms.Form.WmClose(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[2020-09-11 08:39:35.058] System.IndexOutOfRangeException: 索引超出了数组界限。
   在 WinDynamicDesktop.ThemeDialog..ctor()
   在 WinDynamicDesktop.ThemeManager.SelectTheme()
   在 WinDynamicDesktop.LaunchSequence.NextStep(Boolean themeReadyOverride)
   在 WinDynamicDesktop.LocationManager.OnLocationDialogClosed(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   在 System.Windows.Forms.Form.WmClose(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[2020-09-11 08:39:36.668] System.IndexOutOfRangeException: 索引超出了数组界限。
   在 WinDynamicDesktop.ThemeDialog..ctor()
   在 WinDynamicDesktop.ThemeManager.SelectTheme()
   在 WinDynamicDesktop.LaunchSequence.NextStep(Boolean themeReadyOverride)
   在 WinDynamicDesktop.LocationManager.OnLocationDialogClosed(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   在 System.Windows.Forms.Form.WmClose(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[2020-09-11 08:46:36.937] System.IndexOutOfRangeException: 索引超出了数组界限。
   在 WinDynamicDesktop.ThemeDialog..ctor()
   在 WinDynamicDesktop.ThemeManager.SelectTheme()
   在 WinDynamicDesktop.LaunchSequence.NextStep(Boolean themeReadyOverride)
   在 WinDynamicDesktop.AppContext..ctor(String[] args)
   在 WinDynamicDesktop.Program.Main(String[] args)

[2020-09-11 08:46:45.230] System.IndexOutOfRangeException: 索引超出了数组界限。
   在 WinDynamicDesktop.ThemeDialog..ctor()
   在 WinDynamicDesktop.ThemeManager.SelectTheme()
   在 WinDynamicDesktop.LaunchSequence.NextStep(Boolean themeReadyOverride)
   在 WinDynamicDesktop.AppContext..ctor(String[] args)
   在 WinDynamicDesktop.Program.Main(String[] args)

[2020-09-11 08:46:56.357] System.IndexOutOfRangeException: 索引超出了数组界限。
   在 WinDynamicDesktop.ThemeDialog..ctor()
   在 WinDynamicDesktop.ThemeManager.SelectTheme()
   在 WinDynamicDesktop.LaunchSequence.NextStep(Boolean themeReadyOverride)
   在 WinDynamicDesktop.AppContext..ctor(String[] args)
   在 WinDynamicDesktop.Program.Main(String[] args)

**Comment by GitLuckyDog** [comment]
![image](https://user-images.githubusercontent.com/22680879/93160726-87b6e000-f743-11ea-8ab4-c5940429692a.png)

**Comment by GitLuckyDog** [comment]
C:\Windows\Web\Wallpaper\Windows

**Comment by pc439527** [comment]
C:\Users\DELL\AppData\Local\Packages\38719TimothyJohnson.WinDynamicDesktop_rfarkse4rn21a\LocalState
[2020-09-25 01:53:13.484] System.IndexOutOfRangeException: 索引超出了数组界限。
   在 WinDynamicDesktop.ThemeDialog..ctor()
   在 WinDynamicDesktop.ThemeManager.SelectTheme()
   在 WinDynamicDesktop.MainMenu.OnThemeItemClick(Object sender, EventArgs e)
   在 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   在 System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   在 System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   在 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.ToolStrip.WndProc(Message& m)
   在 System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by t1m0thyj** [comment]
Is this error still happening in the latest version of WDD (4.4.0)?

**Comment by pc439527** [comment]
> 
> 
> Is this error still happening in the latest version of WDD (4.4.0)?

it was fixed，thanks
