### ISSUE TITLE
Big Sur theme.

### ISSUE THREAD

**Issue by hxsci** [t1m0thyj/WinDynamicDesktop#229]
Sorry but I can't download the Big Sur theme in the app, can you please offer a link to download it with a browser or downloader?
This app is great and thank you very much.

**Comment by t1m0thyj** [comment]
Big Sur DDW files can be downloaded here: https://github.com/t1m0thyj/WDD-mac-themes/releases/tag/big-sur

**Comment by hxsci** [comment]
Thanks.
