### ISSUE TITLE
JPEGImportQuality Is Not Really Working On Windows 1809

### ISSUE THREAD

**Issue by ariefcfa** [t1m0thyj/WinDynamicDesktop#230]
- Windows version: 1809
 - WinDynamicDesktop version: 4.2.0
 - Installation source: Portable

I found the option to disable .jpg compression is not available anymore in WinDynamicDesktop option menu, however I check in registry the key is set, JPEGImportQuality Hex=64 (Decimal=100).

But for me, my desktop wallpaper still lower quality than the original file. I tried to easy my self beforehand by just convert the wallpaper file to .png, then as my wallpaper collection grows, this way takes more and more storage spaces.

Is there something I missed, how to get the full quality wallpaper as the original file? Please help

Thanks

**Comment by ariefcfa** [comment]
This is the comparison between my Desktop wallpaper and the Original file

![Compare](https://user-images.githubusercontent.com/34770799/88300287-82ce4500-cd2d-11ea-9ac7-028bd5cff480.png)

**Comment by t1m0thyj** [comment]
If you have applied this registry tweak (credits: [Windows Central](https://www.windowscentral.com/how-disable-image-compression-desktop-wallpapers-windows-10)), then I'm not sure why JPEG images would still be getting compressed.
![image](https://user-images.githubusercontent.com/22344007/100833184-6ce93300-3437-11eb-8cd5-947ef64200d7.png)
