### ISSUE TITLE
About theme Making

### ISSUE THREAD

**Issue by x2391555062** [t1m0thyj/WinDynamicDesktop#233]
How to make the theme used in the software?
I have a heic
I am a novice
don't know how to make a theme with HEIC

**Comment by gdstewart** [comment]
Hey there, you have two options: 

1. You can either follow the instructions here that t1m0thyj put together: https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes
2. You can try out the theme creator which extracts the HEIC file images and then you can manually drag them into the proper categories: https://ddw-theme-creator.vercel.app/
