### ISSUE TITLE
Repeat #232

### ISSUE THREAD

**Issue by rushelex** [t1m0thyj/WinDynamicDesktop#234]
Repeat #232.

Hey. Despite the fact that I respect you, you are wrong.
Check out this app: https://github.com/Armin2208/Windows-Auto-Night-Mode. It has the option to start not from the Startup folder, but from the Windows Task Scheduler. If the program is launched from the Windows Task Scheduler, the program starts immediately when the computer is turned on and does not wait for other programs to start.
I tried to add the launch of the program myself as a scheduled task, but I could not find where the .exe file of the program itself is located. I am using the UWP version of the program.

P.S. My PC has an SSD and the 10 second delay before starting programs is disabled for me.

**Comment by t1m0thyj** [comment]
Closing this issue and reopening #232 to track it which has comment history.
