### ISSUE TITLE
I am working on a clone of this project

### ISSUE THREAD

**Issue by samtholiya** [t1m0thyj/WinDynamicDesktop#236]
Hi, I am working on a clone of this project with better modern  UI and more architectures and some UWP native background task. Can you please let me know before hand if you disagree? Like I should not do that... Or somethings I should keep in my project to not face a legal charge. I have also listed the reason for the project.. 
https://github.com/samtholiya/DynaDesktop

**Comment by t1m0thyj** [comment]
@samtholiya Hi, I have no objections to you working on a clone of this project, as long as you comply with the terms of the [Mozilla Public License 2.0](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)) if you are using WDD's source code.

Regarding the things you've mentioned:
* "better modern UI" - Have you checked out the latest code on "master" branch? It's still using Windows Forms so not as modern as UWP, but the theme dialog which was one of the most "ugly" parts of the UI previously has been redesigned to look more modern.
![image](https://user-images.githubusercontent.com/22344007/91841283-142fb180-ec20-11ea-85ca-79ed6ad848c0.png)

* "more architectures' - WDD can run on 32-bit, 64-bit, and ARM. Currently it always runs in 32-bit mode, but there are no technical reasons limiting WDD from running 64-bit. I haven't seen reason yet to publish a separate 64-bit version, but if you would like I can do that. Regarding ARM, I can't publish a native ARM build until .NET Framework 5 is released, but the app still runs on ARM, just less efficiently for now.
* "UWP native background task" - I'm afraid I don't know enough about UWP to comment on this.

Let me know what you think. If the things mentioned above don't affect your decision to create a clone of this project, feel free to continue work on it.

Also a question for you - After you complete the new UWP UI for DynaDesktop, would you consider contributing it back to WinDynamicDesktop? There could be a possibility in the future for us to collaborate on the same project. But I also understand if you'd rather keep the UWP app as an independent project.

**Comment by samtholiya** [comment]
I would actually love to contribute to your project. Would do so once I complete all the features if it would be possible (Don't know all the challenges involved in win32 and UWP merge yet). As I am doing this for self learning and displaying my c# knowledge, I might complete in my own pace. By the way new theme design way cooler then the one I have installed on my system.


Hope to complete all the features you already have in win32 application soon. 
Thanks for your help. 

Note: Will also copy some common logic from your code base but would not monetize the app. And will mention this original project in the app. The source of themes would be your website only.

**Comment by t1m0thyj** [comment]
Closing as the clone repo has been inactive for 90 days. If it becomes active again, contributions are welcome in the future.
