### ISSUE TITLE
New Fluent Design Logo

### ISSUE THREAD

**Issue by akhilesh-balaji** [t1m0thyj/WinDynamicDesktop#237]
Hi!
As you might already know, Microsoft is updating all its icons with fluent design icons. I was wondering if WinDynamicDesktop can also get a fluent design logo, because it looks really odd when juxtaposed with the other windows 10 logos. I have designed a fluent design logo myself:
![BeforeAfter](https://user-images.githubusercontent.com/69246693/92071337-1171bf80-edcc-11ea-843c-9ca398cc0012.png)

If you are interested, you can tell me what changes I can make, and I'll send you all the source files.

**Comment by Cyberdroid1** [comment]
Hi.

I would like to say that the current icon fits the fluent icon theme. 

You can maybe improve the icon by adding some drop shadow to it, maybe?
I think you should not use yellow and black together, it does not look good. 

(Please don't get offended, I don't mean to)

**Comment by akhilesh-balaji** [comment]
@Cyberdroid1 No worries, thanks for the feedback! I realized I could do better, that's why I closed the issue.
