### ISSUE TITLE
Resolution Fix

### ISSUE THREAD

**Issue by ikramul04** [t1m0thyj/WinDynamicDesktop#24]
I have a Samsung SyncMaster 733nw Monitor. the res of the monitor is 1440x900 and the aspect ration is 16:10. The picture it download are in 16:9. I get two black Bars in Up and down Plz Fix this Soon

**Comment by t1m0thyj** [comment]
The wallpapers that are used by default are Apple's, so I'm sorry but I have no control over their aspect ratio. You can make the images stretch on your screen if you prefer that to having them be centered, through the wallpaper settings built into Windows. Or you can also substitute your own set of images if you want to use different ones.
