### ISSUE TITLE
Error when starting WinDynamicDesktop 

### ISSUE THREAD

**Issue by VietUK** [t1m0thyj/WinDynamicDesktop#243]
**Description**
[2020-09-17 22:09:20.196] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WinDynamicDesktop.WallpaperChangeScheduler.GetImageData(SolarData data, ThemeConfig theme)
   at WinDynamicDesktop.WallpaperChangeScheduler.RunScheduler(Boolean forceImageUpdate)
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

**Steps to reproduce**
1. start windows
2. See error.

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Windows 10 2004
 - App version: 4.2.0
 - Installed from: Microsoft Store, Installer EXE, Portable ZIP

**Additional information**

**Comment by 1600kHz** [comment]
I have the same issue. Stops the app from running at all. Reinstalling solved it.

**Comment by t1m0thyj** [comment]
Is this error still happening in the latest version of WDD (4.4.0)?

**Comment by t1m0thyj** [comment]
@VietUK @1600kHz Could you please try this build of WDD and let me know if it fixes your issue? The out of range exception should hopefully be fixed now: https://ci.appveyor.com/project/t1m0thyj/windynamicdesktop/builds/37066592/artifacts

**Comment by 1600kHz** [comment]
Hey Timothy,

Thanks for coming back to this! Unfortunately I can't be of any help, since
the error disappeared for me after a reinstall.

I'll install the latest build nonetheless.

Cheers,
Joris

**Comment by 1600kHz** [comment]
Forgot I was using the UWP version. I'll wait for the update there.

**Comment by t1m0thyj** [comment]
Sorry for the delay, the UWP version has just been updated to 4.5.0 which should include the fix:
"Fixed error when location has different timezone that may be a day ahead of or behind the system clock"
