### ISSUE TITLE
Reopen the google form to submit custom themes

### ISSUE THREAD

**Issue by Cyberdroid1** [t1m0thyj/WinDynamicDesktop#246]
**Is your feature request related to a problem?**
NO

**Describe the solution you'd like**
Please reopen the google form link for submitting custom themes.

LINK- https://docs.google.com/forms/d/e/1FAIpQLScFNP4TTE9nZ_DrbLPMUubEE6h-TNuR2y5Spcr40oWGrORUEQ/viewform?usp=sf_link

**Comment by Cyberdroid1** [comment]
@t1m0thyj Is it possible for you to open this form? I would like to share some of my custom themes.

**Comment by t1m0thyj** [comment]
Please submit new themes here instead: https://github.com/t1m0thyj/WDD-themes

Sorry for taking so long to reply. The Google form received way more responses than I expected which were too many for me to have time to review manually. So I've now created a mostly automated review process.

**Comment by Cyberdroid1** [comment]
Thanks! Will surely do.
