### ISSUE TITLE
Power shell command to disable the networking setting of Azure Data Factory

### ISSUE THREAD

**Issue by AnirudhBragadeesan** [t1m0thyj/WinDynamicDesktop#247]
In Azure Data Factory under the Settings options of "Networking", we have to disable the "Public Network Access", under the "Network access" option. If the public network access is "Enabled" then it is Open to Internet, which states that - "All Networks, including Internet can access Data Factory". And this is more threat of exposing the Data Factory to internet. For which we need a power-shell/AZ CLI command which will help us to disable the 'Public Network Access".

command -
$factory = Get-AzResource -ResourceType Microsoft.DataFactory/factories -ResourceGroupName <resource-group-name> -ResourceName <datafactory-name>
$factory.Properties.publicNetworkAccess = "Disabled"
$factory | Set-AzResource -Force

How to set the property of the $factory.

**Comment by t1m0thyj** [comment]
This is not a PowerShell help forum. Please limit PowerShell discussions to topics related to WDD scripts.
