### ISSUE TITLE
Form for submitting themes not reopened yet???

### ISSUE THREAD

**Issue by TheAlienDrew** [t1m0thyj/WinDynamicDesktop#248]
On [this page](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes), we are supposed to be able to submit new themes, but when trying, it says [the form](https://docs.google.com/forms/d/e/1FAIpQLScFNP4TTE9nZ_DrbLPMUubEE6h-TNuR2y5Spcr40oWGrORUEQ/viewform?usp=sf_link) is closed.

![image](https://user-images.githubusercontent.com/19640692/93949597-e658fc80-fcf5-11ea-96ed-29dc0a322311.png)

**Comment by t1m0thyj** [comment]
Please submit new themes here instead: https://github.com/t1m0thyj/WDD-themes

Sorry for taking so long to reply. The Google form received way more responses than I expected which were too many for me to have time to review manually. So I've now created a mostly automated review process.
