### ISSUE TITLE
Windows unusable during wallpaper transition

### ISSUE THREAD

**Issue by mozram** [t1m0thyj/WinDynamicDesktop#251]
**Description**

PC almost unusable during wallpaper transition.

**Steps to reproduce**
1. Setup dynamic wallpaper
2. Wait till it transition

**Expected behavior**

The wallpaper should change seamlessly without user noticed it, like in KDE Plasma dynamic wallpaper

**Screenshots**

None

**Environment**
 - OS: Windows 10 2004
 - App version: 4.2.0
 - Installed from: Microsoft Store

**Additional information**

Everytime the wallpaper changes, it make my PC unusable for the duration of transition (3-5 sec). Is this software issue, or just Windows things?

Ryzen 2600
32GB RAM

**Comment by t1m0thyj** [comment]
This is not normal behavior for WDD. It shouldn't use much system resources to change the wallpaper image.

If you change your wallpaper image in the Windows 10 Settings app, do you notice that being slow as well?

**Comment by cela96** [comment]
My pc has the same problem, i think it's Windows fault, I noticed it before installing this application and the bug is also present with this app.

Env:

- Windows 10 20H2
- Ryzen 7 3700x
- Samsung 960 Evo
- 32GB of RAM
- App version 4.4.0.0
- Installed from Microsoft Store

**Comment by t1m0thyj** [comment]
Closing the issue as this seems to be Windows fault. Enabling the setting "More Options > Pause while fullscreen apps running" doesn't fix the issue, but may help if your computer is freezing during a full-screen movie or game.

When you change wallpaper in Win10 Settings app, your computer should remain usable. If it doesn't, then you'll likely experience the same issue in WDD.
