### ISSUE TITLE
Edit Italian translation

### ISSUE THREAD

**Issue by PaoloC95** [t1m0thyj/WinDynamicDesktop#253]
There are some things bad translated.
Attached the .png right!

there are:
"Configura tempismo" to "Cambia località"
"Shuffle theme daily" to "Cambia tema ogni giorno"
"Manage installed scripts" to "Gestisci Scripts installati"

![Immagine](https://user-images.githubusercontent.com/43925971/95622885-a70c0900-0a74-11eb-931c-9e2d0547da4a.png)

And then on the select theme screen:
"Previewing Sunrise" to "Anteprima dell'alba"
"Previewing Day" to "Anteprima del giorno"
"Previewing Sunset" to "Anteprima del tramonto"

**Comment by t1m0thyj** [comment]
@PaoloC95 Thanks for reporting this! I've updated the strings you mentioned in POEditor, am unsure about a few of them:
* The first string says "Configure Timing" in English so I believe the current translation is correct
* For "Previewing Sunrise/Day/Sunset/Night", the string is split in half, so would this be ok?
![image](https://user-images.githubusercontent.com/22344007/95657700-dd34a180-0ae3-11eb-9624-f509896aa467.png)

There are 34 more untranslated strings for the Italian translation. Feel free to contribute to the Italian translation by joining the POEditor project here: https://poeditor.com/join/project?hash=DEgfVpyuiK

**Comment by PaoloC95** [comment]
Yes perfect, i've fixed also some parts on poeditor for the italian lang! :D

**Comment by Dustmix** [comment]
I completed the italian translation and also fixed a few things.

**Comment by t1m0thyj** [comment]
Thanks @PaoloC95 @Dustmix , the Italian translation was updated in v4.4.0
