### ISSUE TITLE
Theme Builder

### ISSUE THREAD

**Issue by HaydenPalmer** [t1m0thyj/WinDynamicDesktop#255]
**Is your feature request related to a problem?**
While there are a wide range of offers available online in terms of themes, quite a few of them are paid. I don't mind this but it's slightly frustrating not being able to pick your own.

**Describe the solution you'd like**
It would be nice to have a standalone (or built into the software) theme builder. It would let you input a variety of high-quality images in which you can turn into a theme that the software recognises. Maybe you could specify at which points of time you would like the image to change (depending on how it currently works).

**Describe alternatives you've considered**
N/A

**Additional information**
N/A

**Comment by t1m0thyj** [comment]
Have you tried the [.ddw Theme Creator](https://ddw-theme-creator.vercel.app/)? It can create a theme from a single image or set of images that you provide. Thanks to @gdstewart for creating it.

**Comment by HaydenPalmer** [comment]
> 
> 
> Have you tried the [.ddw Theme Creator](https://ddw-theme-creator.vercel.app/)? It can create a theme from a single image or set of images that you provide. Thanks to @gdstewart for creating it.

I didn't realise this even existed, thanks for alerting me to it! I originally started using your software over a year ago but stopped recently for a couple of months but I'm happy to see this has been made. I'll go ahead and close the issue.
