### ISSUE TITLE
[Feature Request] Give option to make lock screen background dynamic as well

### ISSUE THREAD

**Issue by PreciousWarrior** [t1m0thyj/WinDynamicDesktop#257]
**Is your feature request related to a problem?**
Yes, I keep my PC locked very often, and it's really annoying that the lock screen wallpaper is different from the main dyanmic wallpaper that I have. I have tried to set the lock screen background to one stage of the dynamic wallpaper, but it just makes it looks worse and inconsistant. 

**Describe the solution you'd like**
The solution I would like is a small checkbox that can be pressed (either from the dropdown menu or the select theme window), which will set the lock screen background to be dynamic as well. This can be a boolean value in settings.conf as well. I don't know how this would be implemented, but I _think_ it would be easy enough if the registry is being used to change the wallpaper, since I believe there is a registry entry for the lock screen background as well.

**Describe alternatives you've considered**
I've tried looking into other dynamic wallpaper apps as well, but none that I have seen have had a lock screen functionality. I tried making a script, but it didn't work out.

**Comment by VNRARA** [comment]
Lol we have the EXACT same idea: #258 #

**Comment by zhangyuesai** [comment]
You can install the script to make lockscreen match the desktop:
https://windd.info/scripts/

**Comment by Cyberdroid1** [comment]
The problem of non consistent changes is because of windows. The folder where the lock screen images are saved are not updated regularly. Furthermore, the ownership of that folder is given to "System" in windows.

So, if there is some fix for that, or the app gets functionality to access that folder by taking ownership, it can be possible to achieve good results.

**Comment by guille003** [comment]
Has it been solved? Because I'm running the script and I don't even get it to update once. May it be that I'm using Windows Store app instead of having downloaded the .exe file?

**Comment by Cyberdroid1** [comment]
It's not an app limitation, instead a Windows bug. And as it is with other Windows stuff, it would take a long time for this to get fixed.

**Comment by fillwithjoy1** [comment]
Look into Lockscreen Wallpaper Synchronizer, it works but it's not exactly reliable
https://www.microsoft.com/store/productId/9N66R5QWK9TM

**Comment by t1m0thyj** [comment]
Tracking in #321 as I'd like to implement this feature but am hindered by Windows API limitations
