### ISSUE TITLE
Can you also please support showing video files?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [t1m0thyj/WinDynamicDesktop#26]
Could be cool...

**Comment by t1m0thyj** [comment]
I agree this could be cool, but it would be very difficult to implement and beyond the scope of what I intend for this program to do.

**Comment by AndroidDeveloperLB** [comment]
Too bad.
Do you know of a similar app? Freeware of course ... :)

**Comment by t1m0thyj** [comment]
@AndroidDeveloperLB Not really, sorry. I came across [this article](https://www.makeuseof.com/tag/ways-set-video-desktop-background/), but based on the comments on that page it seems like the ways that are mentioned either aren't ideal or don't work well anymore.

**Comment by AndroidDeveloperLB** [comment]
ok thanks anyway
