### ISSUE TITLE
OutOfMemoryException and NotSupportedException

### ISSUE THREAD

**Issue by ViewWay** [t1m0thyj/WinDynamicDesktop#261]
**Description**

 System.Runtime.InteropServices.COMException: 无法找不到组件。 (异常来自 HRESULT:0x88982F50)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   在 System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   在 System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   在 System.Windows.Media.Imaging.BitmapImage.EndInit()
   在 WinDynamicDesktop.WPF.ThemePreviewerViewModel.CreateImage(MemoryStream memory)
   在 WinDynamicDesktop.WPF.ThemePreviewerViewModel.Start(Int32 index)
   在 WinDynamicDesktop.WPF.ThemePreviewerViewModel.PreviewTheme(ThemeConfig theme)
   在 WinDynamicDesktop.ThemeDialog.UpdateSelectedItem()
   在 WinDynamicDesktop.ThemeDialog.listView1_SelectedIndexChanged(Object sender, EventArgs e)
   在 System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   在 System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   在 System.Windows.Forms.ListView.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[2020-10-28 14:26:04.033] System.NotSupportedException: 未找到适用于完成此操作的图像处理组件。 ---> System.Runtime.InteropServices.COMException: 无法找不到组件。 (异常来自 HRESULT:0x88982F50)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   在 System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   在 System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   在 System.Windows.Media.Imaging.BitmapImage.EndInit()
   在 WinDynamicDesktop.WPF.ThemePreviewerViewModel.CreateImage(MemoryStream memory)
   在 WinDynamicDesktop.WPF.ThemePreviewerViewModel.GoTo(Int32 index)
   在 WinDynamicDesktop.WPF.ThemePreviewerViewModel.set_SelectedIndex(Int32 value)
   在 WinDynamicDesktop.WPF.ThemePreviewerViewModel.Next()
   在 WinDynamicDesktop.WPF.ThemePreviewerViewModel.<.ctor>b__60_0(Object s, EventArgs e)
   在 System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   在 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   在 WinDynamicDesktop.Program.Main(String[] args)
-->

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Environment**

OS: Windows 10 20H2 
App version :4.0.3
install from : Portable

**Additional information**

**Comment by t1m0thyj** [comment]
An OutOfMemory exception may be caused by an invalid image in a theme. Just released WinDynamicDesktop 4.5.0 which should show a user-friendly error when this happens.
