### ISSUE TITLE
Big Sur 11.0.1 New Wallpaper Released - Request for inclusion integration

### ISSUE THREAD

**Issue by chrisquim** [t1m0thyj/WinDynamicDesktop#262]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
Big Sur 11.0.1 New Wallpaper has just been released. request for inclusion on the apps fetching database on wallpapers from app directly just like the other previous wallpapers of official apple.

**Describe alternatives you've considered**
well, users (or power users) could manually download, add and configure (not to mention the theme.json file to match configure manually).. The point is, inclusion integration built-in as convenience for the casual, novice and majority of the users.

**Additional information**

- 4 new day-to-night illustrated landscape wallpaper
- 4 new light-and-dark landscape photography wallpaper

Download Link: [9to5mac.com - macOS Big Sur 11.0.1 includes even more new wallpapers, download them here](https://9to5mac.com/2020/10/28/macos-big-sur-11-0-1-includes-even-more-new-wallpapers-download-them-here/)

![Big-Sur-wallpapers](https://user-images.githubusercontent.com/13996297/97513544-837b1500-19c7-11eb-9fe8-6af4ee3a8c0c.png)

**Comment by t1m0thyj** [comment]
.ddw packages for new wallpapers are now available for download [here](https://github.com/t1m0thyj/WDD-mac-themes/releases/tag/big-sur). I plan to release a WDD update tomorrow that adds them to the list of themes preinstalled in the app.

**Comment by t1m0thyj** [comment]
These themes are included in WDD v4.4.0
