### ISSUE TITLE
Any plans for multiple-monitors-supported?

### ISSUE THREAD

**Issue by EnormousKnob** [t1m0thyj/WinDynamicDesktop#264]
For instance, I have 3 displays, and I would like to apply different theme on each display.
Will that happen any time soon?

**Comment by Cyberdroid1** [comment]
I think Windows does not support this functionality natively.

**Comment by theapplemaniac** [comment]
In the windows setting, in Backgrounds, you can right-click a photo to set it to a specific monitor.

**Comment by EnormousKnob** [comment]
> In the windows setting, in Backgrounds, you can right-click a photo to set it to a specific monitor.

Yeah but in that case the backgrounds wouldn't be shifting during 24 hours, best feature of this software is gone

**Comment by theapplemaniac** [comment]
Yh I was seeing if there was a function where WinDynamicDesktop only changes the wallpapers on specific displays.

**Comment by livejamie** [comment]
I would love this feature as well, most wallpaper programs support this

**Comment by Cyberdroid1** [comment]
Since Windows is finally(!) getting this feature in Insider Dev builds, seems like this feature will be great to have for the app.

> I would love this feature as well, most wallpaper programs support this

@livejamie Which app supports this?

**Comment by livejamie** [comment]
> Since Windows is finally(!) getting this feature in Insider Dev builds, seems like this feature will be great to have for the app.
> 
> > I would love this feature as well, most wallpaper programs support this
> 
> @livejamie Which app supports this?

John's Background Switcher is probably the most popular one

https://johnsad.ventures/software/backgroundswitcher/

**Comment by t1m0thyj** [comment]
Tracking in #321 as I'd like to implement this feature but am hindered by Windows API limitations
