### ISSUE TITLE
Changing system colors to light/dark automatically

### ISSUE THREAD

**Issue by itsdeyan** [t1m0thyj/WinDynamicDesktop#268]
I just think it'd be cool if the app was able to also change the windows colors with the sunrise/sunset, as it is in macos right now.

**Comment by t1m0thyj** [comment]
WDD can do this if you enable scripts. See https://github.com/t1m0thyj/WDD-scripts/tree/master/stable#readme

**Comment by itsdeyan** [comment]
Awesome, thank you.
