### ISSUE TITLE
异常关闭

### ISSUE THREAD

**Issue by cuijianzhuang** [t1m0thyj/WinDynamicDesktop#273]
- WDD Version:
- OS Version:

Steps to Reproduce:

1.
2.

Are you using the Microsoft Store version of WDD?: Yes/No
[
![Snipaste_2020-12-01_17-39-08](https://user-images.githubusercontent.com/31424401/100723063-48bc3080-33fc-11eb-8bcb-00609da5d7a6.png)
](url)

**Comment by t1m0thyj** [comment]
It looks like you ran the WDD installer as administrator to put it in "C:\Program Files", but are running WDD as a non-admin user that doesn't have permission to write settings there. This issue should be resolved if you install WDD to a different location that doesn't require admin access to write to.

**Comment by cuijianzhuang** [comment]
ok
