### ISSUE TITLE
Microsoft Defender detects false-positive as "Trojan:MSIL/Masslogger.VN!MTB"

### ISSUE THREAD

**Issue by Fytuf** [t1m0thyj/WinDynamicDesktop#274]
- WDD Version: 4.4.0
- OS Version: Windows 10 1909 (Build 18363.1198)

Steps to Reproduce:

1. Update Windows 10
2. Install WinDynamicDesktop

Are you using the Microsoft Store version of WDD?: No

**Comment by OstenTV** [comment]
I have the same issue on Windows 10 20H2

**Comment by NicolasBuecher** [comment]
Same for me.

Taking a look at the closed issues, it seems to happen often but it still have the community trust.

https://www.virustotal.com/gui/url/37ecea1b74427283df86eb36a27cbb60c6951fd0ac792090d93e0d58f562787e/detection

**Comment by philliml74** [comment]
It would seem that the Windows Store version of WDD is also getting tagged.
![image](https://user-images.githubusercontent.com/5111693/102017851-6744f480-3d37-11eb-8608-c322ec9eab39.png)

**Comment by DanteJenzie** [comment]
Appeared to me today, have it uninstalled due to concerns :(

**Comment by Fytuf** [comment]
Everyday I have Windows Defender remove it from my computer when I boot. I hope for this to be fixed soon.

**Comment by Tissitron** [comment]
I had the same issue with the Windows Store version 5 days ago. Windows Defender detected it as "Trojan:MSIL/Masslogger.VN!MTB". I'm worried and hope this is just a false positive.

- WDD Version: 4.4.0 (UWP)
- OS Version: Windows 10 Pro 20H2 (Build 19042.685)

**Comment by t1m0thyj** [comment]
This is a false positive (incorrectly detected as malware), hence why none of the other scanners on VirusTotal detect anything.

I've reported the WDD executable as a false positive on Microsoft's website - please do the same if you're able to hopefully accelerate this being resolved: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by Fytuf** [comment]
I already reported it as a false positive, I hope Microsoft will use this data.

![chrome_chuevqMH4t (2)](https://user-images.githubusercontent.com/72277532/102977245-f5e80d00-44bf-11eb-9879-2a986f333102.png)

**Comment by t1m0thyj** [comment]
False positive should now be fixed, please let me know if resolved for you. Update from Microsoft below:
> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
>
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
>
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

**Comment by Fytuf** [comment]
I'm glad to finally see this fixed. I will now close the issue.

**Comment by cela96** [comment]
@t1m0thyj However, IMO since it happens very often it would be necessary to understand what is the cause of the virus detection.

**Comment by t1m0thyj** [comment]
> since it happens very often
Is the problem present again - is Windows Defender flagging WDD for you?
