### ISSUE TITLE
Install the app per machine

### ISSUE THREAD

**Issue by xmha97** [t1m0thyj/WinDynamicDesktop#275]
Hi,
I want to install the app for all users to %ProgramFiles% instead of %LocalAppData%

**Comment by xmha97** [comment]
Support for this feature also solves this issue: #273

**Comment by t1m0thyj** [comment]
This option has been added in 75b80ec. In the next version of WDD it will be possible to install the app for all users in %ProgramFiles%, and settings will be stored in %LocalAppData%.

**Comment by xmha97** [comment]
Thanks.

**Comment by t1m0thyj** [comment]
Released in WinDynamicDesktop 4.5.0
