### ISSUE TITLE
Error when opening WDD

### ISSUE THREAD

**Issue by elajits** [t1m0thyj/WinDynamicDesktop#276]
- WDD Version: 4.4.0
- OS Version: windows 10 Pro  20h2 Build (19042.685)

Steps to Reproduce:

1.it start to happen after a reboot of windows 10

 whats wrong
2.when i trying to start WDD i getting a error message that say i have to read the WinDynamicDesktop.exe log file
but i cant understand
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/5696861/WinDynamicDesktop.exe.log)
![error message ](https://user-images.githubusercontent.com/8584951/102235895-21cd2680-3ef3-11eb-8873-450f95bc536c.png)

Are you using the Microsoft Store version of WDD?: Yes

**Comment by elajits** [comment]
i manage to solve the issue! but i am still want to know what the issue can be!
i set my location my self the windows Location service just gives me error!

**Comment by t1m0thyj** [comment]
Older versions of WDD had some issues with locations that have a different timezone that may be a day ahead of or behind the system clock. This should be fixed in WinDynamicDesktop 4.5.0.
