### ISSUE TITLE
How to set a proxy for this app?

### ISSUE THREAD

**Issue by UserNameIllegal** [t1m0thyj/WinDynamicDesktop#278]
Sorry, I didn't find any place where I can set a proxy for internet.

**Comment by t1m0thyj** [comment]
You can use HTTP_PROXY or HTTPS_PROXY environment variable to define proxy settings for apps on your device including WDD: https://stackoverflow.com/a/41570055/5504760

**Comment by babyNEKO** [comment]
没办法设置代理，下载速度太慢

**Comment by t1m0thyj** [comment]
> 没办法设置代理，下载速度太慢

You can download themes from [here](https://github.com/t1m0thyj/WDD-mac-themes) in your browser and import them into the app if downloads are too slow in your region.
