### ISSUE TITLE
Option to remove status bar icon

### ISSUE THREAD

**Issue by brunovieira97** [t1m0thyj/WinDynamicDesktop#28]
Would be nice to disable the status bar icon, since settings can be done on the conf file. This way it would be completely seamless, running on background.

**Comment by t1m0thyj** [comment]
Added in version 1.3, see the README for details:

> If you want to run the app silently with no icon in the system tray, you can do this by editing the settings.conf file which is in the same folder as the EXE. Change the setting `"hideTrayIcon":false` to `"hideTrayIcon":true` (or add it if it doesn't exist), then restart the app.
