### ISSUE TITLE
In some places the controls overlap with other controls.

### ISSUE THREAD

**Issue by RedApelsin** [t1m0thyj/WinDynamicDesktop#280]
# Screenshots
![image](https://user-images.githubusercontent.com/59859860/106934474-37104580-672b-11eb-97ae-ff988103e752.png)
![image](https://user-images.githubusercontent.com/59859860/106934796-9f5f2700-672b-11eb-9677-c2ef82e94714.png)

# Info
WinDynamicDesktop 4.4.0
Windows 10
Are you using the Microsoft Store version of WDD?: No

# Steps to Reproduce:
1) Open app
2) Select Russian language
3) Try to change a theme or language

**Comment by t1m0thyj** [comment]
Thanks for reporting, this will be fixed in the next release 🙂
