### ISSUE TITLE
Got stuck generating cover

### ISSUE THREAD

**Issue by leostudiooo** [t1m0thyj/WinDynamicDesktop#283]
- WDD Version: latest
- OS Version: Windows 10 Home CN 20H2 19042.746

Steps to Reproduce:

1. Import Beach.zip
[Beach.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/5936324/Beach.zip)
2. Got Stuck
3. Other themes disappear after force stop in taskmgr.

Are you using the Microsoft Store version of WDD?: No

**Comment by leostudiooo** [comment]
Screenshot: 
![image](https://user-images.githubusercontent.com/35419343/107110112-3806bb80-6880-11eb-871b-a10ee2c00d77.png)

**Comment by t1m0thyj** [comment]
Hello, images #3 and #4 in your theme seem to be corrupted, as I'm not able to load them in MSPaint:
![image](https://user-images.githubusercontent.com/22344007/120198899-a20ced00-c1f0-11eb-9f71-fd114328c74a.png)

Changing these images to a format that MSPaint can open should make your theme work in WDD.

**Comment by t1m0thyj** [comment]
There will be a better error message for this case in future versions of WDD:
![image](https://user-images.githubusercontent.com/22344007/120201680-b43c5a80-c1f3-11eb-9d49-0e17757ae114.png)
