### ISSUE TITLE
The desktop turned pink, black

### ISSUE THREAD

**Issue by ze0ss** [t1m0thyj/WinDynamicDesktop#285]
- WDD Version: v4.4.0
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Apply theme
2. Wait for a few hours
3. See bug

Are you using the Microsoft Store version of WDD?: No (Since I need ps1 scripts)

Short description: I downloaded WDD just today, and started using it, I applied a theme, set the city, and minimised it, to tray, and went on about my day as usual.
Much to my surprise (and really, I seldom see my desktop since I have almost nothing on it and I have many programs open at a time, and need to switch between them...), I saw the **whole** desktop is just a solid pink-ish colour, and took me about 20 seconds to realise what had happened, I remembered about WDD, it had set the theme, so I quickly disabled WDD and actually exited (closed) it to see if it gets my (static) wallpaper back, but no it did not.

I tried setting another static wallpaper, from the many I have, a normal PNG or JPEG picture, but all the desktop did was either remain solidly pink or change to #000000 (Black).
Left without any more options, I started to lose my calm, and almost proceeded to restart the computer, but decided to try one last thing: Change theme manually, from "Personalisation" settings of windows.
Et voila! It not only changed my theme, but also reverted my desktop to a seemingly normal state, and I was ecstatic, and was able to change wallpapers without any problem (Remember, WDD is still closed), and then now that I have some time, decided to report this issue here, so, O kind Tim sir, I request you to please look into this and also explain me about it, what actually happened, as I'm really interested.
Mind you though, I have really liked this app so far, and will continue to use it, once the issue is resolved.

Necessary technical specs:
OS: Windows 10 x64 version 1909
Screen resolution: 1920*1080 (FHD), only one monitor
All software and hardware are up-to-date as on 11 Feb 2021

Powershell script in use: System theme changer

Feel free to ask anything else
Attached below is a screenshot of the pink desktop.
Thanks

![20210211_191240.jpg](https://user-images.githubusercontent.com/56572179/107645821-359ccb00-6c9f-11eb-9334-7b17bda82d58.jpg)

**Comment by t1m0thyj** [comment]
Did you try restarting your PC to see if it would resolve the pink desktop?

Occasionally the `explorer.exe` process gets into a weird state, and restarting your PC (or just the explorer process) can fix it. My guess is that's what happened, and this was a one-off thing you shouldn't experience again.

If you do experience it again, let me know.

**Comment by abh-oss01** [comment]
I did restart explorer.exe, although not the pc itself, but it didn't fix it.
And like I said, I changed the theme, and then only it fixed it.
I'll surely report here if it happens again.
Thanks

**Comment by t1m0thyj** [comment]
Feel free to reopen if it happens again.
