### ISSUE TITLE
No way to remove and uninstall as well as no way to determine where files are?

### ISSUE THREAD

**Issue by Bjorn218** [t1m0thyj/WinDynamicDesktop#294]
Not my issue if there are duplicates  this is my first report

- WDD Version: 4.4.0
- OS Version: Windows 10

Steps to Reproduce:

1.causes system to freeze just past login and cannot use anything
2.once booting to safe mode with winpe disk there is no way to uninstall dynamic desktop

Are you using the Microsoft Store version of WDD?: Yes/No yes

**Comment by emberaholdon** [comment]
> Not my issue if there are duplicates this is my first report
> * WDD Version: 4.4.0
> * OS Version: Windows 10
> 
> Steps to Reproduce:
> 
> 1.causes system to freeze just past login and cannot use anything
> 2.once booting to safe mode with winpe disk there is no way to uninstall dynamic desktop
> 
> Are you using the Microsoft Store version of WDD?: Yes/No yes

Windows Store apps are located in %localappdata%\packages (usually c:\users\username\appdata\local\packages)
Be careful about what you change there.

**Comment by t1m0thyj** [comment]
I'm not familiar with WinPE disk, typically WDD should show up in the list of installed programs. If it doesn't, you can find its files here: https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed

If you need to disable WDD from launching on startup, you can disable it from Task Manager.
