### ISSUE TITLE
Display when the picture changes

### ISSUE THREAD

**Issue by Dattito** [t1m0thyj/WinDynamicDesktop#298]
### I would like to see a feature in the theme settings where you can see for every picture in a theme at what time it will be displayed.

[![Screenshot-2021-03-19-094522.png](https://i.postimg.cc/wBynqjCz/Screenshot-2021-03-19-094522.png)](https://postimg.cc/CZ0cJSMr)

**Comment by zzt990814** [comment]
It would be better if the user could set the time when each picture appears.

**Comment by t1m0thyj** [comment]
The time of day for each image is now displayed in WDD v5.

**Comment by zzt990814** [comment]
您好，您的邮件已收到，谢谢。祝好！
