### ISSUE TITLE
Support for multiple virtual desktop backgrounds for version >= Build 21337

### ISSUE THREAD

**Issue by watermarkhu** [t1m0thyj/WinDynamicDesktop#299]
Since [Windows Insider Build 21337](https://blogs.windows.com/windows-insider/2021/03/17/announcing-windows-10-insider-preview-build-21337/), support is added for setting the background per virtual desktop. It would be great to see WDD officially support this feature by allowing us to set a different dynamic background per virtual desktop. 

![Virtual Desktops](https://46c4ts1tskv22sdav81j9c69-wpengine.netdna-ssl.com/wp-content/uploads/prod/sites/44/2021/03/vd-right-click.png)

**Comment by t1m0thyj** [comment]
Thanks for reporting, I hope to support this soon once I'm able to work around an issue with the VirtualDesktop API: https://github.com/Grabacr07/VirtualDesktop/pull/49.

**Comment by t1m0thyj** [comment]
An update on the situation: Microsoft has made breaking changes to the Virtual Desktop API and no one has figured out how to use the new APIs yet, so this issue is currently blocked and depending on https://github.com/Grabacr07/VirtualDesktop/issues/55.

**Comment by t1m0thyj** [comment]
Tracking in #321 as I'd like to implement this feature but am hindered by Windows API limitations

**Comment by t1m0thyj** [comment]
Closing as this issue is still relevant but superseded by #398

**Comment by direrFlood** [comment]
I wish this is a feature.

**Comment by t1m0thyj** [comment]
@b4nn WDD doesn't yet support a separate wallpaper for each virtual desktop which is what this issue originally requested. However I have created a script to sync the same wallpaper across desktops which sounds like it would solve your problem: https://github.com/t1m0thyj/WDD-scripts/tree/master/experimental#synchronize-virtual-desktops

Could you give it a try and let me know if you encounter any issues?
