### ISSUE TITLE
Not automatically changing

### ISSUE THREAD

**Issue by Saihaan06** [t1m0thyj/WinDynamicDesktop#302]
the wallpaper is not automatically changing, it only changes after I click refresh in the tray icon

**Comment by HaydenPalmer** [comment]
Did you resolve this issue? Maybe a power saving method that prevents tasks running in the background?

**Comment by t1m0thyj** [comment]
In order to determine whether this is a problem with WDD or your machine, could you try enabling the Slideshow feature built-in to Windows 10, and see if that works to periodically change your wallpaper? https://www.windowscentral.com/enable-windows10-slideshow-and-battery
