### ISSUE TITLE
Night Mode does not affect the script

### ISSUE THREAD

**Issue by alphawent** [t1m0thyj/WinDynamicDesktop#308]
I turned on the 'Night Mode' during the day, but the windows theme is still light.

Maybe one more parameter should be passed to indicate the 'Night Mode'?
```powershell
<scriptName> [-daySegment2] <int> [-daySegment4] <int> [-imagePath] <string>
```

**Comment by alphawent** [comment]
```powershell
<scriptName> [-NightMode] <int>  [-daySegment2] <int> [-daySegment4] <int> [-imagePath] <string>
```
Does that look reasonable?

**Comment by t1m0thyj** [comment]
Thanks, this was an oversight and a `nightMode` parameter has been added in WinDynamicDesktop 4.5.0.
