### ISSUE TITLE
[Feature Request] Auto Dark Mode

### ISSUE THREAD

**Issue by xmha97** [t1m0thyj/WinDynamicDesktop#322]
Hi, I want the dark mode to be activated automatically at night and the dark mode disabled during the day.

**Comment by Geeyun-JY3** [comment]
Try the [PowerShell scripts](https://github.com/t1m0thyj/WDD-scripts).

**Comment by t1m0thyj** [comment]
What @Geeyun-JY3 said 🙂 particularly the scripts for changing Windows app and system themes: https://github.com/t1m0thyj/WDD-scripts/tree/master/stable#readme

**Comment by fillwithjoy1** [comment]
Use Auto Dark mode
