### ISSUE TITLE
Norton says that windd is unsafe( I know its safe i just wanted to let you know)

### ISSUE THREAD

**Issue by Smartninja365** [t1m0thyj/WinDynamicDesktop#323]
- WDD Version:
- OS Version:

Steps to Reproduce:

1.
2.

Are you using the Microsoft Store version of WDD?: Yes/No

**Comment by t1m0thyj** [comment]
Thanks for reporting here, please also report as a false positive to Norton if you're able: https://submit.norton.com/

**Comment by t1m0thyj** [comment]
Assuming this has been fixed since noone else has reported it for the latest WDD version.
