### ISSUE TITLE
Wallpaper switches back to one specific 

### ISSUE THREAD

**Issue by theface78** [t1m0thyj/WinDynamicDesktop#325]
- WDD Version: 4.4.0 and 4.5.0
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. I have set a 24h wallpaper Big Sur #1, set my location to my city, the sunrise and sunset times are loaded.
2. The wallpaper for the correct time of the day gets set, but after some time it always changes back to on specific wallpaper (number 8 out of 16 in total) and only changes back to the correct wallpaper that is set for the specific hour when I click on refresh wallpaper. 

Are you using the Microsoft Store version of WDD?: Tried both, also manually installed an older version too

**Comment by theface78** [comment]
Nobody? Nothing? I cannot be the only one having this problem. Maybe too lfew people use 24h wallpapers and it´s not so obvious when the wallpaper is just supposed to change three times instead of 16 times?

**Comment by omegamalkior** [comment]
same thing and it's driving me crazy. Hate seeing pure yellow sunsets at 1:00pm here. And changing no setting fixes this

**Comment by t1m0thyj** [comment]
Are you still seeing this issue in WDD v5? I use it on several devices and with the latest version (v.5.1.0) I've not had any issues with wallpapers refreshing.

If you are still seeing this issue in the latest version of WDD, please edit the `settings.json` configuration file and change `"debugLogging": false` to `"debugLogging": true`. This will enable more detailed logging in a `debug.log` file that shows all the wallpaper scheduler events. If you run WDD for a day or so with this setting enabled and upload the log file, it may help with diagnosing the issue.

**Comment by t1m0thyj** [comment]
Closing for now, if you continue to see the issue please post a debug log file.
