### ISSUE TITLE
Ultrawide Support

### ISSUE THREAD

**Issue by jonathanmwood** [t1m0thyj/WinDynamicDesktop#326]
Love the app. It would be great if there was a zoom option that zooms the images instead of stretching to fit when using ultrawide monitors

**Comment by Synaptic149** [comment]
I don't have an ultrawide and don't know if this works. If you use the Github version (not the Microsoft Store version,) you can go into Windows Settings --> Personalization --> Background -- Choose a fit and change the fit there.

**Comment by t1m0thyj** [comment]
You should be able to change the wallpaper fit in Windows 10 settings. If you encounter an issue where the fit setting isn't remembered, there's a workaround documented [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Known-issues#wallpaper-fit-not-saved-with-multiple-monitors).
