### ISSUE TITLE
When starting up computer, WDD initially preserves "Span" setting for multiple monitors, but switches to "Fill" during initialization

### ISSUE THREAD

**Issue by josephclaytonhansen** [t1m0thyj/WinDynamicDesktop#327]
- WDD Version: WinDynamicDesktop 4.5.0 (UWP)
- OS Version: Windows 10 Education 20H2

Steps to Reproduce:

1. Set WDD to display the same on two monitors.
2. Go to Personalize and change to Span.
3. Restart your computer, or shut it down.
4. Wait for a few seconds- will switch from Span to Fill

Are you using the Microsoft Store version of WDD?: Yes

**Comment by t1m0thyj** [comment]
This is a known issue, a workaround is documented here: https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Known-issues#wallpaper-fit-not-saved-with-multiple-monitors
