### ISSUE TITLE
new composition

### ISSUE THREAD

**Issue by Vidarius** [t1m0thyj/WinDynamicDesktop#33]
* change to suitable picture after checked system time (check 1/minute) - so the picture is correct again at the latest 1min after the end of the stand-by mode
* depending on the date/month of other rhythm of the pictures (summer / winter)

**Comment by t1m0thyj** [comment]
Just released version 1.3, with rewritten code for the wallpaper change scheduler that should hopefully fix the issue of the picture not updating after wake up from sleep (if you still experience issues relating to this, please report in #12). I'd rather not have a timer that runs every minute if I can avoid it, to keep the program as efficient as possible.

Changing the wallpaper based on the time of month or year would be neat, but beyond the intent of this program which is to imitate the sunrise/sunset time based image switching of macOS Mojave.
