### ISSUE TITLE
macOS Monterey Dynamic Wallpapers

### ISSUE THREAD

**Issue by snajdovski** [t1m0thyj/WinDynamicDesktop#331]
The macOS Monterey beta is live, I think there is .heic file floating around as well as 2 jpegs with the wallpapers on Reddit, I dont want to link it, but simple google search should reveal the file.

**Comment by Bellisario** [comment]
Yes, Monterey Dynamic Wallpaper (the default) it's available on iSpazio:
https://wallpapers.ispazio.net/advert/macos-12-monterey-official-stock-wallpaper-6k

**Comment by t1m0thyj** [comment]
The full resolution version is here: https://www.idownloadblog.com/2021/06/07/macos-monterey-wallpaper/

I'll add it to WDD tonight :)

**Comment by Bellisario** [comment]
@t1m0thyj, can you explain me how can you convert HEIC format to WDD?
 I've opened also a discussion about it... #332

**Comment by t1m0thyj** [comment]
@Bellisario See the link to an online HEIF to JPEG converter here: https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes#image-files

**Comment by Bellisario** [comment]
Oh, good! Thank you @t1m0thyj! :smile:

**Comment by t1m0thyj** [comment]
Here they are in DDW format: https://github.com/t1m0thyj/WDD-mac-themes/releases/tag/monterey

**Comment by Bellisario** [comment]
One problem... the theme isn't shown in the app, so, I think for now we need to add it manually, but for the future I think can be useful to add it.

**Comment by t1m0thyj** [comment]
@Bellisario The theme is now bundled in WDD 4.6.0
