### ISSUE TITLE
Inform the user download how download is long

### ISSUE THREAD

**Issue by Bellisario** [t1m0thyj/WinDynamicDesktop#333]
Now, if you want download a new background, you need to start download to watch how is long, so, I'd like to "preview" this information.

**Comment by t1m0thyj** [comment]
WDD doesn't know your download speed right away, it needs "to start download to watch how is long" same as you. I'm not sure how to preview this information without starting a download in the background which I don't really want to do.

Have you had issues with the Cancel button being slow to respond? As long as clicking Cancel on a slow download stops it right away, I don't see a problem with the current behavior.

**Comment by Bellisario** [comment]
Ok, @t1m0thyj, let me explain: I don't want to know how the download takes (seconds) but how the download is long (MB). So, I just think that can be useful to know how long is the file you are going to download. To explain me, here is an example of GitHub release (where you can see download size):
![image](https://user-images.githubusercontent.com/72039923/121586669-361e5600-ca34-11eb-8bb1-ff4e81cebe64.png)

**Comment by t1m0thyj** [comment]
Sorry for misunderstanding the original request, this is an excellent idea and I've implemented in WDD 4.6.0
