### ISSUE TITLE
Any plans for a x86-64 build?

### ISSUE THREAD

**Issue by sungaila** [t1m0thyj/WinDynamicDesktop#335]
WinDynmaicDesktop is built on .NET Framework 4.5 and should be able to run as x86-64, shouldn't it? Is there a reason it isn't compiled as _Any CPU_?

Great work by the way, using it for months on my desktop PC and I love it! :)

**Comment by t1m0thyj** [comment]
WinDynamicDesktop is compiled as "Any CPU". Are you encountering issues running it on an x86-64 system? If so what version of WDD are you running?

**Comment by t1m0thyj** [comment]
Please disregard my earlier comment. I have found that "Prefer 32-bit" option was selected in the WDD project. I'm not sure why Microsoft makes this the default, but I'll probably disable it for future versions so WDD can run 64-bit on 64-bit systems 🙂

**Comment by sungaila** [comment]
Neat! 👍 Please make sure to edit the UWP manifest for the new target. I use the Windows Store release for the convenient auto update.

Thanks!

**Comment by t1m0thyj** [comment]
@sungaila WDD is definitely capable of running as x86-64, but after further consideration I'm unsure whether I want it to. There's no reason why it should need more than 4GB addressable space. Since WDD runs idle in the background most of the time, I'd like to keep memory usage minimal, and switching to 64-bit addressing basically doubles the RAM usage. Any thoughts about this?

**Comment by sungaila** [comment]
Windows 10 on ARM has an emulation for x86-64 (in preview) that is about 3-4 times faster than the x86 one.

Might not be of much use here, since WDD idles most of the time.

The only reason I opened this issue was because I opened the Task Manager and sorted all process by architecture: WDD was the only 32 bit app here and that made me question why. 😄

**Comment by emberaholdon** [comment]
Not everything must be 64 bit, especially considering the resource usage from an app that, as you said, idles most of the time. IMHO it’s totally worthless in this case.

**Comment by sungaila** [comment]
I wouldn't call it worthless. You save the overhead of CPU cycles and memory usage for WoW64, since 32 bit apps can't run natively. Other than that security features like ASLR are not supported either.

In any other case I wouldn't recommand the effort to get this done. But here it's just a simple checkbox and .NET Framework will build architecture independent CIL.

**Comment by t1m0thyj** [comment]
> Windows 10 on ARM has an emulation for x86-64 (in preview) that is about 3-4 times faster than the x86 one.

Sorry if I'm missing something obvious, could you cite a source for this? According to [here](https://www.techrepublic.com/article/windows-on-arm-this-is-how-well-64-bit-emulation-is-working/):
> In general, x86 and x64 emulated apps should be similar in performance, except for the larger address space.
> ...
> For common editing tasks, the 32-bit version of Photoshop running in emulation was often very slightly faster than the native 64-bit and emulated 64-bit versions

**Comment by sungaila** [comment]
@t1m0thyj These are my own tests and CPU benchmarks like [this one](https://browser.geekbench.com/v5/cpu/compare/5375190?baseline=5319407). The x86-64 emulation is much faster for CPU-bound tasks. E.g. I got three times more FPS on OpenRCT2 in software rendering mode.

Photoshop is a bad benchmark as it is mostly GPU-bound, the emulation can improve on CPU instructions only.

I am using my [WDD .NET 6 fork](https://github.com/sungaila/WinDynamicDesktop/releases/tag/v4.6.0-dotnet6) for 3 weeks without issues. Turns out porting to ARM64 is not that easy because some of the NuGet packages are not compiled for AnyCPU/ARM64 or are legacy .NET Framework libs.

**Comment by t1m0thyj** [comment]
Don't plan to release a 64-bit build currently for reasons mentioned above. Waiting to make this switch until I migrate to .NET 6 (https://github.com/t1m0thyj/WinDynamicDesktop/pull/336) - which will likely be when .NET 6 becomes stable and supports WPF natively on ARM64 (https://github.com/t1m0thyj/WinDynamicDesktop/issues/225), or when Visual Studio 2022 is released which no longer bundles .NET 4.
