### ISSUE TITLE
Fix Installer startup

### ISSUE THREAD

**Issue by xmha97** [t1m0thyj/WinDynamicDesktop#338]
I installed this app per machine (%ProgramFiles%)
The installer created a startup for all users!
Please fix the installer.
![image](https://user-images.githubusercontent.com/23485114/121804157-3d26ad80-cc5a-11eb-9237-c550f085f5fb.png)

**Comment by t1m0thyj** [comment]
Hello, which option did you choose on this prompt of the installer?
![image](https://user-images.githubusercontent.com/22344007/121837500-c0b8bc80-cca3-11eb-8c27-42295bf0c6f1.png)

**Comment by xmha97** [comment]
> 
> 
> Hello, which option did you choose on this prompt of the installer?
> ![image](https://user-images.githubusercontent.com/22344007/121837500-c0b8bc80-cca3-11eb-8c27-42295bf0c6f1.png)

Yes, I can install this app per machine (for all users)
but the installer created a startup for all users! (not current user)
Please see the above picture.

**Comment by t1m0thyj** [comment]
To make sure I understand, you selected the first option "Install for me only"? I haven't been able to reproduce this behavior. If you selected the second option, then creating a startup for all users would be expected.

**Comment by xmha97** [comment]
I'm sorry, my English is not very good, but I'm trying to convey what I mean.
The startup should always be made for the current user.
Suppose a computer has 3 users but only two users want to use this app.
In that case, we have to install the app per machine.
Because the startup is for all users, the app also runs for the third user.

**Comment by t1m0thyj** [comment]
Thanks for the explanation, I agree this is undesirable behavior and it will be fixed in the next version of WDD.

**Comment by xmha97** [comment]
> 
> 
> Thanks for the explanation, I agree this is undesirable behavior and it will be fixed in the next version of WDD.

Thank you.

**Comment by t1m0thyj** [comment]
Fixed in v4.7.0

**Comment by xmha97** [comment]
Thanks.
