### ISSUE TITLE
[Possible Bug] Win11 Can only automatically change one desktop's wallpaper

### ISSUE THREAD

**Issue by 7HE-W0R1D** [t1m0thyj/WinDynamicDesktop#342]
- WDD Version: 4.6.0 (UWP)
- OS Version: Dev 21996.1

Steps to Reproduce:

1. Add more than one desktops
2. Select a theme and wait for it to change once (or change to dark mode manually)
3. Only the current desktop's wallpaper switchs, the others' stay the same

Are you using the Microsoft Store version of WDD?: Yes

I'm using the leaked version of win11 and hopefully they fixed that in the public release. I'll update once the official release is available. I tried wallpaper engine and it can change all the desktop's wallpaper as usual, not sure if that helps.

**Comment by t1m0thyj** [comment]
This is not specific to Win11, in Win10 build 21337 the feature was introduced to have different wallpapers across virtual desktops.

I'm investigating a fix for this which is tracked in https://github.com/t1m0thyj/WinDynamicDesktop/issues/321 and https://github.com/Grabacr07/VirtualDesktop/pull/57.
