### ISSUE TITLE
No update of wallpaper after resume from hibernation

### ISSUE THREAD

**Issue by theface78** [t1m0thyj/WinDynamicDesktop#344]
- WDD Version: 4.4-4.6
- OS Version: Windows 10 h121

Steps to Reproduce:

1. Wallpaper is set to one of the night wallpapers, laptop closed to hibernate
2. When starting the laptop again in the morning, the app doesn't realize/check and stays with night wallpaper until I either manually refresh or the next scheduled wallpaper change happens.

Are you using the Microsoft Store version of WDD?: Yes, but tried the one from GitHub too

**Comment by t1m0thyj** [comment]
Do you still experience this issue in the latest version of WDD (5.0.3)?

**Comment by theface78** [comment]
Hey, sorry for the late reply. It seems to work with the latest version and Windows 11. Thanks!

**Comment by theface78** [comment]
Hey @t1m0thyj I have to report, that the behavior is actually still happening. The wallpaper doesn´t get updated after resuming fom hibernation. It works occasionally, but didn´t work lately. Windows 11 version is 22H2, WDD 5.0.3 UWP

**Comment by t1m0thyj** [comment]
This should be fixed in the latest version (WDD v5.1.0). There was an issue related to "theme not updating on displays that were connected when device is sleeping".
