### ISSUE TITLE
It Does Not Support Windows 7 Resolutions (1366x768)

### ISSUE THREAD

**Issue by DreamHasBeenTaken** [t1m0thyj/WinDynamicDesktop#346]
**_WDD Version:  4.6.0
OS Version: Windows 7_**

WinDynamicDesktop is probably the best wallpaper/theme app I have ever seen and experienced. I really liked it! But when I tried this on Windows 7(resolution - 1366x768) with .NET Framework 4.8 it does not really show the complete wallpaper.
You can check the screenshot below - 
![Untitled](https://user-images.githubusercontent.com/77918460/122918402-b7eb7900-d37c-11eb-93b0-6928e8f703a2.png)
As you can see it only shows a part of the wallpaper which does not look nice :(
I would really appreciate it if you could fix this issue or just drop a comment if there is already a fix for this :)
Thanks in advance!
**I AM NOT USING THE MICROSOFT STORE APP. I HAVE DOWNLOADED THIS FROM THE OFFICIAL WinDynamicDesktop GITHUB PAGE**

**Comment by t1m0thyj** [comment]
WDD respects the wallpaper fit settings you set in the Windows Control Panel. To configure the Windows wallpaper settings, see [these instructions](https://www.computerhope.com/issues/ch000592.htm#win7) (skip steps 4-6 which don't apply).

**Comment by Rajbir98** [comment]
lol problem was very dumb
