### ISSUE TITLE
weather

### ISSUE THREAD

**Issue by Socialgiogi** [t1m0thyj/WinDynamicDesktop#35]
What about the possibility to add images for different weather, like snowy, windy, cloudy... using the wheater forecast?
Even if it's not what Apple did could be a sweet add!

Thanks again for the sweet work You did!

**Comment by t1m0thyj** [comment]
This is a neat idea, but currently implementing a major new feature like changing wallpaper based on weather is more than what I've planned to do with this app. It would require connecting to an online weather API to get daily data and a total rewrite of the wallpaper change scheduler code. Maybe someday I'll create a version 2 of the app, which could have fancy features like this and a theme manager.
