### ISSUE TITLE
Automatically switches between the dark and light theme of Windows 10 at scheduled times.

### ISSUE THREAD

**Issue by S-Kee** [t1m0thyj/WinDynamicDesktop#351]
I hope WinDynamicDesktop can automatically switches between the dark and light theme of Windows 10 at scheduled times.

**Comment by t1m0thyj** [comment]
WDD supports this thru PowerShell scripts, see [here](https://github.com/t1m0thyj/WinDynamicDesktop/discussions/350#discussioncomment-945550).
