### ISSUE TITLE
Noisy Wallpaper

### ISSUE THREAD

**Issue by Rajbir98** [t1m0thyj/WinDynamicDesktop#353]
## - Resolution: 1366 x 768 ##

Steps to Reproduce:

1.When I Apply A Theme the Wallpaper Looks Very Noisy
2.But Some Custom Themes Like Dreams Work Fine And I Also Tried To Replace Big Sur Wallpaper With The One Which I Downloaded And That to Works Fine

Are you using the Microsoft Store version of WDD?: No
![image](https://user-images.githubusercontent.com/84771149/124548861-efadf280-de4b-11eb-9f42-d33260e65083.png)

**Comment by Rajbir98** [comment]
ignore the windows icon i have changed it with classic shell dont think it is windows 10 or 8

**Comment by Rajbir98** [comment]
Is there anyone to respond

**Comment by Rajbir98** [comment]
## REply Plzzz ##

**Comment by t1m0thyj** [comment]
> I Also Tried To Replace Big Sur Wallpaper With The One Which I Downloaded And That to Works Fine

Where did you download it? Have you tried downloading and importing the DDW from [here](https://github.com/t1m0thyj/WDD-mac-themes/releases/tag/big-sur)? If not, please do so and let me know if it helps.

Also please don't spam comments, I already get notified when a new issue is created. WDD is FOSS (Free Open-Source Software) without paid support, so there is no obligation for me to respond quickly.

**Comment by Rajbir98** [comment]
i downloaded it from the app
and due to noisiness to fix it i have to download both day night wallpaper and replace with the original one

**Comment by Rajbir98** [comment]
and the pic shown abouve is the one which  i downloaded from wdd

**Comment by t1m0thyj** [comment]
The Big Sur wallpaper that WDD downloads is hosted here: https://github.com/t1m0thyj/WDD-mac-themes/releases/download/big-sur/Big_Sur_Abstract_2.ddw

You can download the file and rename the extension to .zip, then extract the contents to check the image quality for yourself.

Perhaps disabling the Win10 setting that compresses JPEG wallpapers would improve your image quality? See here for how to do it: https://www.windowscentral.com/how-disable-image-compression-desktop-wallpapers-windows-10

**Comment by Rajbir98** [comment]
It doesn't fix it i have tried try fixing the image quality first in your themes

**Comment by t1m0thyj** [comment]
The problem is not in my theme, here's a screenshot of the 1st JPEG:
![image](https://user-images.githubusercontent.com/22344007/125560069-c7cd8627-fa1e-4f22-85e3-7a257a369a5b.png)

**Comment by Rajbir98** [comment]
Then whats the problem is its problem of windows

**Comment by Rajbir98** [comment]
and yes if i view the pic in photos its fine but when i apply the wallpaper
then this problem happens

**Comment by Stackedstudio** [comment]
Try installing Winaero Tweaker and Adjust wallpaper quality to Max.
It may help

**Comment by Rajbir98** [comment]
can u tell me where can i find this option cause I search it but It doesn't;t seem to come up with anything u said.
can u pls tell me in which section it comes under

**Comment by Stackedstudio** [comment]
> can u tell me where can i find this option cause I search it but It doesn't;t seem to come up with anything u said. can u pls tell me in which section it comes under

Section `Desktop and Taskbar` >> Wallpaper Quality. 
Note: This is an App I personally use and not related to WinDynamicDesktop.
