### ISSUE TITLE
WDD v4.7.0 crashed when downloading 'Tree' theme after first-time install

### ISSUE THREAD

**Issue by RussellJQA** [t1m0thyj/WinDynamicDesktop#354]
- WDD Version: 4.7.0
- OS Version: Windows 10 Home, OS build 19043.1083
- Chocolatey Version: v0.10.15
- Chocolatey GUI Version: 0.18.1.0

I'm a long-time, satisfied user on WDD, but encountered this bug when I tried to do a first-time install on a PC whose hard drive I'd recently replaced. Here's what I did:

Steps to Reproduce:

1. Do a first-time install of WDD using Chocolatey GUI
2. Select the "Tree" theme
3. When told "Theme is not downloaded. Click the Download button to enable full preview.", do so

Are you using the Microsoft Store version of WDD?: No

Results:
• An error dialog popped up saying:

> Errors occurred
> See the logfile
> 'C:\Users\rljohnson\AppData\Local\Programs\WinDynamicDesktop\WinDynamicDesktop.exe.log'
> for details
   
• The WinDynamicDesktop "Downloading images for 'Tree'..." dialog which appeared seemed to indicate that all "15.4 MB of 15.MB" had been downloaded.
• But the WinDynamicDesktop icon was not shown in the Windows taskbar notification area, and visually it could be seen that the theme had not yet been applied.

Thankfully, I was able to successfully recover:

Steps (continued); 
3. On the "Processes" tab of Windows Task Manager, select WinDynamicDesktop, right-click, and select "End task" from the context menu
4. In the Windows taskbar's Search box, search for WinDynamicDesktop, and select "Open" from the options presented
5. Right-click on the WinDynamicDesktop icon which appears in the Windows taskbar notification area, and selected "Select Theme"
6. In the WinDynamicDesktop theme chooser, select the "Tree" theme, and click the "Apply" button

I've attached 2 screenshots and the .log file.

![WinDynamicDesktop error dialog](https://user-images.githubusercontent.com/16086475/125079441-9f27d680-e091-11eb-8d92-49cf501559e3.png)

![WinDynamicDesktop download progress indicator](https://user-images.githubusercontent.com/16086475/125079459-a3ec8a80-e091-11eb-82f2-8817ad457c6c.png)

[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/6791373/WinDynamicDesktop.exe.log)

**Comment by t1m0thyj** [comment]
Closing as this issue could not be reproduced and the wallpaper engine has been refactored in WDD v5. If it happens again, please feel free to reopen.
