### ISSUE TITLE
Cancel button on the download theme windows stretch when moved to an other screen.

### ISSUE THREAD

**Issue by sadspear** [t1m0thyj/WinDynamicDesktop#356]
- WDD Version: 4.7.0
- OS Version: Windows 11 21H2 22000.65
- 1st screen dimensions: 1920 x 1080
- 2nd screen dimensions: 1366 x 768

Steps to Reproduce:

1. Download a theme
2. Move the download window on an other screen
3. The cancel button should streth like [this](https://i.imgur.com/Bj2Dj6L.png)

Are you using the Microsoft Store version of WDD?: No

**Comment by t1m0thyj** [comment]
I can't reproduce this issue in the latest version of WDD - also using Windows 11, 1st screen is 3840x2160 and 2nd screen is 1920x1080. Do you still experience this issue and if so, do you know if your screens have different DPI scaling?
