### ISSUE TITLE
Support for dynamic HEIC files

### ISSUE THREAD

**Issue by morgenman** [t1m0thyj/WinDynamicDesktop#357]
Mac OS supports dynamic wallpapers in the format of HEIC. As such, there is a large library of dynamic wallpapers available for it. 
(see: https://dynamicwallpaper.club/ )
If we could support it, or at least have a tool to convert from one to another, we would increase interest in this software, and have a much larger theme base. 
I suggest looking at https://github.com/strukturag/libheif

**Comment by morgenman** [comment]
Oops, I'm a dumbass, https://github.com/gdstewart/ddw-theme-creator exists. 
Highly recommend heic be supported manually, but this is a great start.
If HEIC is not a planned feature, feel free to close this

**Comment by t1m0thyj** [comment]
I'd really like to support importing HEIC files directly in WDD, but unfortunately there are limitations preventing me from making this possible. See https://github.com/t1m0thyj/WinDynamicDesktop/issues/151 for more details.
