### ISSUE TITLE
Feature request: shuffle favourites

### ISSUE THREAD

**Issue by HarryAnkers** [t1m0thyj/WinDynamicDesktop#359]
Would like to use a selection to shuffle. E.g. use only favourites to shuffle daily.

**Comment by yazan1107** [comment]
also me

**Comment by cal4** [comment]
This would be a nice alternative to deleting themes to remove them from the shuffle

**Comment by brdcg** [comment]
Plus one from me. I Would love this Feature too.

**Comment by t1m0thyj** [comment]
Added in WinDD 5.4.0
