### ISSUE TITLE
[Feature Request] More time of the day options

### ISSUE THREAD

**Issue by ccelik97** [t1m0thyj/WinDynamicDesktop#365]
Can we have more than only "sunrise", "day", "sunset", "night" time of the day options?

I know that setting more than 1 image per these four is possible but it picks from those randomly, so ends up refreshing the wallpaper only 4 times per day. I'd like to be able to make it refresh more often by actually having more time of the day options if possible :D Otherwise this app is missing a great potential by being limited to only 4 I think.

(Or in case there's indeed a way (that is compatible with the location api based mode then please let me know it.)

**Comment by t1m0thyj** [comment]
> I know that setting more than 1 image per these four is possible but it picks from those randomly, so ends up refreshing the wallpaper only 4 times per day.

WDD does not pick randomly, it loops through the images in each list sequentially so you can add as many images as you want and they will all be shown. See the example themes here for more details about how wallpaper images are scheduled throughout the day: https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes#theme-file

**Comment by ccelik97** [comment]
Well, at first I thought it should work like that too but ever since I installed it it only picked one random image among each section and showed it only until the next time of the day, hence I'm bringing it here like this :D I didn't change any of the app settings btw, I picked the windows location api in the schedule options and that's it. What am I missing here? (yes the .ddw files I create have more than 1 image per those 4 times of the day, as shown in the example .json file you linked there)

**Comment by ccelik97** [comment]
Ok, I'll close this issue as I reinstalled the app and it's now working properly. I really don't know why it wasn't going in order by what's set in the json file before but now it does and it's not random so I'm done :D
