### ISSUE TITLE
'Start on Boot' got reset after reboot on Windows 11

### ISSUE THREAD

**Issue by andylim-mkj** [t1m0thyj/WinDynamicDesktop#375]
- WDD Version: 4.7
- OS Version: Windows 11 22000.194
- Version used: 4.7.0 Portable

Steps to Reproduce:

1. Set 'Start on Boot' on
2. WDD not started after reboot

Are you using the Microsoft Store version of WDD?: No

Update:
Just tried using the non-portable installer, it works OK though. App started after reboot. But I'd personally prefer to use the portable version as I don't need to re-download/re-import all my downloaded themes.

**Comment by t1m0thyj** [comment]
With the latest version of WDD, the "Start on Boot" setting should work in the portable version on Windows 11.
