### ISSUE TITLE
Monterey wallpapers?

### ISSUE THREAD

**Issue by rwkyyy** [t1m0thyj/WinDynamicDesktop#381]
Hi there, I would like to see the Monterey wallpapers added, thank you in advance!

**Comment by t1m0thyj** [comment]
Apple hasn't created as many wallpapers for Monterey as they did for previous releases. So far they only added an abstract wallpaper which is already included in WDD.

In the future if you find new wallpapers that Apple has bundled with macOS, please include a link in the issue.

**Comment by rwkyyy** [comment]
Oh, I'm sorry, I was expecting the Monterey to be on top of the list, that's why I came here and posted, considering the cronology of the pictures...
