### ISSUE TITLE
I get an error when open WDD

### ISSUE THREAD

**Issue by TechStudent11** [t1m0thyj/WinDynamicDesktop#389]
- WDD Version: I honestly don't know.
- OS Version: Windows 11 Version 21H2 (OS Build 22000.318)

Steps to Reproduce:

1. Start WDD

Are you using the Microsoft Store version of WDD?: No

@t1m0thyj I opened an issue **2 months ago** and I got no reply. See #364.

**Comment by t1m0thyj** [comment]
Sorry for the delay, replied to other issue.
