### ISSUE TITLE
Dark mode UI for choose theme menu

### ISSUE THREAD

**Issue by papa-shrek** [t1m0thyj/WinDynamicDesktop#391]
I find that dark mode UIs look much neater and I find this software to be mostly directed towards the aesthetics of a computer so I think is could look real neat.

I think a nice color could be: #323337, its what google uses

Also t1m0thyj if you see this, thanks so much this program is amazing!

**Comment by t1m0thyj** [comment]
I am also a big fan of dark mode UIs 🙂 

Unfortunately, implementing a toggleable dark mode is not easy to do in a Windows Forms app. Rewriting WDD from the ground up as a UWP app could make the UI a lot nicer, but is also a significant effort so I don't know if I'll ever find the time to do it.

**Comment by t1m0thyj** [comment]
Automatic dark theme is WIP:
![image](https://user-images.githubusercontent.com/22344007/198147712-0d1d9c67-f901-4536-a5cf-7437d8c98db7.png)

**Comment by t1m0thyj** [comment]
Instead of the homespun dark theme in the above screenshot, WDD 5.2.0 now uses Mica to show a dark theme on Windows 11.
