### ISSUE TITLE
Changing lockscreen image after restarting PC?

### ISSUE THREAD

**Issue by yazan1107** [t1m0thyj/WinDynamicDesktop#392]
done

- WDD Version: 4.7.0
- OS Version: 

Steps to Reproduce:

1. restarting PC
2. the computer always shows the same image(and not the lastest theme wallpaper applied) on lock screen!
3. i expect that the image changed per last theme applied, how can i change this?
Are you using the Microsoft Store version of WDD? No

**Comment by t1m0thyj** [comment]
This issue is known and documented here:
https://github.com/t1m0thyj/WDD-scripts/tree/master/experimental#change-lockscreen-image

> ⚠️ Changing the image does not work consistently (see [MSDN](https://social.msdn.microsoft.com/Forums/vstudio/en-US/c5f7e014-a1a1-4d62-b550-7976381d62cd/change-windows-8-lockscreen-image-with-wpfservice-only-works-once?forum=wpf)).
