### ISSUE TITLE
bigsur theme not working, i get black screen instead of wallpaper!!

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WinDynamicDesktop#395]
i am using lastest version of windows 11+ desktop version of windynamicdesktop
bigsur theme not working, i get black screen instead of wallpaper!!
when reloading configuration file it crashes!
also sometimes when reloading configuration file i get this error message:
![image](https://user-images.githubusercontent.com/78726445/144223123-d7416fcf-9541-4347-82e1-f4e52bed4a9d.png)
this also an error message i get, only when using bigsur theme!!
btw i applied decompess wallpaper registry!
this is the log:
> [2021-11-30 09:22:18.818] System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
> at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
> at System.Collections.ObjectModel.ObservableCollection1.OnCollectionChanged(NotifyCollectionChangedEventArgs e) at System.Collections.ObjectModel.ObservableCollection1.ClearItems()
> at System.Collections.ObjectModel.Collection`1.Clear()
> at WinDynamicDesktop.WPF.ThemePreviewerViewModel.Stop()
> at WinDynamicDesktop.ThemeDialog.OnFormClosed(Object sender, FormClosedEventArgs e)
> at System.Windows.Forms.FormClosedEventHandler.Invoke(Object sender, FormClosedEventArgs e)
> at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
> at System.Windows.Forms.Form.RaiseFormClosedOnAppExit()
> at System.Windows.Forms.Application.ExitInternal()
> at System.Windows.Forms.Application.Restart()
> at WinDynamicDesktop.JsonConfig.d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__6_1(Object state)
> at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
> at System.Threading.ThreadPoolWorkQueue.Dispatch()
> at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
> [2021-11-30 09:24:32.451] System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
> at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
> at System.Collections.ObjectModel.ObservableCollection1.OnCollectionChanged(NotifyCollectionChangedEventArgs e) at System.Collections.ObjectModel.ObservableCollection1.ClearItems()
> at System.Collections.ObjectModel.Collection`1.Clear()
> at WinDynamicDesktop.WPF.ThemePreviewerViewModel.Stop()
> at WinDynamicDesktop.ThemeDialog.OnFormClosed(Object sender, FormClosedEventArgs e)
> at System.Windows.Forms.FormClosedEventHandler.Invoke(Object sender, FormClosedEventArgs e)
> at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
> at System.Windows.Forms.Form.RaiseFormClosedOnAppExit()
> at System.Windows.Forms.Application.ExitInternal()
> at System.Windows.Forms.Application.Restart()
> at WinDynamicDesktop.JsonConfig.d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__6_1(Object state)
> at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
> at System.Threading.ThreadPoolWorkQueue.Dispatch()
> at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

 another log: 
> [2021-11-30 10:30:08.436] System.InvalidOperationException: Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application.
> at System.Windows.Forms.MessageBox.ShowCore(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
> at WinDynamicDesktop.AppContext.HandleMultiInstance()
> at WinDynamicDesktop.AppContext..ctor(String[] args)
> at WinDynamicDesktop.Program.Main(String[] args)
> [2021-11-30 10:45:05.776] System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
> at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
> at System.Collections.ObjectModel.ObservableCollection1.OnCollectionChanged(NotifyCollectionChangedEventArgs e) at System.Collections.ObjectModel.ObservableCollection1.ClearItems()
> at System.Collections.ObjectModel.Collection`1.Clear()
> at WinDynamicDesktop.WPF.ThemePreviewerViewModel.Stop()
> at WinDynamicDesktop.ThemeDialog.OnFormClosed(Object sender, FormClosedEventArgs e)
> at System.Windows.Forms.FormClosedEventHandler.Invoke(Object sender, FormClosedEventArgs e)
> at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
> at System.Windows.Forms.Form.RaiseFormClosedOnAppExit()
> at System.Windows.Forms.Application.ExitInternal()
> at System.Windows.Forms.Application.Restart()
> at WinDynamicDesktop.JsonConfig.d__8.MoveNext()
> End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__6_1(Object state)
> at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
> at System.Threading.ThreadPoolWorkQueue.Dispatch()
> at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by yazan1107** [comment]
still the same problem, anyone?

**Comment by t1m0thyj** [comment]
Do you still experience this issue after trying the fix suggested [here](https://github.com/t1m0thyj/WinDynamicDesktop/issues/216#issuecomment-657196199=)?

**Comment by t1m0thyj** [comment]
Closing since OP has deleted their GitHub account.
