### ISSUE TITLE
Bad Quality

### ISSUE THREAD

**Issue by panoreganko** [t1m0thyj/WinDynamicDesktop#396]
- WDD Version: 4.7.0
- OS Version: Windows 11 but also occurs on Windows 10

Issue:
When setting up dynamic wallpaper, it's in great quality no visible pixels. But after some time wallpaper gets worse quality even on simple wallpapers like solar gradients. I tried to convert .jpg wallpaper files to .png but app didnt see that files and i would need to download it again with .jpg. I have 1366x768 monitor so it could be issue but idk
Steps to Reproduce:

1. Just set up dynamic wallpaper
2. Wait (also restarting computer works)

Are you using the Microsoft Store version of WDD?: No

**Comment by Rajbir98** [comment]
yeah i also do have 1366x768 monitor and face the same issue

**Comment by t1m0thyj** [comment]
Closing as duplicate of https://github.com/t1m0thyj/WinDynamicDesktop/issues/353.

If you want to use .JPGs that you have converted to .PNGs, you'd need to edit the `theme.json` file to replace ".jpg" with ".png".
