### ISSUE TITLE
Error message when starting up windows!

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WinDynamicDesktop#399]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/78726445/146128715-51aabd06-161b-4fd3-9ad3-cfc74b143d61.png">

**Comment by t1m0thyj** [comment]
As a temporary workaround, downgrading to v4.6.0 will probably fix the issue but will also mean the wallpaper isn't synced between virtual desktops. I'll look into this issue as soon as I get a chance.

**Comment by t1m0thyj** [comment]
@yazan1107 What is your version of Windows 11? I've tested WDD on the latest Insider Preview build (22523) and am not seeing the error.

**Comment by yazan1107** [comment]
> @yazan1107 What is your version of Windows 11? I've tested WDD on the latest Insider Preview build (22523) and am not seeing the error.

i received it again (i receive this error message sometimes:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/78726445/149918070-52aa1c3d-01c1-4816-b85d-405b422d6deb.png">

windows 11 version 21H2 build 22000.438
