### ISSUE TITLE
Feature request: add weather status

### ISSUE THREAD

**Issue by Sekkei** [t1m0thyj/WinDynamicDesktop#405]
I'm not sure If this project will implement more than whats is possible on mac. But if so I would love to see a wallpaper changing by weather and time.

Atm the theme.json looks like this `"sunriseImageList": [ 1, 2, 3 ],`  I propose to add something like this `"sunriseImageListWeather": [ sunny, rain, snow ],` and as file `"Solar_Gradients_*_*.jpg"` so `Solar_Gradients_3_sunny.jpg`
Or what ever not breaks the backwards compatibility

(maybe add also season ? could also be fun)

*edit
may have a look here for free weather api https://github.com/chubin/wttr.in

**Comment by t1m0thyj** [comment]
Related to #370. Currently there are no plans to implement this in WDD.

**Comment by Sekkei** [comment]
I understand, but I have some thoughts about your doubts: 
> It would require connecting to an online weather API to get daily data

If curl-ing with wttr is to much work for now let the user do the work. You could load a txt where only the current weahter info needs to be. The user can create a pwsh script + a lookup for diiferent api names, to a general format WDD would use (e.g if api delivers 'heavy snow' or 'snow_heavy')

> a total rewrite of the wallpaper change scheduler code

You could just dublicate your scheduler, the original only time based, and any addition scheduler you/user desire. Determing the use of each scheduler with different json args like `"features": "Time_Weather",`
(listening on the txt timestamp for changes and read if so)
