### ISSUE TITLE
Booting with Windows 11

### ISSUE THREAD

**Issue by damianshrinivas** [t1m0thyj/WinDynamicDesktop#409]
So, for me everything works fine except for app autorun. I've added a task in Windows task scheduler to run at startup but I get the error code 0x40010004. (Windows build 22000.469)

**Comment by Sekkei** [comment]
Also on Windows 11 (dev-build) , but it works for me. 
Of course you tried a reinstall ?
Do you have AV software and could you check if it will work with them disabled ?

To run an app on start , adding a task is overkill , just search for autostart folder or registry entry and try it like this

**Comment by damianshrinivas** [comment]
So I reinstalled Microsoft Store version and again, it would not boot. But then I installed exe from the github and everything is working fine again.

**Comment by IgnusG** [comment]
I have the github version and can confirm I never had this problem on it.

**Comment by t1m0thyj** [comment]
This should be fixed since WDD v5. The auto-start function works fine in Windows 11 for me.
