### ISSUE TITLE
Settings not applied when boot up on Windows 11 

### ISSUE THREAD

**Issue by jwdotpark** [t1m0thyj/WinDynamicDesktop#410]
- WDD Version: 4.7.0 (UWP)
- OS Version: Windows 11 22000.469 stable channel

Steps to Reproduce:

1. Since 8th Feb on boot up, default mode sets to solid color, not picture mode based on time. Some parameter on Windows might have changed but I can't be sure what it is. 

Are you using the Microsoft Store version of WDD?: Yes

Thank you for the great software!

**Comment by t1m0thyj** [comment]
Does this issue still happen in the latest version of WDD ([v5.1.0](https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0))?
