### ISSUE TITLE
Theme Submitter Giving Incorrect Negatives

### ISSUE THREAD

**Issue by AnAceCase** [t1m0thyj/WinDynamicDesktop#413]
This issue is too do with the theme submitter for WinDynamicDesktop,

I've summitted Multiple .DDW files all coming back with the result "Rejected due to: .DDW file must contain only theme.json and the Images it references." 

I've gone through the contents .DDW and the .json file multiple times and found no issues.
I'll attach my file in a zip to this report.
[Abstract_Mountains.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/8054150/Abstract_Mountains.zip)

**Comment by t1m0thyj** [comment]
To make your theme pass the criteria, your JSON file inside the DDW should be renamed from "Abstract_Mountains.json" to "theme.json".

The name of the JSON file in the DDW doesn't actually matter for WDD to import it successfully, so I'll fix the theme submitter to make it less strict.

**Comment by t1m0thyj** [comment]
I've updated the theme submitter but now it's failing because in your theme.json the `*` is missing on the following line:
```  "imageFilename":"Abstract_Landscape_*.jpg",```

**Comment by t1m0thyj** [comment]
Closing since the original issue was fixed.
