### ISSUE TITLE
Location Error - Invalid Location No Matter What

### ISSUE THREAD

**Issue by Tyree** [t1m0thyj/WinDynamicDesktop#414]
- WDD Version: 4.7.0
- OS Version: 21H2 (19044.1526)

Steps to Reproduce:

1. Start the software
2. Enter and city state combo, even the one suggested
3. Error saying location is invalid

Yes, I am connect to the internet.

Are you using the Microsoft Store version of WDD?: No

**Comment by t1m0thyj** [comment]
This should be working now, sorry for the inconvenience. WDD experienced a high volume of users over the weekend which exceeded the daily quota of the geocoding API it uses. This is the first time this has happened, if it happens repeatedly I'll need to look into switching to a different API or paying for a higher tier.

**Comment by Tyree** [comment]
No worries! Thanks for the reply. I ended up enabling Location Services in Windows and got it going with that method.

Maybe start charging a buck for the Windows Store version? :-)

**Comment by t1m0thyj** [comment]
Version 5 makes using Windows location the default option when Location Services are enabled. This should reduce the number of requests to the geocoding API, and WDD has not come close to exceeding the quota recently, so closing this for now.
