### ISSUE TITLE
Overwriting default Windows 10 settings

### ISSUE THREAD

**Issue by maticboncina** [t1m0thyj/WinDynamicDesktop#415]
- WDD Version: 4.7.0
- OS Version: Windows 10

Steps to Reproduce:

1. Configure any night changing background.
2. You will see that during the day your OS LEVEL theme gets set to white and during sunset and until the next morning it gets set back to dark (or however is set in the .json config file (eg sunrise at 7:00 and sunset at 19:00).

There should be a way to disable this from happening as it doesn't happen on the old versions. Let's say always keep dark mode enabled. This is the setting that is being changed to white:

![rOAwJ](https://user-images.githubusercontent.com/54638868/154816640-647ec654-9526-45c0-8c8b-2d0eb400a7fb.png)

Are you using the Microsoft Store version of WDD?: Yes

**Comment by t1m0thyj** [comment]
WDD does not change the app mode color setting unless the [Change Windows App Theme](https://github.com/t1m0thyj/WDD-scripts/tree/master/stable#change-windows-app-theme) script is installed.
