### ISSUE TITLE
[FEATURE REQUEST] show geographical location(city,country) for landscape themes

### ISSUE THREAD

**Issue by yazan1107** [t1m0thyj/WinDynamicDesktop#419]
done

maybe show it as on one of the corners, or when hovering over windynamicdesktop app in overflow thing shows the location of the photo taken(for example geneve,switzerland)

**Comment by t1m0thyj** [comment]
It's up to theme creators whether or not they want to include the photo location in the title. Many of them already do (e.g., Licancabur or Monument Valley).
