### ISSUE TITLE
Can not automatically change the wallpaper on Windows11 beta

### ISSUE THREAD

**Issue by KarsonShi** [t1m0thyj/WinDynamicDesktop#423]
- WDD Version:5.0.1
- OS Version:22581.200

Main Problem: The app **sometime** can not change the wallpaper, it need refresh it manually.
But sometimes it works fine. I don't know why.

Another problem: seems that the script which used to change the Windows system theme doesn't work anymore. So how can let the windows theme automatically change into dark mode after sunset, and change back to light mode after sunrise?

Are you using the Microsoft Store version of WDD?: No

**Comment by bobshinkman** [comment]
Can confirm, same issue on the latest beta

**Comment by smxko** [comment]
Same on WDD 5.0.1 and Windows 22000.593

**Comment by t1m0thyj** [comment]
Are you using WDD to show different wallpapers on multiple monitors or just one across all of them? And do you have the "Change Lockscreen Image" setting enabled?

**Comment by smxko** [comment]
> Are you using WDD to show different wallpapers on multiple monitors or just one across all of them? And do you have the "Change Lockscreen Image" setting enabled?

Speaking for myself, I use the same wallpaper on every monitor. "Change lockscreen Image" is disabled.

**Comment by lorenzobilli** [comment]
I have the same issue. Both WDD 5.0.0 (Store version) and WDD 5.0.1 (Store version) sometimes fails to switch the wallpaper even in the stable W11 build (22000.593), the only way(s) to refresh them is either by restarting WDD or by manually refreshing the wallpaper. The issue occurs regardless of "Change Lockscreen Image" setting (I've tested both). I use the same wallpaper on every monitor.

**Comment by Skywings96** [comment]
I also have the same problem on windows 11 bulid 22000.593.

**Comment by carlosvsilva** [comment]
I'm also unable to change all 3 desktop wallpapers at once via latest Store version. 
I'm on a brand new clean install of a Win11 22H2 22621.169 (Release Preview) full up to date. 

I'm attaching a short list of operations performed by Windows System Settings (recorded using a small reliable tool from Microsoft: Sysinternals Process Monitor), when applying a wallpaper to all desktops. It should be necessary for WinDynamicDesktop to perform the same operation calls.
To find the relevant calls i recommend using the highlight to highlight Paths containing the word jpg, and later Details containing jpg. Not at the same time, the tool performs an AND, not OR. Thanks.

[ChangeAllDesktopsWallpaper.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/9124259/ChangeAllDesktopsWallpaper.zip)

**Comment by 840922704** [comment]
OS Version:22621.232
Same problem. It seems that it can only change wallpaper on one virtual monitor unless by pressing 'Refresh Wallpaper' manually.

**Comment by t1m0thyj** [comment]
Does this issue still happen in the latest version of WDD ([v5.1.0](https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0))?

**Comment by lorenzobilli** [comment]
Been using v5.1.0 for about a day, the problem seems finally fixed for me!
