### ISSUE TITLE
See logfile, Array Out Of Bounds Exception.

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [t1m0thyj/WinDynamicDesktop#428]
- WDD Version: Started from 5.0.0, Still occuring in 5.0.1 (MS Store Latest)
- OS Version: [Version 10.0.19043.1586]

Steps to Reproduce:

1. Launch WinDynamicDesktop on startup
2. Error

Are you using the Microsoft Store version of WDD?: Yes/No
Yes

Other Information:
This happened at around update 5.0.0. Could this be an issue with the number of screens since i've recently had a new screen (3rd one)to work with WinDynamicDesktop

Error Log:
[WinDynamicDesktop.dll.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/8458179/WinDynamicDesktop.dll.log)
?

**Comment by ENTPRESTIGIOUS** [comment]
UPDATE: Just disabled my 3rd screen, now it launches without problems! So must be screen amount incompatibility!

**Comment by t1m0thyj** [comment]
Hello, could you please try a test build from here to see if resolves the issue? https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/2400167665

To download/install a test build, scroll down to the Artifacts section of the linked page and download the EXE for your platform. Then run WDD using the downloaded EXE (you can copy it to the folder where WDD is installed, see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) if unsure where that is).

**Comment by t1m0thyj** [comment]
This should be fixed in 5.3.0.
