### ISSUE TITLE
Doesn't work on windows11

### ISSUE THREAD

**Issue by taoBo1999** [t1m0thyj/WinDynamicDesktop#433]
After updating WinDynamic and Windows a few days ago, the wallpaper can be changed at first, but it will fail after about 5 hours.

Windows 11 Professional Edition 21H2 22000.613

**Comment by Toma62299781** [comment]
I meet this issue too, my system version is also Windows 11 Professional Edition 21H2 22000.613.

**Comment by Skywings96** [comment]
> I changed to version 4.7, and now I can successfully update the wallpaper
> 
> > I meet this issue too; my system version is also Windows 11 Professional Edition 21H2 22000.613.

I also have the same issue, and the same windows version as yours, and V4.7 also works very well for me.

**Comment by Toma62299781** [comment]
> 

Thanks for your information, I will downgrade to version 4.7 and give it a try.

**Comment by taoBo1999** [comment]
> > I changed to version 4.7, and now I can successfully update the wallpaper
> > > I meet this issue too; my system version is also Windows 11 Professional Edition 21H2 22000.613.
> 
> I also have the same issue, and the same windows version as yours, and V4.7 also works very well for me.
