### ISSUE TITLE
[Bug] Powershell addon error after latest Windows 11 Update

### ISSUE THREAD

**Issue by wkdk** [t1m0thyj/WinDynamicDesktop#439]
- WDD Version: 5.0.1 UWP (latest update)
- OS Version: Window 11 Build 22000.675

Steps to Reproduce:

1. On startup: "mscoree.dll missing"
2. Click "OK", another pop-up appears: "PowerShell.exe error"

It occurs after Windows 11 05 (May) Cumulative Update KB5013943 (aka OS Build 22000.675)

Are you using the Microsoft Store version of WDD?: Yes

**Comment by wkdk** [comment]
### I fixed the issue by enabling **_[-] .NET Framework 3.5 (includes 2.0 and 3.0)_** in **_Windows Features_**

_**It was disabled by default.**_

**Comment by t1m0thyj** [comment]
Which PowerShell scripts were you using? I'm wondering if this affects all scripts, or only specific ones.

**Comment by wkdk** [comment]
> Which PowerShell scripts were you using? I'm wondering if this affects all scripts, or only specific ones.

powershell.exe error pop-ups were occuring for all scripts I'm using, which are ChangeDisplayBrightness, ChangeWindowsAppTheme and ChangeWindowsSystemTheme.

I think it's about latest W11 cumulative update which drops .NET Framework 3.5 support automatically. When I enabled .NET framework 3.5 option in Windows Features, problem solved.

**Comment by anthonydouwes** [comment]
Ditto, thanks for the fix!!

Also started happening after latest W11 update.
This not only affects PowerShell, a bunch of other apps also bring up the same error.
