### ISSUE TITLE
Background still not updating on enabling night mode

### ISSUE THREAD

**Issue by oGrqpez** [t1m0thyj/WinDynamicDesktop#440]
The wallpaper is not updating when enabling night mode and has to be done manually. I have restarted my computer and explorer.exe multiple times and still does not work. 
- WDD Version: 5.0.1
- OS Version: Win 10 Pro

Are you using the Microsoft Store version of WDD?: Yes

**Comment by wkdk** [comment]
Could you please check ".NET Framework 3.5 (includes 2.0 and 3.0)" option is enabled?
If not, enable it and restart the PC.

**Comment by oGrqpez** [comment]
Yes it is fully checked

**Comment by oGrqpez** [comment]
Is there something else I need to install or?

Also wanna mention I'm using Optimizer

**Comment by wkdk** [comment]
> Is there something else I need to install or?
> 
> Also wanna mention I'm using Optimizer

I think optimizer program causes it.

**Comment by t1m0thyj** [comment]
Related to #425, this is a bug in WDD and I plan to release an update that fixes it soon.

**Comment by t1m0thyj** [comment]
This should be fixed in 5.0.2.
