### ISSUE TITLE
[FEATURE REQUEST] Location based theme selection

### ISSUE THREAD

**Issue by wkdk** [t1m0thyj/WinDynamicDesktop#441]
Is it possible for you to make a feature which we can use different themes on different locations?
For example I wanna use Big Sur on my home, but Mojave on my work.

Location coordiantes can be 100 meters (etc.) diameter in order to apply theme.

Also "Home mode" and "Work mode" can be added to the menu for users who don't use location services.

Warmest regards.

**Comment by t1m0thyj** [comment]
This is a cool idea but I don't have plans to implement it in WDD.

I'm working on an update that will allow you to set separate wallpapers on each virtual desktop (as requested in https://github.com/t1m0thyj/WinDynamicDesktop/issues/398). This would allow you to have separate virtual desktops for "Home mode" and "Work mode" each with their own wallpaper.

**Comment by wkdk** [comment]
> This is a cool idea but I don't have plans to implement it in WDD.
> 
> I'm working on an update that will allow you to set separate wallpapers on each virtual desktop (as requested in #398). This would allow you to have separate virtual desktops for "Home mode" and "Work mode" each with their own wallpaper.

I'm not an enthusiastic fan of separate desktops really, nevertheless that idea would work the same way 👍 
Still, I would like to have that location-based theme change feature (:
