### ISSUE TITLE
3-segment wallpapers doesn't seem to work

### ISSUE THREAD

**Issue by t1m0thyj** [t1m0thyj/WinDynamicDesktop#442]
### Discussed in https://github.com/t1m0thyj/WinDynamicDesktop/discussions/429

<div type='discussions-op-text'>

<sup>Originally posted by **ilverogattuso** April 11, 2022</sup>
I am quite fond of this app, which is why I decided to give it a try and make my own custom themes, that's when I spotted what I think is an error, which is triggered when in the .json you only include 3 out of the 4 Image Lists (in my case I included all and omitted sunrise), afterwards, when selecting the theme from the app, an error will pop-up, so when checking the log it mostly says:

System.IndexOutOfRangeException: Index was outside the bounds of the array.

The current workaround is to include all 4 phases and repeat one image number in the .json, I tried this with sunset and sunrise as well as sunrise and day, and that way it works just fine!
Just wanted to know if this happens to anyone else.
Anyways love your work sir and thanks in advance!</div>

**Comment by wkdk** [comment]
I just ignore the pop-up, then click "Apply". Theme is being applied and working without any issue.

For example this: [LoFiGirl](https://www.mediafire.com/file/axomv90yz203l1a/LoFiGirl.ddw/file) theme

**Comment by watchmakerful** [comment]
Confirmed also with the "Adwaita" theme containing day, night and sunset, but no sunrise. The easiest way to avoid this error is to add the missing phase (e. g. sunrise) with the same image number as the opposite phase.

**Comment by t1m0thyj** [comment]
> The easiest way to avoid this error is to add the missing phase (e. g. sunrise) with the same image number as the opposite phase.

Supporting 3-segment wallpapers is a valid enhancement request but low priority IMO since this workaround exists. If you want to raise more attention to it, please comment or upvote on this issue.

**Comment by t1m0thyj** [comment]
Added support for 3-segment themes like Adwaita in v5.3.0
