### ISSUE TITLE
wallpaper needs to be manually refreshed(Sometimes wallpapers does not switch neither the power shell scripts)!

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WinDynamicDesktop#448]
- WDD Version:
- OS Version:

Steps to Reproduce:

1.
2.

Are you using the Microsoft Store version of WDD?: Yes/No

**Comment by t1m0thyj** [comment]
Does this issue still happen in the latest version of WDD ([v5.1.0](https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0))?
