### ISSUE TITLE
Cannot install on Windows 22621.160

### ISSUE THREAD

**Issue by AvMavs** [t1m0thyj/WinDynamicDesktop#452]
- WDD Version: 5.0.3 
- OS Version: Windows 22H2 22621.160

Steps to Reproduce:

1. Download the Setup .EXE (AMD64)
2. Install

Are you using the Microsoft Store version of WDD?: No

![image](https://user-images.githubusercontent.com/82929505/173622746-6ee8e0f5-356e-44fa-b10f-2d6758b90e6d.png)

**Comment by SaiyajinK** [comment]
works perfectly on my side on ni_release 22h2 (github version) 👍 :

![vmware_vOsK12Zdqt](https://user-images.githubusercontent.com/105972098/176401564-179e76e6-3f88-446d-b298-51492eb93dcb.png)

Why are you installing the arm64 version? is there a specific feature on your pc that asks you to select this package?
Use the x64 version instead !

- [Portable x64](https://github.com/t1m0thyj/WinDynamicDesktop/releases/download/v5.0.3/WinDynamicDesktop_5.0.3_x64_Portable.exe)
- [x64](https://github.com/t1m0thyj/WinDynamicDesktop/releases/download/v5.0.3/WinDynamicDesktop_5.0.3_x64_Setup.exe)

there's no reason it shouldn't work for you

**Comment by t1m0thyj** [comment]
Does this issue still happen in the latest version of WDD ([v5.1.0](https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0))?

**Comment by AvMavs** [comment]
> 

No, it's fixed now. Thank you so much!
