### ISSUE TITLE
[Request] Able to shuffle daily themes from online

### ISSUE THREAD

**Issue by leodoi3** [t1m0thyj/WinDynamicDesktop#453]
Right now, the way how "shuffle theme daily" works, is you need to have themes downloaded beforehand, and it only shuffles with those that are downloaded locally. 
But I would like it also to automatically download new themes and apply them. Then the next day when a new theme is applied, you can delete my old theme.  This theme can also coincide with the current season and holidays. 
So basically, I want kind of how Windows Spotlight works , but I also want them to be dynamic.

**Comment by t1m0thyj** [comment]
This is a neat idea but picking a new theme daily and having the app automatically download a new theme for each day isn't a feature planned for WDD.
