### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by jptrx** [t1m0thyj/WinDynamicDesktop#457]
- WDD Version: 5.0.3.0
- OS Version: Windows 11 (OS Build: 22000.739)

Steps to Reproduce:

Nothing to reproduce really. When WDD is trying to start a following error message is shown (see files attached)

Are you using the Microsoft Store version of WDD?: Yes/No

Yes

![wdd_error](https://user-images.githubusercontent.com/108369714/176284923-7c3ef021-b536-4c31-8cf9-8cf68845f034.png)
[WinDynamicDesktop.dll.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/9004776/WinDynamicDesktop.dll.log)

**Comment by 2d78** [comment]
The same problem.

[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/9078999/WinDynamicDesktop.exe.log)

**Comment by t1m0thyj** [comment]
I believe I may have fixed this issue, could you try a dev build from here? https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/2573755334

If you scroll to the bottom of the page, there are artifacts and you can download an EXE for your platform.

**Comment by thushanperera95** [comment]
> I believe I may have fixed this issue, could you try a dev build from here? https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/2573755334
> 
> If you scroll to the bottom of the page, there are artifacts and you can download an EXE for your platform.

No luck, I'm still getting the same issue with this build.
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/9238737/WinDynamicDesktop.exe.log)

**Comment by t1m0thyj** [comment]
What were you doing with WDD when the error happened? Were you opening the Select Theme dialog and did you have the Ventura theme selected? Asking because I found another bug related to that scenario.

**Comment by thushanperera95** [comment]
Yep, opening the Select Theme dialog after going through the set location setup.
It's a fresh install - so I don't have any themes selected.

**Comment by juuwong** [comment]
Encountering a similar issue on WDD 5.x including Microsoft Store version. 
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.21996 N/A Build 21996
[debug.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/9333054/debug.log)
[WinDynamicDesktop_5.0.0_x64_Portable.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/9333055/WinDynamicDesktop_5.0.0_x64_Portable.exe.log)

Last stable version is 4.7.0

**Comment by carlosvsilva** [comment]
I also got a crash happening to me that only started after latest Windows Update KB5016695 and KB5016591, that updated Win 11 22H2 and .NET 3/4, to Windows version 10.0.22621.457 (Release Preview), maybe the final build for public worldwide release of Win 11 22H2 next month.

[2022-08-23 19:32:11.514] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WinDynamicDesktop.WallpaperEngine.RunScheduler(Boolean forceImageUpdate)
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

Happens with or without scripts installed. No theme active. Windows Store latest version 5.0.3.0


[WinDynamicDesktop.dll.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/9410450/WinDynamicDesktop.dll.log)
[debug.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/9410451/debug.log)

**Comment by carlosvsilva** [comment]
I workedaround my startup crash by setting an active theme in AppData\Packages\WinDynamicDesktop\LocalState\settings.json:

  "activeThemes": [
    "Windows_11"
  ],

before it was null. So the code using this array should expect null value in it.

**Comment by t1m0thyj** [comment]
This should be fixed in [v5.1.0](https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0).
