### ISSUE TITLE
System service for sync login theme (light/dark)

### ISSUE THREAD

**Issue by iamdtms** [t1m0thyj/WinDynamicDesktop#459]
I'm quite sure it is not exists at all.

System service needed for sync login theme after boot, before app runs at startup after successful login, it is too late.
It is a real issue for me, hope can be solved. AutoDarkMode & WinDynamicDesktop worth a lot together, some little issues has to be fixed for instant success! Thank you.

**Comment by t1m0thyj** [comment]
Please try installing the startup task from here: https://github.com/t1m0thyj/WDD-scripts/tree/master/standalone

It should launch WDD earlier before you log on.

**Comment by iamdtms** [comment]
Thank you, I have just installed.
