### ISSUE TITLE
Wallpaper Changes to random pics out of my pictures Folder, even after deleting the app. 

### ISSUE THREAD

**Issue by MrLLL16** [t1m0thyj/WinDynamicDesktop#462]
I have downloaded the App from the Microsoft store and had a custom Wallpaper, which had 3 Pictures in it. I wanted to change it back to static one, so i closed the App and removed it out of autostart. After I changed the Wallpaper, my other one from the App started appearing again, so i deleted the App. But after that the Wallpaper still changed. So i deleted the .json file with the pictures. Now my Background is always getting overwritten by .jpeg files out of my pictures library. 
I also tried reinstalling the app, but it still gets overwritten by the first Wallpaper/the .json file. 

I dont have an app Version anymore. 

Steps to Reproduce:

1. make own .json file with pictures in it 
2. select a picture through Windows 
3. delete the app

Are you using the Microsoft Store version of WDD?: Yes

**Comment by t1m0thyj** [comment]
Have you switched the wallpaper back to a single "Picture" in the Windows 10 settings?
![image](https://user-images.githubusercontent.com/22344007/178391151-1fc21f90-f53b-47a4-9e10-bf713d1b6c10.png)

If it is set to "Slideshow", Windows will still switch between multiple images without WDD.

**Comment by MrLLL16** [comment]
Its set on a single picture. And when its changing to a random Picture its also set on a single picture in the settings.
