### ISSUE TITLE
Theme selector availability when hiding tray icon

### ISSUE THREAD

**Issue by Vortikai** [t1m0thyj/WinDynamicDesktop#464]
Currently, the default behavior is that the theme selector application is not accessible when hiding the tray icon. I request that it be made available as the default behavior for clicking on WinDynamicDesktop in the Start Menu. If one tries to do so presently, the default "application is already running" is given.

**Comment by ssmmtt** [comment]
second a motion

**Comment by t1m0thyj** [comment]
Good idea 🙂 This enhancement has been made in [v5.1.0](https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0).
