### ISSUE TITLE
Getting error even after reinstalling (GitHub install and Windows Store install attempted)

### ISSUE THREAD

**Issue by lianemusic** [t1m0thyj/WinDynamicDesktop#465]
- WDD Version: 5.0.3
- OS Version: Windows 10

Steps to Reproduce:

1. Reinstall app
2. Open app

Are you using the Microsoft Store version of WDD?: **Yes**/No

![image](https://user-images.githubusercontent.com/72551531/179185221-b7215bd6-cd14-43d3-afb2-5f5189e1018c.png)

This was after reinstalling (tried both the .exe and the Microsoft Store versions), and also happens every time when I try to apply any theme. The reinstalls were prompted by a previous error, that appeared when opening the app, that said:

System.IndexOutOfRangeException: Index was outside the bounds of the array.

Every time I opened the app, all the themes were gone, had to redownload them and re-import them. It's also happening again now.

**Comment by t1m0thyj** [comment]
I believe I may have fixed this issue, could you try a dev build from here? https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/2573755334

If you scroll to the bottom of the page, there are artifacts and you can download an EXE for your platform.

**Comment by t1m0thyj** [comment]
The `IndexOutOfRangeException` should be fixed in [v5.1.0](https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0).
