### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by ProGamer01234** [t1m0thyj/WinDynamicDesktop#469]
I have 3 desktops (Pic)
and i WinDynamicDesktop only refreshes on the desktop im on currently 
and i have to manually refresh the other 2

![Screenshot (18)](https://user-images.githubusercontent.com/76862883/184851489-13ca2a3c-e53b-4509-a628-c973fa43e923.png)

**Comment by carlosvsilva** [comment]
It's a Microsoft Windows 11 22H2 reported bug, you can upvote this bug here to help acknowledge it, at Feedback Hub:

https://aka.ms/AAhmoj9

**Comment by LuckieCrab** [comment]
I have the same issue, hope the devs are able to fix this.

**Comment by t1m0thyj** [comment]
I don't think this is a Windows bug, they seem to have purposely designed the wallpaper API to only update the current virtual desktop. This behavior should be fixed in [v5.1.0](https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0) if you install the script mentioned below:
> This version removes syncing wallpaper across virtual desktops in Windows 11 which used an experimental API that is too unstable to support. If you still want this functionality, install the [Sync Virtual Desktops](https://github.com/t1m0thyj/WDD-scripts/tree/master/experimental#synchronize-virtual-desktops) script.

**Comment by carlosvsilva** [comment]
I just solved it with a powershell script to customize each desktop individual wallpaper after installing that Virtual Desktop powershell extension:

param (
    [Parameter(Mandatory=$true)][int]$daySegment2,  # 0 = Day, 1 = Night
    [Parameter(Mandatory=$true)][int]$daySegment4,  # -1 = N/A, 0 = Sunrise, 1 = Day, 2 = Sunset, 3 = Night
    [Parameter(Mandatory=$false)][string]$imagePath, # Path to current wallpaper image
    [Parameter(Mandatory=$true)][bool]$nightMode    # True if night mode is enabled
)

switch ($daySegment2)
{
	0 { Set-DesktopWallpaper -Desktop Play -Path C:\Users\Carlos\OneDrive\Imagens\Wallpapers\Relax\Dia\green-park.jpg
		Set-DesktopWallpaper -Desktop Work -Path C:\Users\Carlos\OneDrive\Imagens\Wallpapers\Work\AnalogTypewriter.jpg
		Set-DesktopWallpaper -Desktop Organize -Path "C:\Users\Carlos\OneDrive\Imagens\Wallpapers\Windows\Windows 11 SE.png"
		Break }
    1 { Set-DesktopWallpaper -Desktop Play -Path C:\Users\Carlos\OneDrive\Imagens\Wallpapers\Relax\Noite\hammock-simple.jpg
		Set-DesktopWallpaper -Desktop Work -Path C:\Users\Carlos\OneDrive\Imagens\Wallpapers\Work\san-fran-night-bridge.jpg
		Set-DesktopWallpaper -Desktop Organize -Path C:\Users\Carlos\OneDrive\Imagens\Wallpapers\Windows\blur-galaxy.jpg
		Break }
}


In every script I had to change the following parameter to NOT mandatory, otherwise it fails to run in WDD 5.1.0:

 [Parameter(Mandatory=$false)][string]$imagePath, # Path to current wallpaper image
