### ISSUE TITLE
Error when opening windynamicdesktop

### ISSUE THREAD

**Issue by familypc123** [t1m0thyj/WinDynamicDesktop#473]
- WDD Version: i cant open the windynamicdesktop but i reinstalled to the 5.1.0
- OS Version:  Windows 10 pro 21H2
Steps to Reproduce:

1. open windynamic desktop on windows 10 pro 21H2 
2. receive this error:
object reference not set to an instance on an object.
![image](https://user-images.githubusercontent.com/110026469/187623830-491e2a63-de60-4aaf-a69a-20d7a0ec8148.png)

Are you using the Microsoft Store version of WDD?: No

**Comment by t1m0thyj** [comment]
Could you attach the contents of the settings.conf or settings.json file in the same folder as the log file? Feel free to redact location info from them.

To work around the issue, you can delete the settings file to reset WDD settings and relaunch WDD.

**Comment by familypc123** [comment]
where is this file located?

**Comment by familypc123** [comment]
there is no folder windynamicdesktop where the app is saying that there is.

**Comment by t1m0thyj** [comment]
See the steps here to find the location where WDD is installed: https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed

**Comment by familypc123** [comment]
> See the steps here to find the location where WDD is installed: https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed

followed this did not find any folder that has this name in localapp %LOCALAPPDATA%\Programs

**Comment by Jaxsss** [comment]
I have the same issue "Index was outside the bounds of the array."

WDD version: 5.1.0
From Microsoft Store: No

I tried the steps you mentioned but did not help, I also tried to insert ["Windows_10"] into activeTheme key as someone has suggested, didn't help too.

Happened right after choosing timezone. When I try to select another theme, this error pops up and there is only Windows theme named as "None". 

My current Windows version is - 21H2, build 19044.2006

Config file looks like this: 
`{
  "locationMode": 1,
  "location": null,
  "latitude": null,
  "longitude": null,
  "sunriseTime": null,
  "sunsetTime": null,
  "sunriseSunsetDuration": 0,
  "activeThemes": null,
  "darkMode": false,
  "changeLockScreen": false,
  "enableShuffle": false,
  "lastShuffleDate": null,
  "shuffleHistory": null,
  "favoriteThemes": null,
  "language": "en",
  "autoUpdateCheck": true,
  "lastUpdateCheckTime": "09/17/2022 19:24:11",
  "hideTrayIcon": false,
  "fullScreenPause": false,
  "enableScripts": false,
  "debugLogging": false
}`

Error:
`[2022-09-17 17:24:12.735] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WinDynamicDesktop.ThemeDialog.<>c__DisplayClass7_0.<GetDisplayNames>b__4(KeyValuePair`2 x)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.LazyToArray()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
   at WinDynamicDesktop.ThemeDialog.GetDisplayNames()
   at WinDynamicDesktop.ThemeDialog.ThemeDialog_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)`

**Comment by t1m0thyj** [comment]
@Jaxsss Since the error message mentions `GetDisplayNames`, this error seems related to the number of displays you have connected. How many screens/monitors do you have?

**Comment by Jaxsss** [comment]
I have 3 monitors. All of them are detected in Windows Settings and also in NVIDIA Control Panel, I do have all three of them connected to graphics card.

**Comment by t1m0thyj** [comment]
Closing since the original issue has gone stale and the other issue (IndexOutOfRangeException) is tracked in #498
