### ISSUE TITLE
mutiple desktop stucking different state of wallpaper

### ISSUE THREAD

**Issue by iamdtms** [t1m0thyj/WinDynamicDesktop#475]
I'm thinking about preload theme by app start, this may solve title mentioned issue. Thank you.

**Comment by t1m0thyj** [comment]
Since WDD v5.1.0 the feature to sync virtual desktops must be installed separately as a script:
> Note: This version removes syncing wallpaper across virtual desktops in Windows 11 which used an experimental API that is too unstable to support. If you still want this functionality, install the [Sync Virtual Desktops](https://github.com/t1m0thyj/WDD-scripts/tree/master/experimental#synchronize-virtual-desktops) script.

**Comment by iamdtms** [comment]
I'm still looking forward to have an automated official solution for this. Are there any ideas?

**Comment by iamdtms** [comment]
Theme.apply() after theme change may solve it, because I only need to apply the current theme (the current state) after sunset/sunrise happens.

**Comment by t1m0thyj** [comment]
Not sure I understand what issue is being reported here. Is the problem that "More Options -> Refresh Wallpaper" doesn't refresh the wallpaper across all desktops, but only on the active one?

**Comment by Alllexey123** [comment]
And there is such a problem, too. The thing is that if there are multiple virtual desktops (in my case in Windows 11), the wallpaper only changes on the active one until you click "Refresh wallpaper" on each one.

**Comment by Alllexey123** [comment]
I recorded a short video about the problem: https://youtu.be/U7iA47oyAg0

**Comment by t1m0thyj** [comment]
@Alllexey123 Do you have the [Sync Virtual Desktops](https://github.com/t1m0thyj/WDD-scripts/tree/master/experimental#synchronize-virtual-desktops) script installed and enabled in WDD? It should change the wallpaper across all virtual desktops at once.

**Comment by Alllexey123** [comment]
I installed this script and now everything works as it should. Thanks! I think it would be better if it could be set through the menu.

**Comment by t1m0thyj** [comment]
> I installed this script and now everything works as it should. I think it would be better if it could be set through the menu. Thanks!

I would like to add this an option directly in the app, but am first waiting for Microsoft to make a stable API for updating wallpaper on virtual desktops. The current API breaks frequently in new Insider releases and requires painful reverse engineering of COM objects to find out how it has changed (see https://github.com/MScholtes/PSVirtualDesktop/issues/27).
