### ISSUE TITLE
lockscreen wallpaper is not changing on windows 11 22h2

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WinDynamicDesktop#483]
- WDD Version: 5.1.0
- OS Version: windows 11 22H2

Steps to Reproduce:

1. enable change lockscreen wallpaper
2. lockscreen wallpaper is not changing.

Are you using the Microsoft Store version of WDD?: Yes

**Comment by t1m0thyj** [comment]
Closing since user deleted their account and no one else has reported this.

**Comment by zararashigal** [comment]
Same problem here, fix it.

**Comment by t1m0thyj** [comment]
@zararashigal This issue is now being tracked in #548. I can't fix the issue until I can reproduce it. To help diagnose the issue, could you gather logs by following the steps in https://github.com/t1m0thyj/WinDynamicDesktop/issues/548#issuecomment-2119083815?
