### ISSUE TITLE
Different theme for different virtual desktop?

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WinDynamicDesktop#488]
Hey,
Different theme for different virtual desktop? I have work virtual desktop + leisure virtual desktop I need a visual indicator to notice which one is which, can you make a different theme for different virtual desktop?

**Comment by lyc0526** [comment]
Same issue for me

**Comment by t1m0thyj** [comment]
Closing as duplicate of #398. Please upvote that issue if you want to see this feature.
