### ISSUE TITLE
App error ,reinstalling too many times but still no result

### ISSUE THREAD

**Issue by damntruck** [t1m0thyj/WinDynamicDesktop#498]
- WDD Version: 5.1.0
- OS Version: 22H2 Windows 10 pro

Are you using the Microsoft Store version of WDD?: No
![Screenshot_85](https://user-images.githubusercontent.com/31514473/210130541-abe0f299-1a91-489b-84a4-eae52e02d360.png)
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/10327077/WinDynamicDesktop.exe.log)

**Comment by damntruck** [comment]
already install on C & download portable but same result

**Comment by t1m0thyj** [comment]
@damntruck Thanks for reporting this, could you try downloading the EXE from the latest build and let me know if it works?
https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/3825559469

**Comment by t1m0thyj** [comment]
This should be fixed in WDD 5.2.0, which was just published to GitHub and will be available on the Microsoft Store soon.
