### ISSUE TITLE
This App Can't Run On Your PC (Rectify11)

### ISSUE THREAD

**Issue by DefaultUser9148** [t1m0thyj/WinDynamicDesktop#503]
Windows 11 Modified With Rectify, App Does not run after Install

**Comment by t1m0thyj** [comment]
@DefaultUser9148 Is this your first time using WDD, or did previous versions like 5.1.0 work with Rectify?

**Comment by t1m0thyj** [comment]
Not planning to support modded Win11 versions unless there is more demand for it.
