### ISSUE TITLE
App start-up error

### ISSUE THREAD

**Issue by treispezeronoua** [t1m0thyj/WinDynamicDesktop#504]
I'm using Windows 11 22H2, OS build 22621.1105, with the WinDynamicDesktop app installed from the GitHub *.exe file.

After updating from version 5.1.0 to 5.2.0, once the updated application started, I received the error below documented in the WinDynamicDesktop.exe.log file:

"[2023-01-18 21:46:46.298] System.InvalidCastException: No such interface supported

   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at Windows.System.UserProfile.LockScreen..cctor()
"

However, the app seems to be working fine after a Windows reboot and I was unable to replicate the error.

- WDD Version: 5.2.0
- OS Version: Windows 11, OS build 22621.1105

Steps to Reproduce:

1. Update app from 5.1.0 version to 5.2.0
2. First app start-up after update.

Are you using the Microsoft Store version of WDD?: No

**Comment by t1m0thyj** [comment]
Closing as I am not aware of anyone else reproducing this in newer versions.
