### ISSUE TITLE
"All displays" missing string in translations?

### ISSUE THREAD

**Issue by Hexaae** [t1m0thyj/WinDynamicDesktop#507]
- WDD Version: 5.2.0 UWP
- OS Version: Windows 11 22H2

I just revised the Italian translation on poeditor.com but couldn't find the string "All displays" (ITA: "Tutti gli schermi") in the upper left:
![image](https://user-images.githubusercontent.com/8591462/219072308-c1a18ccd-4dc7-491e-a0ec-fc03bcfbb16a.png)

Are you using the Microsoft Store version of WDD?: Yes

**Comment by t1m0thyj** [comment]
Thanks for translating WinDD and reporting this, I've added "All Displays" and a few other missing strings to PoEditor.

After adding the term the combobox still won't be translated due to a bug in WinDD, but I'll fix this in the next release.

**Comment by Hexaae** [comment]
Updated Ita catalog 👍

**Comment by t1m0thyj** [comment]
Fixed in v5.2.1
