### ISSUE TITLE
Font readability problems (1920x1080 100% Win11)

### ISSUE THREAD

**Issue by Hexaae** [t1m0thyj/WinDynamicDesktop#508]
- WDD Version: 5.2.0 UWP
- OS Version: Windows 11 22H2

Steps to Reproduce:

1. run the program: the UI will have very thin and brownish ugly fonts on my screen: 1920x1080 100% font size.
E.g. (full size WDD UI. See std OS fonts instead used for the screen capture program):
![image](https://user-images.githubusercontent.com/8591462/219074631-6339b09b-a11f-44fb-b23e-2602fdc36780.png)

Are you using the Microsoft Store version of WDD?: Yes

**Comment by t1m0thyj** [comment]
Thanks for reporting this, I believe it may be fixed in the latest build. Could you please try downloading an EXE from here and let me know if it works? https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/4163698360

**Comment by Hexaae** [comment]
EXE seems ok... Can't install and double-check the x64 MSIX: missing valid certificate.

**Comment by t1m0thyj** [comment]
Fixed in v5.2.1
