### ISSUE TITLE
Shuffle theme improvement, make a queue/playlist so all themes get its turn (the same theme does not shuffle twice in the same playlist).

### ISSUE THREAD

**Issue by bigplayer-ai** [t1m0thyj/WinDynamicDesktop#510]
Done, The issue is when shuffle is enabled. I get the same theme twice without going over all the themes I have.

I want it to act like a music playlist to go over all the playlist without going back to the same theme if not all themes were ser beforehand.

**Comment by t1m0thyj** [comment]
> The same theme does not shuffle twice in the same playlist

This is how WDD is already supposed to behave. It stores "shuffleHistory" in settings.json, which is used to ensure that the same theme is not shown twice until all themes have had their turn.

Next time this happens, please upload your settings.json file (with location info redacted) that includes the "shuffleHistory" and provide the name of the theme being shown twice.
