### ISSUE TITLE
"minutes" string misplaced in the "Configure schedule..." panel

### ISSUE THREAD

**Issue by Hexaae** [t1m0thyj/WinDynamicDesktop#513]
- WDD Version: 5.2.1
- OS Version: Win11 22H2, 1920x1080 screen 100% scale

Steps to Reproduce:

1. open _Configure schedule..._ from menu. "minutes" ("minuti" in Italian) in the bottom-right is misplaced: 
![image](https://user-images.githubusercontent.com/8591462/220967098-2c6eab7b-79ff-45f1-a763-eeb04f0e7651.png)

Are you using the Microsoft Store version of WDD?: Yes

**Comment by Hexaae** [comment]
Also "Tramonto:" (sunset) in the bottom-left is a bit unjustified...

**Comment by Hexaae** [comment]
Since these are very easy to fix issues I hope to see them finally solved for next release 5.3.2...

**Comment by t1m0thyj** [comment]
This will be fixed in the next version:
![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/22344007/025ed04d-39e9-479a-b676-9cdd0d44c0fb)

**Comment by t1m0thyj** [comment]
Fixed in WinDD 5.4.0
