### ISSUE TITLE
[Feature request] Follow Windows Night Light mode.

### ISSUE THREAD

**Issue by bigplayer-ai** [t1m0thyj/WinDynamicDesktop#517]
Done

Follow Windows Night Light mode times instead of getting the times of the location.
![Clip_20230309_224452](https://user-images.githubusercontent.com/119108387/224153122-5f4f2130-9a36-4204-a25b-aaad6b49d9be.png)

**Comment by t1m0thyj** [comment]
I don't know of any events or APIs provided by Microsoft to detect when the "Night Light" status changes.

Closing since I also don't see high demand for this - the settings that already exist in WinDD to use Windows location or set manual hours should mimic the Night Light behavior pretty closely.
