### ISSUE TITLE
can't use mouse 

### ISSUE THREAD

**Issue by quark365** [t1m0thyj/WinDynamicDesktop#525]
The mouse pointer is not clickable within the app. Only the apps behind the window is being clicked, seems like its transparent or not there. Only enter and arrows can be used for navigation, issue seen in latest version 5.3.0.0.

**Comment by prakharb5** [comment]
I would like to add to this issue, that only the edges of the buttons or the text is now clickable. All the whitespaces (which now appear as the mica material) are unclickable, and get passed to another app behind the app's window.

**Comment by t1m0thyj** [comment]
The Mica background was cool but caused too many bugs, so replaced it with a custom dark theme in v5.3.1

**Comment by t1m0thyj** [comment]
@prakharb5 That would probably fix the issue as both of those frameworks have better support for Mica than WinForms. Currently I don't have time to make the switch, but contributions are welcome if anyone is interested in a UI rewrite 🙂
