### ISSUE TITLE
Add Windows 11 Wallpaper

### ISSUE THREAD

**Issue by xmha97** [t1m0thyj/WinDynamicDesktop#526]
Please add the Windows 11 wallpaper as a dynamic wallpaper.

![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/23485114/7534a74f-bb6a-4432-9639-bf3bb205821b)

Thanks

**Comment by prakharb5** [comment]
Although the Win11 wallpaper is offered on the themes website [(here)](https://windd.info/themes/), it would be cool to have it as a built-in option in the app!

**Comment by xmha97** [comment]
> Although the Win11 wallpaper is offered on the themes website [(here)](https://windd.info/themes/), it would be cool to have it as a built-in option in the app!

Yes 👍

**Comment by t1m0thyj** [comment]
Added in WinDD 5.4.0
