### ISSUE TITLE
Black wallpaper when applying the Big Sur theme

### ISSUE THREAD

**Issue by l-zariqi** [t1m0thyj/WinDynamicDesktop#527]
- WDD Version: 5.3.1
- OS Version: Windows 11 22H2 (OS Build 22621.1848)

Steps to Reproduce:

1. Download and Apply Big Sur theme
2. Watch as desktop turns to black

Are you using the Microsoft Store version of WDD?: Yes

https://github.com/t1m0thyj/WinDynamicDesktop/assets/78166855/7d9edc79-399d-4326-b608-552da41bf8fd

**Comment by Jozoooooo** [comment]
I also encountered this problem, is there any solution?

**Comment by t1m0thyj** [comment]
> I also encountered this problem, is there any solution?

See https://github.com/t1m0thyj/WinDynamicDesktop/issues/216#issuecomment-670999900 for a solution that some users report has worked.
