### ISSUE TITLE
Cannot sync virtual desktop again in Win 11

### ISSUE THREAD

**Issue by 7HE-W0R1D** [t1m0thyj/WinDynamicDesktop#532]
- WDD Version: GitHub 5.3.1
- OS Version: Win11 22631.2048

Steps to Reproduce:

1. Set a theme / toggle night mode / refresh wallpaper
2. Only the focused desktop would change wallpaper

Are you using the Microsoft Store version of WDD?: No

I have the script enabled but it's still not working. Can't recall exactly when it stopped :(
![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/42311695/2a8a5c73-f434-4f24-a6c1-bc91a930f942)

**Comment by freecodecampster** [comment]
I just updated to insider build:
OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631

Now the virtual desktop script throws an exception.

**Comment by InfinitGit** [comment]
Same issue I think:
![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/124841095/523ac0b0-3697-4ea0-866b-5f7c2dd55bab)

**Comment by alexoliva91** [comment]
I had the same problem and I resolved it by updating this module [https://github.com/MScholtes/PSVirtualDesktop](https://github.com/MScholtes/PSVirtualDesktop), which the script uses.
Simply run, in a admin PS terminal:

`Update-Module VirtualDesktop`
