### ISSUE TITLE
Day Mode

### ISSUE THREAD

**Issue by Synaptic149** [t1m0thyj/WinDynamicDesktop#547]
I think it would be a nice idea to have a day mode. It's like night mode, but instead of selecting a dark wallpaper, it selects a bright wallpaper. One idea to present this feature is to replace the night mode toggle with a folder that contains these three options: night mode, day mode, and auto. Auto will be the normal mode.

**Comment by t1m0thyj** [comment]
This would behave similar to the "Light" option on MacOS
![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/22344007/9c7667cc-fae7-4da2-b487-ddbcb98f35c0)

**Comment by Synaptic149** [comment]
I don't have a Mac, but if it's making the wallpaper bright, then yes.

**Comment by t1m0thyj** [comment]
Added in WinDD 5.5.0
