### ISSUE TITLE
Crash with customized theme

### ISSUE THREAD

**Issue by graphixillusion** [t1m0thyj/WinDynamicDesktop#55]
Heya there. I followed the instructions for customizing the theme but when i put the custom theme.json inside the "themes" folder, the application crashes on start with this log:

`System.IO.FileNotFoundException: Il file 'C:\Users\MEFISTO\Downloads\WinDynamicDesktop\Earth_From_Space.json' non è stato trovato.
Nome file: 'C:\Users\MEFISTO\Downloads\WinDynamicDesktop\Earth_From_Space.json'
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   in System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   in System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   in System.IO.File.ReadAllText(String path)
   in WinDynamicDesktop.JsonConfig.LoadTheme(String name)
   in WinDynamicDesktop.ThemeManager.Initialize()
   in WinDynamicDesktop.AppContext..ctor()
   in WinDynamicDesktop.Program.Main()

UPDATE: 

I've understand what's going on: the program wants the json theme file in both of these locations: 
1) "themes" folder 
2) same location of the executable

With this config i have no more crash on start and the program can see the new theme in the theme manager window.
`
UPDATE 2

I've found another bug. I will post my steps for replicate it:

1) Open the application
2) Right click on the icon in the system tray ---> Select Theme
3) The Theme manager window will show up ---> select any theme and apply it clicking ok
4) Right click again on the icon in the system tray---> Select Theme again
5) The Theme manager window will NOT show up anymore. You need to close and reopen the program to make it works again.

Last thing: i'm always get this message whenever i run the executable (portable one)

> https://i.imgur.com/bmTmRYj.png
`You need to install an app for this activity. Search it in the Store?`

**Comment by graphixillusion** [comment]
Thank you for the support. About the dialog: maybe it searching for some store's dependency? I have decrapified my system with a script but i still have the store installed.

**Comment by t1m0thyj** [comment]
Fixed the second bug in version 2.0.2.

Regardingt the dialog, are you using the Windows Store version of the app or have you downloaded it from GitHub?

**Comment by graphixillusion** [comment]
Sorry if i didn't answer before. I'm using the version downloaded from github.

**Comment by t1m0thyj** [comment]
Both bugs have been fixed, unfortunately I don't know that I can do much about the Windows Store message since I can't reproduce it and no one else has reported it. If you would like to investigate it further, feel free to create a separate issue for it.
