### ISSUE TITLE
Custom Theme: shuffle images in segments

### ISSUE THREAD

**Issue by barmat80** [t1m0thyj/WinDynamicDesktop#559]
Hello.
I created my own theme and I think it could be nice if one can set a shuffle of the images for every single segment (sunrise, day etc...) or for all the segments.

Mattia

**Comment by t1m0thyj** [comment]
Shuffle per segment would be neat but kind of tricky to implement since not all themes have the same number of segments (2, 3, 4 are all supported).

The next version of WinDD will have more shuffle options for every hour, 12 hours, daily, etc.

**Comment by t1m0thyj** [comment]
Closing as not planned. If you want to shuffle images in segments, a workaround would be to create multiple versions of the theme where each one has the same images in a different order. Then add all these themes as favorites and turn on the option to shuffle only favorite themes.
