### ISSUE TITLE
"Errors occurred" on user account disconnection

### ISSUE THREAD

**Issue by Hexaae** [t1m0thyj/WinDynamicDesktop#569]
- WDD Version: 5.4.1 MS
- OS Version: Win 11 23H2

Steps to Reproduce:

1. set WDD to be run on startup
2. boot Windows (will launch WDD in background)
3. disconnect current user from Start menu > click on your profile icon > Disconnect

Are you using the Microsoft Store version of WDD?: Yes

On user account disconnection there is an error during Win 11 shutdown showing "Errors occurred" as a task blocking shutdown.
Going back to desktop (selecting Cancel on the shutdown screen) for a brief moment I was able to catch this:

![Screenshot_20240223-175549](https://github.com/t1m0thyj/WinDynamicDesktop/assets/8591462/b2855f4d-5da7-4208-b59d-7fe28a499b5d)

Here is that log in the picture:
[WinDynamicDesktop.dll.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/14388009/WinDynamicDesktop.dll.log)

**Comment by Hexaae** [comment]
(BTW, I suggest to use appropriate windows titles to determine the task they refer to... e.g. in this case "WinDynamicDesktop - Errors occurred")

**Comment by t1m0thyj** [comment]
Fixed in 5.4.2
