### ISSUE TITLE
Settings open only once after app start.

### ISSUE THREAD

**Issue by Schlaefer** [t1m0thyj/WinDynamicDesktop#57]
- start the app
- open the settings with "Select Themes"
- close settings
- try to open the settings a second time

Instead of opening the settings again nothing happens.

Store version 2.0.0.0

**Comment by t1m0thyj** [comment]
Sorry for this serious bug on first run, I'll try to get a fix released tonight.

In the meantime, if you go the folder `%LOCALAPPDATA%\Packages\38719TimothyJohnson.WinDynamicDesktop_rfarkse4rn21a\LocalState` and edid the file `settings.conf`, you should be able to change the `themeName` value to "Mojave_Desert", "Solar_Gradients", or "None". Make sure the app is closed before editing the file, then after setting the themeName restart the app and it should work.

**Comment by t1m0thyj** [comment]
The serious bug that was keeping the wallpapers from changing is fixed in version 2.0.1. I thought that was identical to this problem of the dialog not opening again, unfortunately it was not. This fix will be in the next version, sorry for the delay.

**Comment by t1m0thyj** [comment]
Fixed in version 2.0.2.
