### ISSUE TITLE
No automatic replacement theme options.

### ISSUE THREAD

**Issue by qingyuhub** [t1m0thyj/WinDynamicDesktop#572]
system version:windows11
WinDynamicDesktop:5.4.1 
issue: No automatic replacement theme options.
![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/157886500/afeb3671-4142-42de-98de-9c58b3d02a75)

**Comment by nil21t** [comment]
Just wanted to add as well that there is no option to sync the lockscreen as well. There is an option to sync all lockscreen images to one display, but no actual option to toggle the change of the lockscreen wallpaper. This option used to be under this menu as well.

**Comment by t1m0thyj** [comment]
These options still exist but were moved in WinDD 5.4.0. See https://github.com/t1m0thyj/WinDynamicDesktop/discussions/571#discussioncomment-8618257
