### ISSUE TITLE
Screen only shows black after theme selection

### ISSUE THREAD

**Issue by TheNativeGit** [t1m0thyj/WinDynamicDesktop#578]
- WDD Version: 5.4.2
- OS Version: WIN11 23H2 build 22631.3296

Steps to Reproduce:

1. Creating new ddw file with 10 new images
2. Starting WinDynamicDestop
3. Importing ddw file
4. Selecting and applying new theme
-> Notification: New Theme [name] applyed
-> Background stays black
The configuration file was not edited, only selected the timezone

Are you using the Microsoft Store version of WDD?: No

Additional information: I have been using WinDynamicWallpaper for a long time and have followed the same steps as the first time. But now I have created a new file, this is also displayed correctly in the program, the preview works, but applying it has ensured that the background remains permanently black. Selecting the old ddw file was also unsuccessful. The gif shows what I'm doing, a restart did not fix the issue.
![a68265e9-d616-431a-80b3-ae2595ca6deb](https://github.com/t1m0thyj/WinDynamicDesktop/assets/118630672/8e92ee18-6dfc-454b-afd9-44585dea3d08)

**Comment by t1m0thyj** [comment]
@TheNativeGit Please attach the contents of the theme JSON file you used in your DDW.

**Comment by TheNativeGit** [comment]
> @TheNativeGit Please attach the contents of the theme JSON file you used in your DDW.
Im sorry, the pictures are 10 png files and each is at least 40MB big and I cant upload above this limit. 
However,  wondered what would happen if I use jpg instead of png. These can be used and they work with WinDynamicWallpaper. 

Now I have the problem I'm probably legally not allowed to make this pictures public since '[kram.store](https://kram.store/)' doesn't allow it. Im sure its useless if I provide the jpg files anyway, since these work.
I assume it's because of the big file sizes? Each picture is a 6016 * 6016 and at least 40MB big.
![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/118630672/e08d1dd5-a51b-445d-8471-2f69a353c6ac)

Maybe there's is an file which logged the error I can provide? Thanks already and sorry for not being a big help here.

**Comment by t1m0thyj** [comment]
@TheNativeGit I don't need to see the images, just the theme JSON file mentioned [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes#theme-file) to see if anything looks wrong.

Also what happens if you navigate to one of your theme's images in File Explorer, right-click on it and select "Set as desktop background"? Curious if this works or if it results in a black background like setting the wallpaper through WinDD does.
