### ISSUE TITLE
wallpaper doesn't change after start\re-start.

### ISSUE THREAD

**Issue by deloextra** [t1m0thyj/WinDynamicDesktop#58]
After a boot or a re-start, the wallpaper dosen't change unless i select manually every time the theme. Also the  dark theme doesn't apply automatically and i must choose it manually.

**Comment by t1m0thyj** [comment]
Can you check what version of the app you're using in the About dialog? There was a serious bug related to wallpaper and theme changing in version 2.0, which I fixed last night in version 2.0.1. The update should be available for both the desktop and Windows Store versions.

**Comment by deloextra** [comment]
i updated to 2.0.1 and i personally have the prob. atm i only installed the 2.0.1 without update. hope this work

**Comment by t1m0thyj** [comment]
If you are still experiencing this issue, could you please try the following steps to aid in debugging it:

1. Delete the `settings.conf` file in the app folder to reset the app settings. (If you don't know where the app folder is, see below.)
2. Update to the latest version of the app (2.1.0). 
3. Run the app and see if you still experience problems with the wallpaper not changing until you manually "Refresh Wallpaper".
4. If so, check if there is a log file (`WinDynamicDesktop.exe.log`) in the app folder. If the file exists please upload it here. Also please mention what version of Windows you are running (7, 8.1, 10, etc.) and how you installed the app (either thru the Windows Store or downloaded from GitHub).

**Finding app folder**
The location where the app is installed is different depending on how you installed it:
 - Installer - Folder that you chose during the installation process (default location is `%LOCALAPPDATA%\Programs\WinDynamicDesktop`)
 - Microsoft Store - Folder where the app package is located (likely `%LOCALAPPDATA%\Packages\38719TimothyJohnson.WinDynamicDesktop_rfarkse4rn21a\LocalState`)
 - Portable EXE - Folder where the app EXE is
