### ISSUE TITLE
cant use translation from poeditor

### ISSUE THREAD

**Issue by febrimuhnas** [t1m0thyj/WinDynamicDesktop#581]
- WDD Version: 5.4.2
- OS Version: windows 11 pro 23h2

Steps to Reproduce:

1. edit the configuration file
2. change ["language": "he",] to [  "language": "poeditor:he",]
3. reload the configuration file
4. WDD cannot be opened or restarted at all.

Are you using the Microsoft Store version of WDD?: No

**Comment by t1m0thyj** [comment]
Fixed in https://github.com/t1m0thyj/WinDynamicDesktop/commit/109490ea4573c2e4f23ebbecc6bfa30885c4150d, you can download preview build here: https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/8577479010

**Comment by febrimuhnas** [comment]
It's works! Thankyou.
