### ISSUE TITLE
accurate to one hour

### ISSUE THREAD

**Issue by policx** [t1m0thyj/WinDynamicDesktop#583]
I have prepared 24 wallpapers, and I want to have corresponding wallpapers for each hour precisely. Can this function be added? Thank you very much.

**Comment by t1m0thyj** [comment]
If you want to schedule a new wallpaper for each hour of the day, this capability is built into Windows. See https://superuser.com/a/1492746/517562

**Comment by policx** [comment]
Firstly, thank you very much for your answer. Indeed, it is achieved through the function of the system slideshow. However, there are two problems. 1. When I start the computer at 3 p.m., the slideshow cannot locate to the 15th wallpaper according to the time, and it needs to be adjusted manually to update the wallpaper at an interval of one hour. 2. When there are multiple screens, the manual slideshow wallpapers are not synchronized on the two screens.

**Comment by t1m0thyj** [comment]
Thanks for sharing your solution 🙂 It should be helpful for anyone else who wants to have an hourly slideshow and finds the built-in capabilities of Windows lacking. Closing as completed, since this is outside the scope of planned features for WinDD.
