### ISSUE TITLE
Add command line support

### ISSUE THREAD

**Issue by xmha97** [t1m0thyj/WinDynamicDesktop#585]
Please add command line support, for example:
- `WinDynamicDesktop.exe --refresh` -> Refresh wallpaper
- `WinDynamicDesktop.exe --theme=auto` -> Set auto theme
- `WinDynamicDesktop.exe --theme=light` -> Set light theme
- `WinDynamicDesktop.exe --theme=dark` -> Set dark theme

**Comment by t1m0thyj** [comment]
Added support for the following commands in https://github.com/t1m0thyj/WinDynamicDesktop/commit/73bf93a9d4367fa7d42b76b9b1e841226e071919:
* `WinDynamicDesktop.exe /refresh`
* `WinDynamicDesktop.exe /theme:auto`
* `WinDynamicDesktop.exe /theme:light`
* `WinDynamicDesktop.exe /theme:dark`

You can download a test build from GitHub Actions [here](https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/9261612502). Are there any other commands that would be helpful to have?

**Comment by t1m0thyj** [comment]
Released in WinDD 5.6.0
