### ISSUE TITLE
App description text

### ISSUE THREAD

**Issue by xmha97** [t1m0thyj/WinDynamicDesktop#586]
Please change "Windows 10" to "Windows"

![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/23485114/891591bb-3e1d-4fae-93a8-0f9ae145f63a)

![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/23485114/d4915c2c-8beb-41bb-abb8-925887e50cf0)

![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/23485114/85e14df4-1a85-43c1-bcbd-15111a6300da)

This app works on Windows 7, Windows 8, and Windows 11, not only Windows 10.

**Comment by t1m0thyj** [comment]
Released in WinDD 5.6.0
