### ISSUE TITLE
WDD not starting with Windows 7.

### ISSUE THREAD

**Issue by FantasiaChan** [t1m0thyj/WinDynamicDesktop#59]
In log file:

System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в WinDynamicDesktop.ThemeManager.Initialize()
   в WinDynamicDesktop.AppContext..ctor()
   в WinDynamicDesktop.Program.Main()

**Comment by t1m0thyj** [comment]
The latest version of the app should run fine on Windows 7. Are you trying with the latest version 2.0.1?

Could you try deleting all other files inside the folder where the app EXE is (images and themes folders, settings.conf file, etc.) and verify that the app still does not run? If you still get the same error message I'll look into it more, currently I don't have any idea what would be causing it.

**Comment by samorinha** [comment]
not working on w7 

log file: 

System.TypeLoadException: Não foi possível carregar o tipo 'System.Collections.Generic.IReadOnlyDictionary`2' da assemblagem 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   em Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   em Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   em System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   em Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   em Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   em Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   em Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   em WinDynamicDesktop.JsonConfig.LoadTheme(String name)
   em WinDynamicDesktop.ThemeManager.Initialize()
   em WinDynamicDesktop.AppContext..ctor()
   em WinDynamicDesktop.Program.Main()

**Comment by t1m0thyj** [comment]
@samorinha Thanks for including the full error log. It seems like the app is crashing when it tries to load the theme JSON files. I'm not sure why this would happen unless you were creating a custom theme file and the contents were not valid JSON? But if you never created your own theme file then this is a bug.

**Comment by samorinha** [comment]
Hi, not creating anything, after Install it just does not Launch...

**Comment by t1m0thyj** [comment]
I believe I see what the problem is now based on the log. It is trying to load version 4.0.0.0 of a .NET DLL, but WinDynamicDesktop is built to target .NET Framework 4.6.1. Perhaps your machine does not have a new enough version of .NET Framework to run the app. Could you try installing .NET Framework 4.6.1 ([download link](https://www.microsoft.com/en-us/download/details.aspx?id=49981)) and see if that fixes the problem?

If you want to check which .NET Framework versions are installed on your machine, there are instructions for how to do that [here](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed).

**Comment by samorinha** [comment]
> I believe I see what the problem is now based on the log. It is trying to load version 4.0.0.0 of a .NET DLL, but WinDynamicDesktop is built to target .NET Framework 4.6.1. Perhaps your machine does not have a new enough version of .NET Framework to run the app. Could you try installing .NET Framework 4.6.1 ([download link](https://www.microsoft.com/en-us/download/details.aspx?id=49981)) and see if that fixes the problem?
> 
> If you want to check which .NET Framework versions are installed on your machine, there are instructions for how to do that [here](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed).

updating the framework dit it!
working ok now!! thanks

**Comment by t1m0thyj** [comment]
Installing .NET Framework 4.6.1 [download link](https://www.microsoft.com/en-us/download/details.aspx?id=49981) should fix this issue. I'll add a note to the README about this and maybe put code in the installer that checks what versions of the framework are installed.

**Comment by michael555444** [comment]
sorry, but I have the same problem while using .NET Framework 4.6.1 or latest version(Win 10).
what should I do now?

/*
   System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в WinDynamicDesktop.UpdateHandler.UpdateToVersion4()
   в WinDynamicDesktop.JsonConfig.LoadConfig()
   в WinDynamicDesktop.AppContext..ctor(String[] args)
   в WinDynamicDesktop.Program.Main(String[] args)
*/
