### ISSUE TITLE
Windows 10 dark/light theme not changing (Store)

### ISSUE THREAD

**Issue by DragoCubed** [t1m0thyj/WinDynamicDesktop#60]
It just doesn't change. I've tried restarting, toggling it on and off and reinstalling WDD. There's obviously no error code. It's night time for me right now (in Australia) and Windows hasn't changed the theme.

**Comment by t1m0thyj** [comment]
Unfortunately I can't reproduce this on my machine in the latest version of the app. Could you try opening the Registry Editor, navigate to `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize` (you can paste the path in at the top of the window), and manually toggle the `AppsUseLightTheme` value (create if it doesn't exist) between 0 and 1? 0 means dark theme and 1 means light, you should see it change right away if you have an app open that gets themed like Windows 10 Settings. Changing this registry value is what the app should be doing under the covers.

**Comment by DragoCubed** [comment]
I set `AppsUseLightTheme ` from 1 to 0 and it worked. Everything is dark. I'm not sure why WDD doesn't change it automatically 😕

**Comment by deloextra** [comment]
what setting i should set to activate the auto-dark theme ?

**Comment by t1m0thyj** [comment]
@deloextra Click on the system tray icon to bring up the main menu, then select "Change Windows 10 Theme". This should make the app theme light during the day and dark at night.

**Comment by 19lmyers** [comment]
I'm also having this issue (#53)

**Comment by DragoCubed** [comment]
The latest update fixed it! Thanks Tim!
