### ISSUE TITLE
Wallpaper changes after WDD is uninstalled

### ISSUE THREAD

**Issue by anaruzhnii** [t1m0thyj/WinDynamicDesktop#616]
I installed WDD a while ago and recently started seeing the different wallpaper timings on my monitors (Big Sur wallpaper). 
I decided to reinstall WDD (and keep the user data) and set the different WDD wallpaper. The next day, when I turned on the PC (around 9 AM), I saw my old WDD wallpaper (Big Sur) with different timings again.
Then I decided to completely uninstall WDD (and delete the user data) and set Windows Spotlight wallpaper. Today, when I turned on the PC, I saw my old WDD wallpaper (Big Sur) with different timings again.

- WDD Version: 5.6.0
- OS Version: Windows 11 22631.4317

Steps to Reproduce:

1. Choose a wallpaper
2. Uninstall WDD
3. Wait for a night

Are you using the Microsoft Store version of WDD?: No

**Comment by t1m0thyj** [comment]
It shouldn't be possible for WDD to continue setting wallpapers after it is uninstalled, since it doesn't make use of the scheduled wallpaper feature built in to Windows.

Could you check if WDD is still running somehow after uninstalling it, by opening Task Manager and checking for a process named WinDynamicDesktop?

**Comment by anaruzhnii** [comment]
Hi Timothy,

I've checked the task manager and didn't find any processes looking like WDD.

I start to think that Windows just switched the wallpaper mode to "Picture" and put the WDD pictures there for some reason.
Let me get back to you in a couple of days to check that theory.

**Comment by anaruzhnii** [comment]
@t1m0thyj it turned out that I also have Auto Dark Mode installed that for some reason switched the wallpapers.

Closing the issue, sorry for bothering.
