### ISSUE TITLE
Error message is displayed when we try to import file with WDD

### ISSUE THREAD

**Issue by Michellehdr** [t1m0thyj/WinDynamicDesktop#619]
- WDD Version: v5.6.0.0
- OS Version: Windows 11

Steps to Reproduce:

1. Deploy latest OS and Perform Windows and Store updates.  
2. Install WDD from store.
3. Launch the application.
4. Select the language as English and click on ok.
5. Click on yes in the location access prompt window. 
6. Select use location to determine sunrise or sunset times.
7. Enter the location and click on ok.
8. Click on "import from file" option in bottom left side of the app. 
9. Try to import any file from CFD window.
10. Observe the error.

Actual Result:
Error message is displayed when we try to import file.
![image](https://github.com/user-attachments/assets/6971aa78-7e46-4300-9a65-31d89a56886d)

Are you using the Microsoft Store version of WDD?: Yes

**Comment by t1m0thyj** [comment]
Based on the error message it seems that you selected a JPG image in the "Import from file" picker.

The only file types that are supported for importing themes are `.zip` archives, `.ddw` files (which are just `.zip` archives with a different extension), or `.json` files in a folder that contains images alongside them.

**Comment by Michellehdr** [comment]
@t1m0thyj Thanks for the quick response. yes, the issue no longer repro if select a supported file type as you listed. I close the bug as completed. Thanks a lot for your great support.
