### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MisterGlasses** [t1m0thyj/WinDynamicDesktop#62]
when  I update to 2.0.1.0 through Microsoft store,the error shows.
![image](https://user-images.githubusercontent.com/27768847/44618666-0286d700-a8ad-11e8-9945-ba2dc827b582.png)

**Comment by t1m0thyj** [comment]
If you click the Retry button does the error still continue? If the download just failed once that might happen sometimes and isn't a big deal. But if it keeps on failing, I wonder if the problem could be related to one of the download links being on OneDrive which might be blocked in some countries, I'd have to look into that further.

**Comment by MisterGlasses** [comment]
there are no use clicking the retry button .
And in china,OneDrive is unstable whick almost cannot be used.
But when i click the cancel button,WinDynamicDesktop can work because the last version has already Download the imagine.However,everytime i reboot my computer,the error shows

**Comment by t1m0thyj** [comment]
Can you try downloading the ZIP file of images from the following link? https://we.tl/t-pu6s0BXL4A

If the download works, then extract the JPEG images from the ZIP file, and copy them into the "images" folder of the app. After dropping the images into the folder, you should no longer see the warning message.

If the download doesn't work, let me know and I can try to find another host. Ideally I should find a free host for the wallpapers with unlimited bandwidth and high uptime that is accessible worldwide.

**Comment by MisterGlasses** [comment]
Can you tell me where is the folder of the app?

**Comment by MisterGlasses** [comment]
I can download the images manually,and I found why the problem shows.
WinDynamicDesktop can download Mojave Desert automaticlly,but can not download solar_gradients.
When I copy the images I downloaded manually into the images folder ,WinDynamicDesktop works.
So please check wheather it is a bug or not!Thank you for your help.

**Comment by t1m0thyj** [comment]
Thanks for the update, I've created #64 as a followup.

**Comment by Rukawalee** [comment]
How to get solar_gradients.zip?

**Comment by t1m0thyj** [comment]
@Rukawalee Please let me know if the link posted above works for you.

**Comment by Rukawalee** [comment]
Thanks, xiaolongLv3。
This link could use but with vpn, so i try down with app by vpn.
