### ISSUE TITLE
WinDynamicDesktop don't start with Windows 10

### ISSUE THREAD

**Issue by Gabricore-i9** [t1m0thyj/WinDynamicDesktop#65]
WinDynamicDesktop don't start with Windows 10

**Comment by t1m0thyj** [comment]
Sorry but I need more information to be able to fix this bug:
 - Is the "Start on boot" option selected?
 - Log file (if it exists, see below for how to find it)
 - WinDynamicDesktop version (e.g. 2.0.0)
 - Installation source (e.g. installer, Microsoft Store, portable EXE)

**Finding log file**
If WinDynamicDesktop crashes, it should log error info to the file `WinDynamicDesktop.exe.log`. The location of the log file is different depending on how you installed the app:
 - Installer - Folder that you chose during the installation process (default location is `%LOCALAPPDATA%\Programs\WinDynamicDesktop`)
 - Microsoft Store - Folder where the app package is located (likely `%LOCALAPPDATA%\Packages\38719TimothyJohnson.WinDynamicDesktop_rfarkse4rn21a\LocalState`)
 - Portable EXE - Folder where the app EXE is

**Comment by Gabricore-i9** [comment]
I will answer you tomorrow because I can not today...

Il giorno gio 4 ott 2018 alle ore 13:14 Timothy Johnson <
notifications@github.com> ha scritto:

**Comment by Gabricore-i9** [comment]
I'm sorry but I didn't have activated the option "Start with Windows".
Your app is very good adn you had a nice idea.
Sorry for my bad English

Il giorno gio 4 ott 2018 alle ore 13:29 Gabriele Cano <
gabriele05.cano@gmail.com> ha scritto:
