### ISSUE TITLE
Retry fetching sunrise/sunset data if Internet connection is down

### ISSUE THREAD

**Issue by t1m0thyj** [t1m0thyj/WinDynamicDesktop#7]
Occasionally the wallpaper fails to update when I wake my laptop from sleep. I believe this is caused by the Internet connection not coming up quickly enough for the program to get the new sunrise/sunset data.

**Comment by Martin5001** [comment]
Also maybe the tray icon could change according to the connection status so the user won´t think that your app is broken.

**Comment by t1m0thyj** [comment]
@Martin5001 That is a good idea, but after implementing #17, this will no be longer necessary because a constant Internet connection will not be required by the app.

**Comment by t1m0thyj** [comment]
App no longer requires a constant Internet connection to fetch sunrise/sunset times, so closing this.
