### ISSUE TITLE
Spanning multiple monitors - Feature request

### ISSUE THREAD

**Issue by arbitraryusername123** [t1m0thyj/WinDynamicDesktop#70]
I happen to have a triple-monitor setup, and the backgrounds look great when using the span option to sort of stitch them together across the three. The only slight problem that I have is that every single time a new image is set to be the background, the images revert to repeating themselves across each monitor. It would be great if there were an option in the program to retain the "spanned" setting each time the wallpapers are updated. Thanks and keep up the great work!

**Comment by t1m0thyj** [comment]
I believe this may be a duplicate of #40. I assume you're using the Windows Store app if you're experiencing this issue? I couldn't find a way to fix it in the Store app, but if you download the desktop version from GitHub, that should retain whatever wallpaper setting you last selected when the wallpapers change.

**Comment by arbitraryusername123** [comment]
Yup, tried that and it appears to have fixed the issue. Thanks for the help!
