### ISSUE TITLE
Earth View

### ISSUE THREAD

**Issue by MisterGlasses** [t1m0thyj/WinDynamicDesktop#71]
I got a series of wallpapers,but It is heic type.I don't know how to transform it into jpg.So I ask for help.
The link is https://www.dropbox.com/s/kd2g59qswchsd0v/Earth%20View.heic?dl=0
Thank you very much.

**Comment by t1m0thyj** [comment]
Added documentation to the wiki about [this](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes#image-files). There is also now an Earth View theme someone else has created available for download.

**Comment by MisterGlasses** [comment]
Thank you very much.I created one too.
