### ISSUE TITLE
Event viewer error ID 1000 at each launch of WinDynamicDesktop

### ISSUE THREAD

**Issue by KB4284848** [t1m0thyj/WinDynamicDesktop#72]
Hi,

I installed WinDynamicDesktop from Store and allowed it to start on boot. 
Everything runs fine but however by looking at event viewer I noticed that at each boot of my computer it logs an error ID 1000 Application Error.

They all look like that 

```Faulting application name WinDynamicDesktop.exe, version: 2.1.0.0, timestamp: 0x5bcf01e0
Faulty module name: KERNELBASE.dll, version: 10.0.17763.1, timestamp: 0x30bd5043
Exception code: 0xe0434352
Error offset: 0x0011aaf2
Failed process ID: 0x1f58
Start time of the failed application: 0x01d46ee94bee457a
Path of the failed application: C:\Program Files\WindowsApps\38719TimothyJohnson.WinDynamicDesktop_2.1.0.0_neutral__rfarkse4rn21a\WinDynamicDesktop\WinDynamicDesktop.exe
Faulty module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: bd69f919-2ca2-4288-84a2-dd24e3f67665
Full name of the failed package:
ID of the application relating to the failed package:
```

 - Screenshots 
![capture](https://user-images.githubusercontent.com/42769194/47620437-fe13b000-dae1-11e8-9631-647e5b923d2a.PNG)

 - Log file : doesn't exist
 - Windows version : 10 
 - Build number 17763.104 (Release Preview Ring of Insider Program)
 - WinDynamicDesktop version : 2.1.0.0
 - Installation source : Microsoft Store

**Comment by t1m0thyj** [comment]
I can't reproduce the error and unfortunately the exception code in the event log is pretty generic so I'm not sure what's happening. Is there more info in the Details tab of the Event Viewer like a stack trace? If so that would be helpful. Am I correct that there aren't any error messages which popup on the screen when the app runs and it doesn't crash, it just logs this to the event log on startup?

**Comment by KB4284848** [comment]
Hi,

> Am I correct that there aren't any error messages which popup on the screen when the app runs and it doesn't crash, it just logs this to the event log on startup?

Yes exactly this, which is pretty weird.

>  Is there more info in the Details tab of the Event Viewer like a stack trace? 

For this event I got that in the Details tab

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-10-28T18:09:00.795818200Z" /> 
  <EventRecordID>8912</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>HP_PAV_LOUIS</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>WinDynamicDesktop.exe</Data> 
  <Data>2.1.0.0</Data> 
  <Data>5bcf01e0</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.17763.1</Data> 
  <Data>30bd5043</Data> 
  <Data>e0434352</Data> 
  <Data>0011aaf2</Data> 
  <Data>1f58</Data> 
  <Data>01d46ee94bee457a</Data> 
  <Data>C:\Program Files\WindowsApps\38719TimothyJohnson.WinDynamicDesktop_2.1.0.0_neutral__rfarkse4rn21a\WinDynamicDesktop\WinDynamicDesktop.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>bd69f919-2ca2-4288-84a2-dd24e3f67665</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

![capture](https://user-images.githubusercontent.com/42769194/48078338-233ea780-e1e1-11e8-8b9e-367925f91eb4.PNG)
![capture](https://user-images.githubusercontent.com/42769194/48078374-33ef1d80-e1e1-11e8-9316-efb38e68fbb9.PNG)

After installation of re-released KB4464455 the 30th October leading to build number 17763.107 (see https://blogs.windows.com/windowsexperience/2018/09/18/announcing-windows-10-insider-preview-build-17763/) I can find one other event which happened the 1st November 
![capture](https://user-images.githubusercontent.com/42769194/48078821-06ef3a80-e1e2-11e8-9243-842607aac8a5.PNG).

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-11-01T16:51:30.430991700Z" /> 
  <EventRecordID>10121</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>HP_PAV_LOUIS</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>WinDynamicDesktop.exe</Data> 
  <Data>2.1.0.0</Data> 
  <Data>5bcf01e0</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.17763.1</Data> 
  <Data>30bd5043</Data> 
  <Data>e0434352</Data> 
  <Data>0011aaf2</Data> 
  <Data>cf4</Data> 
  <Data>01d4720317ab8539</Data> 
  <Data>C:\Program Files\WindowsApps\38719TimothyJohnson.WinDynamicDesktop_2.1.0.0_neutral__rfarkse4rn21a\WinDynamicDesktop\WinDynamicDesktop.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>902fab2a-feab-4d6e-aa39-dddfb319c9af</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

An other thing I discovered by looking at event viewer is that regularly I also got some .NET Runtime errors you will find here the most recent one
![capture](https://user-images.githubusercontent.com/42769194/48079226-d9ef5780-e1e2-11e8-88e7-4e80eb88cab2.PNG)
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-11-06T15:20:20.961589900Z" /> 
  <EventRecordID>11427</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>HP_PAV_LOUIS</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application : WinDynamicDesktop.exe Framework Version : v4.0.30319 Description: The service was stopped because of an unhandled exception. Exception information : System.UnauthorizedAccessException à System.IO.__Error.WinIOError(Int32, System.String) à System.IO.Directory.SetCurrentDirectory(System.String) à WinDynamicDesktop.Program.Main()</Data> 
  </EventData>
  </Event>

**Comment by t1m0thyj** [comment]
I just noticed that according to the log data it looks like you're using .NET Framework v.4.0.30319. WinDynamicDesktop requires version 4.5 or later, could you try installing .NET Framework 4.6.1 from [here](https://www.microsoft.com/en-us/download/details.aspx?id=49981) and see if that resolves the issue?
