### ISSUE TITLE
Earth View available now

### ISSUE THREAD

**Issue by Bagetta** [t1m0thyj/WinDynamicDesktop#74]
I created the Earth View theme for this utility, you can use it:

[earth_view.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/2561222/earth_view.zip)

P.S. The .json file has a link to download images from the repository (~90 days from now will be valid), but you can just drop the images from the archive into the folder.

![earth_view_11](https://user-images.githubusercontent.com/6232241/48191848-44c19f80-e357-11e8-80f4-66e76d4a62e2.jpeg)

**Comment by t1m0thyj** [comment]
@Bagetta I plan to create a list of community created themes on the GitHub wiki (yours being the first one). I want to make sure you're OK with me putting it on the list?

**Comment by samorinha** [comment]
how to add the theme ?

**Comment by Bagetta** [comment]
> @Bagetta I plan to create a list of community created themes on the GitHub wiki (yours being the first one). I want to make sure you're OK with me putting it on the list?

of course

**Comment by t1m0thyj** [comment]
Added your theme to [the list](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Community-created-themes#earth-view). I changed the timing of the images slightly because they seemed to have not been changed from the Mojave Desert theme and were a bit off.
