### ISSUE TITLE
[19H1] Feature Request - Change Windows theme in addition to app theme

### ISSUE THREAD

**Issue by 19lmyers** [t1m0thyj/WinDynamicDesktop#76]
Windows 10 19H1 added a new Windows theme option. Would it be possible to support changing that as well?

**Comment by t1m0thyj** [comment]
It should be possible for WinDynamicDesktop to change the new "app theme" setting if I know what registry key is used for the new setting.

Could you check the following path in the registry and see what all settings are listed? `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize`

The only settings I have are these:
![image](https://user-images.githubusercontent.com/22344007/48556019-b1392300-e8b0-11e8-84bc-58286f7324f7.png)

My guess would be the new registry setting should show on the list there, but it could be somewhere else totally different.

**Comment by 19lmyers** [comment]
[image: image.png]
This new key shows up in the same location as the old ones.

-- 

Sent from Inbox

**Comment by 19lmyers** [comment]
![image](https://user-images.githubusercontent.com/14363487/48584342-53233480-e8de-11e8-8f2f-2582ecaf6e2e.png)

This new key shows up in the same place for me.

**Comment by megaRammy** [comment]
I made a pull request for the basic feature, as it's currently implemented, it will make that registry key on older builds of Windows, which... shouldn't be an issue, as far as I know, but if anyone knows better and how to address that so it only attempts to change system theme if on a Windows build with that feature, feel free 😛 

#77

**Comment by t1m0thyj** [comment]
Fixed in version 2.3.0
