### ISSUE TITLE
New Theme: New York

### ISSUE THREAD

**Issue by SteveyCario** [t1m0thyj/WinDynamicDesktop#78]
New York theme for windynamicdesktop
Images taken from Jetson Creatives, the creator of 24 Hour Wallpapers for MacOS Dynamic Desktop
HEIF images converted to JPEG, renamed

JSON file included inside zip containing all converted images. 
USERNAME in "imagesZipUri" needs to be edited.
[NewYork.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/2588090/NewYork.zip)

**Comment by t1m0thyj** [comment]
Thanks, added it to the list

**Comment by t1m0thyj** [comment]
Sorry, had to remove these themes because the photographer requested I take them down for copyright reasons.
