### ISSUE TITLE
New Theme: San Francisco

### ISSUE THREAD

**Issue by SteveyCario** [t1m0thyj/WinDynamicDesktop#79]
San Francisco theme for windynamicdesktop
Images taken from Jetson Creative, the creator of 24 Hour Wallpapers for MacOS Dynamic Desktop
HEIF images converted to JPEG, renamed

JSON file included inside zip containing all converted images. 
USERNAME in "imagesZipUri" needs to be edited.
[SanFrancisco.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/2588095/SanFrancisco.zip)

**Comment by t1m0thyj** [comment]
Thanks, added it to the list
