### ISSUE TITLE
New Theme: High Sierra

### ISSUE THREAD

**Issue by SteveyCario** [t1m0thyj/WinDynamicDesktop#80]
High Sierra theme for windynamicdesktop
Images taken from Jetson Creative, the creator of 24 Hour Wallpapers for MacOS Dynamic Desktop
HEIF images converted to JPEG, renamed

JSON file included inside zip containing all converted images. 
USERNAME in "imagesZipUri" needs to be edited.
[HighSierra.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/2588099/HighSierra.zip)

**Comment by t1m0thyj** [comment]
Thanks, added it to the list
