### ISSUE TITLE
New Theme: BitDay

### ISSUE THREAD

**Issue by PaQshet** [t1m0thyj/WinDynamicDesktop#82]
A fine theme with wallpapers created by [BloodyMarvellous](https://www.reddit.com/user/BloodyMarvellous), high res as well.

Json-file included in zip.
[BitDay.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/2637144/BitDay.zip)

**Comment by t1m0thyj** [comment]
Sorry for the delay, added it to the list. Thanks for the contribution!
