### ISSUE TITLE
New Theme: Firewatch

### ISSUE THREAD

**Issue by danimart1991** [t1m0thyj/WinDynamicDesktop#83]
A fine theme with Firewatch game wallpapers created by Olly Moss, high res as well.

Json-file included in zip.
[Firewatch.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/2679136/Firewatch.zip)

**Comment by PaQshet** [comment]
I feel kinda copied, but it's a nice theme you got there.

**Comment by t1m0thyj** [comment]
@danimart1991 Thanks for the contribution, added it to the list.

@PaQshet Not sure why you feel copied, it looks pretty different to me.
