### ISSUE TITLE
Unable to selecet theme 

### ISSUE THREAD

**Issue by BLANK-MOJO** [t1m0thyj/WinDynamicDesktop#88]
Submit your bug report or feature request here. If you have questions please ask them on [Gitter](https://gitter.im/t1m0thyj/WinDynamicDesktop) instead.

When reporting a bug please provide:
 - Steps to reproduce it --- Select Theme
 - Screenshots ![20190108192045](https://user-images.githubusercontent.com/46484467/50827673-1aea2080-137a-11e9-8fd2-109909fa61cc.png)
 - Log file [WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/2736487/WinDynamicDesktop.exe.log)
 - Windows version --- 7
 - WinDynamicDesktop version --- 2.3
 - Installation source --- WinDynamicDesktop.exe

**Comment by StormCoder7** [comment]
Is this after trying to download the Firewatch theme?

**Comment by StormCoder7** [comment]
If so check the closed issue "Can't import Firewatch Theme" ( #84 )

**Comment by BLANK-MOJO** [comment]
> Is this after trying to download the Firewatch theme?

Nah, right after downloading Mojave and Solar, only have two themes.

**Comment by t1m0thyj** [comment]
@BLANK-MOJO Could you please try the following steps to help with troubleshooting?

* Download [`wdd-logger.exe`](https://bitbucket.org/t1m0thyj/wdd-themes/downloads/wdd-logger.exe)
* Copy the EXE to the same folder where `WinDynamicDesktop.exe` is located (see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Finding-where-app-is-installed) if you don't know where it is)
* Double-click on `wdd-logger.exe` to run it. You should see a file `wdd-report.log` get created in the same folder after a few seconds.
* Attach the `wdd-report.log` file and upload it here.

**Comment by t1m0thyj** [comment]
Just released a new version (3.2.0) that I hope fixes this issue.
