### ISSUE TITLE
Add option to specify custom config path

### ISSUE THREAD

**Issue by anortiz08** [t1m0thyj/WinDynamicDesktop#89]
To support syncing theme settings between devices via OneDrive or other file syncing tools, it would be nice to have the ability to specify a custom path for the config file theme settings.

**Comment by t1m0thyj** [comment]
@anortiz08 Which version of the app are you using: the EXE from GitHub or the Microsoft Store app? If you're using the EXE from GitHub, you could install the app in your OneDrive folder and all the config files would sync up.

**Comment by anortiz08** [comment]
@t1m0thyj Thank you for the response. I am currently using the MS Store version for ease of application updates. Your suggestion would be a functional alternative but I still think it would be useful to have the option to leverage any version (MS Store or standalone) and specify a custom path for the theme settings.

**Comment by t1m0thyj** [comment]
This option has been added in version 3.1 which was just released (will take a day or two to show up on the Microsoft Store). If you create a file `WinDynamicDesktop.pth` in the same folder as the app EXE (see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) if you're not sure where that is), and add the custom path you want to use as the first line of the file, the app should use that folder.
