### ISSUE TITLE
Translated to RUS

### ISSUE THREAD

**Issue by FantasiaChan** [t1m0thyj/WinDynamicDesktop#94]
I KNOW ABOUT GITTER. Can you create a new branch for pull request?

WinDynamicDesktop 2.9.1 - RUS

**Comment by FantasiaChan** [comment]
P.s. Add a question label

**Comment by FantasiaChan** [comment]
shet

**Comment by t1m0thyj** [comment]
I'm not sure if I understand what you mean exactly. If you want to make a pull request that adds localization support and a Russian translation, that's great. I don't need to make it branch for that, you should just be able to create a fork and do work in it, then submit a PR.

If you're requesting that I maintain a separate version in a branch that is translated into Russian, I'm sorry but I can't do that. Once I'm able to add localization support to the app then you'll be able to add a Russian translation that will be in the main branch.

**Comment by FantasiaChan** [comment]
(

**Comment by FantasiaChan** [comment]
just check my vers

**Comment by t1m0thyj** [comment]
I'd be glad to check out your version but where is it? I don't see it on your GitHub.

**Comment by t1m0thyj** [comment]
I see it now, I'll let you know when I have localization support so you can add the translations. 👍
