### ISSUE TITLE
Wallpaper stays black after start until app launches after some time (this bug didn't happen previously). 

### ISSUE THREAD

**Issue by anton31kah** [t1m0thyj/WinDynamicDesktop#99]
When the device starts (or restarts) the wallpaper is black until the app launches in the system tray. This bug didn't happen in the past, but for a couple of weeks it has been like this and I couldn't figure out how to fix it.

App version 3.0.0
Windows 10 Build 17763
Installed from Microsoft Store

**Comment by StormCoder7** [comment]
Yeah same issue here

**Comment by F3neden** [comment]
I have this issue on only one of two devices. Probably different windows versions. 
On the one it stays black (it has the out of the box version). On the other I have hardcoded my location and disabled the check for wifi connection (corporate networks firewall blocks the traffic). There it has the wallpaper image from the last time the pc was running and updates it after some time.

**Comment by FantasiaChan** [comment]
+

**Comment by FantasiaChan** [comment]
I think that this is normal, because WDD does not start immediately after turning on the computer..
Even if it is in autoload

**Comment by t1m0thyj** [comment]
Although WDD doesn't start immediately after turning on the computer, the wallpaper that shows before it loads should be the last one that it set rather than a black screen. This seems to be a bug only present in the Windows Store version AFAICT, and is due to the registry entry for the current wallpaper not getting updated like it should.

**Comment by FantasiaChan** [comment]
after a sharp shutdown of the computer (for some unknown reason), this bug also began to appear

**Comment by t1m0thyj** [comment]
This should be fixed in the latest version of the store app (3.3.0) that was just released.
